### ISSUE TITLE
zcml condition for including archetypes related code is not specific enough

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.restapi#1004]
There are some `zcml:condition="installed Products.Archetypes"` that might conflict with BBB patches providing aliases for the Python3 migration.
E.g. if you have some code like:
```
alias_module("Products.Archetypes", missing_archetypes)
```

That will make the startup of the instance fail with:
```
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/home/ale/.buildout/eggs/plone.restapi-6.13.7-py3.8.egg/plone/restapi/deserializer/configure.zcml", line 28.4-28.56
   ...
    File "/home/ale/.buildout/eggs/plone.restapi-6.13.7-py3.8.egg/plone/restapi/configure.zcml", line 76.2-76.37
    ModuleNotFoundError: No module named 'Products.Archetypes.event'
```
I would propose to change the zcml conditional with 
`zcml:condition="installed Products.Archetypes.atapi"` which has a very low chance of being present in the aliased module.

**Comment by ale-rt** [comment]
Any comment on this? ^

**Comment by thet** [comment]
I think this is a good fix with no risk of breaking anything.

**Comment by tisto** [comment]
The good thing about AT is that it is stable so I don't see a problem with a more specific check here.
