### ISSUE TITLE
Support for not queries in p.restapi

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#1010]
Not queries are around since Products.ZCatalog 4.0 but they never got first class support in Plone, and only can be accessed programatically.

Having that available for p.restapi would be great, but we have to come up with a syntax for the querystring.

We could also support it for the p.a.querystring (which might be easier).

**Comment by sneridagh** [comment]
Outcome: We can stop filtering things by doing the "positive query", e.g. Types to show in the search.

**Comment by davisagli** [comment]
New operators were added in plone.app.querystring: https://github.com/plone/plone.app.querystring/blob/master/CHANGES.rst#160-2022-05-26
