### ISSUE TITLE
Include widget info in JSON Schema produced by @types endpoint

### ISSUE THREAD

**Issue by lukasgraf** [plone/plone.restapi#104]
The JSON Schema produced by `@types/[portal_type]` currently only includes the field type, but no information about which widget should be used. This information should be included in the JSON Schema as well.

A custom widget for a field can be specified using a [`plone.autoform` directive](https://github.com/plone/plone.autoform/#changing-a-field-s-widget). That information then gets stored on the schema interface using tagged values, which should be easy to access and serialize.

The default widget however for a particular `zope.schema` field type is currently being determined by `z3c.form`, which means we might need to replicate some of `z3c.form`'s logic.

/cc @ebrehault

**Comment by tisto** [comment]
We need this as well soonish. We already include a widget attribute for some fields but not for all. Will look into it.

**Comment by ebrehault** [comment]
In angular2-schema-form, we use a `widget` property which is either a string (the id of the widget), either a dictionary if we need widget settings (like for a date/time, tinymce, etc.). See
https://github.com/makinacorpus/angular2-schema-form#widgets

**Comment by tisto** [comment]
@ebrehault using the widget property is fine. I just would make sure the property is always included and not "None" as it is now.

**Comment by tisto** [comment]
Pull request: https://github.com/plone/plone.restapi/pull/205
