### ISSUE TITLE
Block field serialization/deserialization on site root

### ISSUE THREAD

**Issue by cekk** [plone/plone.restapi#1043]
Block serializers/deserializers are registered for IBlocks interface and they works smooth on content-types (because ct with blocks have that behavior interface).

The problem is for blocks created into site root because the site root doesn't implements that interface.

I see two quick-and-dirty solutions:
- register transforms adapters not for IBlocks but for a generic Interface (they will work for every context)
- register all the transformers twice (once for site root interface and once for IBlocks)

The first one is the easiest but i don't know if could lead to some problems.
The second one is more "safe" but if you register new transformers, you'll need to register it twice each time.

Do we have any other options?

**Comment by tisto** [comment]
I'd go with the second option. Once we have the dexterity site root we can get rid of the duplicate registration.

**Comment by mauritsvanrees** [comment]
PR was merged. Closing.
