### ISSUE TITLE
Why are we using escape in @navigation endpoint?

### ISSUE THREAD

**Issue by cekk** [plone/plone.restapi#1061]
https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/navigation/get.py#L202

This generates "strange" outputs from restapi with some characters, for example '

It converts that character into "&#x27;" and the frontend doesn't handle it very well because other endpoints does not escape strings.

**Comment by cekk** [comment]
@sneridagh obviously that question is for you ;)

**Comment by sneridagh** [comment]
@cekk 😅well, I refactored the current sections viewlet into the endpoint, and I thought that should be some good reason (like umlauts or special characters handling that might have led to it) about it... If we find it's a bug, let's remove it altogether!

**Comment by sneridagh** [comment]
oh, I see now why... the current viewlet generates HTML... thus the conversion...

I will create a PR.
