### ISSUE TITLE
IBlockFieldSerializationTransformer and IBlockFieldDeserializationTransformer broken for DX CType with Layout enabled

### ISSUE THREAD

**Issue by avoinea** [plone/plone.restapi#1070]
Right now all **Field Serialization Transformers** and **Field Deserialization Transformers** are registered on `IBlocks` behavior interface. 

But in order for TTW DX Content-types Layout to work we had to disable this behavior and manually add `blocks` and `blocks_layout` fields.

Thus, we need a new marker interface behavior for custom blocks.

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/plone.restapi/pull/1477
