### ISSUE TITLE
Release restapi 6.15.1 and plone.rest 1.6.2

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#1075]
@plone/restapi-team Can we have new releases for [Plone 5.2.4](https://github.com/plone/Products.CMFPlone/issues/3250) please?

**Comment by sneridagh** [comment]
@mauritsvanrees We plan to release p.restapi 7.0.0 final this weekend (if possible) so please wait for it if you can!

**Comment by tisto** [comment]
@mauritsvanrees I will do a release today.

@sneridagh let me know when I can cut an 8.0.0 final. It would be indeed good to include this final release in 5.2.4 IMHO.

**Comment by tisto** [comment]
@mauritsvanrees here you go:

https://pypi.org/project/plone.restapi/6.15.1/#id1

https://pypi.org/project/plone.rest/1.6.2/#id1

It would be cool if you could wait for p.restapi 7.0.0 (today or tomorrow) and maybe consider the cffi/cryptography pin.

**Comment by tisto** [comment]
@mauritsvanrees I just released p.restapi 7.0.0:

https://pypi.org/project/plone.restapi/7.0.0/

This is the only version that we plan to maintain from now on. We had a long alpha period to try the resolveuid feature for Volto. This has no side-effects for non-Volto use cases and I tried my best to keep 6.x and 7.x similar. I see no risks in moving to the 7.0.0 release for both Plone 5.2 and 6.0. We cut a major release even though technically this is not a breaking change but "just" a feature release. Semantic UI permits that when a new feature is considered very important. :)

cc @sneridagh @esteele

**Comment by mauritsvanrees** [comment]
I have a slight hesitation adding 7.0.0 this late, but only slight. It has been long in the works and likely the alpha and beta releases have meanwhile got a lot of field testing already. And due to one or two Jenkins test failures on the 6.x.x branch, coredev has been tested against the master for a long time. So 7.0.0 might be better than another 6.15. :-) Thanks for both releases!

I added the version pin as part of https://github.com/plone/buildout.coredev/pull/713

Do you have a few lines as suggestion for including in the [release notes](https://dist.plone.org/release/5.2.4-pending/RELEASE-NOTES.txt)? I guess I can throw the new features together, but maybe a bit more summarised.

**Comment by tisto** [comment]
@mauritsvanrees I leave this decision up to you. Though, as said, I don't see much risk in going to 7 right away. If things go wrong, you can always blame me. ;)

Release notes for REST API:

- Add ResolveUID functionality for Volto blocks and allows Volto to preserve internal links when content is moved.
- Add root element to the @breadcrumbs endpoint [sneridagh] (#1064)
- Mark restapi 7 with a zcml feature flag: plonerestapi-7 [sneridagh] (#1068)
- Add new @contextnavigation endpoint. [tiberiuichim] (#1042)
- Refactor navigation endpoint, add new nav_title attribute [sneridagh] (#1047)
- Add "smart fields" concept: if block has a searchableText field, this will be indexed in Plone [cekk, tiberiuichim] (#952)

So, as said, only non-breaking new features and changes in Volto-related functionality.
