### ISSUE TITLE
Upgrade to Plone 5.2.4 blocked (because of plone.dexterity 2.10.0)

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#1096]
plone.dexterity 2.10.0 introduced a dynamic schema change that breaks our documentation test. See
https://github.com/plone/plone.dexterity/pull/137 for details. A workaround is to pin plone.dexterity to 2.9.8 but that isn't a long-term solution.

**Comment by avoinea** [comment]
@tisto Can you please point me to the failing running commands as running tests on my python3.8 sandbox doesn't seem to fail. 
I can see a hardcoded python 3.7 condition within github actions (it would help if we can switch to python 3.8)

**Comment by sneridagh** [comment]
@avoinea I recall yesterday building it on a 3.8 and see the dynamic behaviour names too... Maybe you didn't build again and you were using an old build?
