### ISSUE TITLE
Evaluate JSON Schema

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#11]
- ietf draft
- PYTHON: pythonjsonschema (laurence has a branch to work better with colander, default field)
- JAVASCRIPT: jsonschema

**Comment by tisto** [comment]
There are quite a few JS form libraries (Angular, React, etc.) out there that work with JSON schema, e.g.:

https://github.com/mozilla-services/react-jsonschema-form
http://schemaform.io/

The basic idea would be that the client application asks for "application/schema+json" via accept header and gets the JSON schema back. Endpoints could be any content object in Plone. This can be used by the client applications to render the edit form.

An alternative would be to have a specific endpoint to ask for the schema. Though, I think the first solution is more elegant.

**Comment by lukasgraf** [comment]
I agree that the first solution has a certain elegancy to it, but how about the content-creation use case? If a client application wants to add some new content of type `Foo`, it would need an endpoint to ask for the schema. And even if another object of that type already exists (which it might not), the client application would need to locate and ask a completely unrelated object for its type's schema, which is a pretty awkward way to go about things.

**Comment by tisto** [comment]
@lukasgraf good point. Then I guess we need to decide if we want the first solution in addition to a "factory" endpoint.

**Comment by tisto** [comment]
@cedricmessiant awesome! Would you mind starting with roughly outlining the endpoint design you have in mind? Do you plan to have a single endpoint for all portal type schemas (e.g. exposing the portal_types tool via REST)?

**Comment by lukasgraf** [comment]
@tisto I believe we might possibly need both. Both vocabulary factories and default value factories / default value adapters can be dynamic and context dependent.

I also did some work recently that relates to this - automatically generating Sphinx docs that describe the schemata used by our custom content types (so I can hand that to the customer that's going to use the API). It's currently a bit hackish and in a "works for our types" sort of state, but I'll contribute back what I can once I cleaned that up. @cedricmessiant I'll drop you a line the next couple days as soon as I pushed that code.

**Comment by lukasgraf** [comment]
What could get tricky here is Plone's (resp. DX and AT's) lack of clear separation between the data model, validation and **forms**. So much of validation and default value generation is tied into form logic.

E.g., the default value that is being chosen and proposed when a user adds a DX content type TTW is essentially determined in [`z3c.form.widget.Widget.update()`](https://github.com/zopefoundation/z3c.form/blob/8965b4042475053f6cf05601147fec569ab660e8/src/z3c/form/widget.py#L80-L141).

If that logic ends up looking for a default value adapter, that will be an adapter that adapts [context, request, form, field and widget](https://github.com/zopefoundation/z3c.form/blob/8965b4042475053f6cf05601147fec569ab660e8/src/z3c/form/widget.py#L124-L126) to `IValue`, and could therefore potentially depend on all of those things. 

---

Another thing that we might have to deal with at some point are the `plone.autoform` directives: Fields can be [omitted, reordered, grouped / moved into fieldsets, and have individual read / write permissions](https://github.com/plone/plone.autoform/blob/4b922dbc3ffd911b841b5dd5a313c4ec27935a1f/plone/autoform/directives.py#L2-L7). I'm not sure how much of this will be relevant to us, but here's some pointers as to how it works:

Those form hints are stored on the schema interfaces as tagged values. TGV from an individual schema interface can be retrieved with `iface.queryTaggedValue(KEY)`. But the fun bit is getting [merged tagged values](https://github.com/plone/plone.supermodel/blob/20812f8162ac549bad6898047c53f8dc8e3d1780/plone/supermodel/utils.py#L241-L250) that consider interface inheritance and [IRO](https://github.com/plone/plone.autoform/blob/4b922dbc3ffd911b841b5dd5a313c4ec27935a1f/plone/autoform/utils.py#L37-L59). Both `plone.autoform` and `plone.supermodel` contain several helper functions that should be useful here.

**Comment by cedricmessiant** [comment]
@tisto : My intuition is to use a single endpoint. Exposing the `portal_types` tool may be useful e.g. to be able to retrieve the list of portal types via the restapi.

But first, I will focus on the adapters to map `zope.schema` fields with jsonschema. I probably wont use the REST api in my application.

**Comment by cedricmessiant** [comment]
It's done ! (See : https://github.com/plone/plone.restapi/commit/dea48da905c8682d39e661a8031cd56f1c7b9afe )

**Comment by tisto** [comment]
Done: https://github.com/plone/plone.restapi/pull/92
