### ISSUE TITLE
Navigation endpoint should sort by object position in parent

### ISSUE THREAD

**Issue by thomasmassmann** [plone/plone.restapi#1107]
The latest implementation of the `navigation` endpoint uses the new navigation strategy as Plone does for the main navigation, but it does not sort the query. Moving items within a folder will affect the rendered Plone Backend, but not the frontend connected through the rest api.

The base query should be:

```diff
        query = {
            "path": {
                "query": self.navtree_path,
                "depth": self.depth,
            },
            "portal_type": {"query": self.settings["displayed_types"]},
            "Language": self.current_language,
            "is_default_page": False,
+           "sort_on": "getObjPositionInParent",
        }
```

Any thoughts? @tisto @sneridagh

**Comment by sneridagh** [comment]
@thomasmassmann yes you are correct. Would you mind to create a PR for it? Thanks!
