### ISSUE TITLE
Can't enable Volto Layout editing in content-types created using an interface based schema

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#1112]
More information to come, error could be related to this: https://github.com/plone/plone.restapi/blob/d78a8411d1166ee785ee71292a540f39fc2cf44c/src/plone/restapi/types/utils.py#L338

If we create a content-type based in a supermodel XML schema layout editing can be assigned correctly but if the content-type is based in an interface schema this can't be done.

We will investigate further.

**Comment by davisagli** [comment]
These days, use the IBlocksLayout behavior for this
