### ISSUE TITLE
PATCH not allowed

### ISSUE THREAD

**Issue by ebrehault** [plone/plone.restapi#114]
With the current master of plone_client + restapi branch , we get an error when trying to update a content:
```
Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response
```

At the contrary, it works with Postman, so I guess something is wrong in my headers.
I tried to debug it with curl, but no success.

@buchi @lukasgraf any hints?

Here is my OPTIONS request as I can see it in Chrome debugger:
```
Request URL:http://localhost:8080/Plone/front-page
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:127.0.0.1:8080

Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Access-Control-Request-Headers:accept, authorization, content-type
Access-Control-Request-Method:PATCH
Cache-Control:no-cache
Connection:keep-alive
Host:localhost:8080
Origin:http://evil.com/
Pragma:no-cache
Referer:http://localhost:3000/front-page/@@edit
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/49.0.2623.108 Chrome/49.0.2623.108 Safari/537.36
```

**Comment by buchi** [comment]
@ebrehault I'm not sure if Postman is doing any CORS checks at all.

With curl your preflight request should look like this:
```
curl -i \
-X OPTIONS \
-H "Accept: */*" \
-H "Access-Control-Request-Method:PATCH" \
-H "Access-Control-Request-Headers:accept, authorization, content-type" \
-H "Origin: http://evil.com" \
http://localhost:8080/Plone/front-page
```

Doing this request with curl returns the following for me:
```
HTTP/1.1 200 OK
Server: Zope/(2.13.23, python 2.7.11, darwin) ZServer/1.1
Date: Thu, 26 May 2016 16:57:30 GMT
Content-Length: 0
Access-Control-Allow-Headers: Accept, Content-Type, Authorization
Vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://evil.com
Access-Control-Allow-Methods: PATCH
```

Can you check if you get the same results when doing the OPTIONS request with curl? And do you have the latest plone.rest (version 1.0a6 or master) installed?

**Comment by ebrehault** [comment]
@buchi I have found my problem, my ZCML declaration for CORS was just a stupid copy/past from the plone.rest README, so the `allow_origin` was "http://example.net".
I have replaced it with "*", and it works now.

Thank you for your help.

Note: maybe we should change the README to put "*" (or maybe explain the `allow_origin` value must be changed), what do you think?

**Comment by buchi** [comment]
@ebrehault I think the best would be to have some documentation about CORS in plone.restapi. I will add a section there.

However I do not recommend to use `allow_origin="*"` in production for plone.restapi because of security implications and thus I would not put that in the example in the README. For development it's fine to use it.

**Comment by ebrehault** [comment]
> However I do not recommend to use allow_origin="*" in production for plone.restapi because of security implications and thus I would not put that in the example in the README
Yes I fully agree.
Do you think `allow_origin="http://localhost:*"` is possible ? Because that's basically what we need to make sure any frontend dev who wants to use restapi can works locally with his/her favorite Gulp/webpack/etc. local dev server .

**Comment by buchi** [comment]
Nope, that's not possible. According to the CORS specs the origin has to be a case-sensitive match for any of the values in the list of allowed origins. Thus using a wildcard for the port will not work.

**Comment by ebrehault** [comment]
Ok, nervermind, documentation will be enough then.
