### ISSUE TITLE
Remove cfgs from unsupported Plone versions of Makefile

### ISSUE THREAD

**Issue by wesleybl** [plone/plone.restapi#1144]
`make update` is used to update the versions of this package. The Makefile file still tries to download cfgs from unsupported versions. It is necessary to remove these files from the Makefile:

https://github.com/plone/plone.restapi/blob/80c0b085381dceb177b48fed34897ecd69d7efa4/Makefile#L27-L28

**Comment by ericof** [comment]
@wesleybl Cleaned in #1171
