### ISSUE TITLE
Missing @components in v8.2.0

### ISSUE THREAD

**Issue by cekk** [plone/plone.restapi#1148]
Using restapi 8.2.0 i don't have @components data anymore when i try to get some content infos.

The problem seems to be [here](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/dxcontent.py#L35)

That import raises this:

`*** ModuleNotFoundError: No module named 'plone.app.robotframework'`

That probably is a subclass of ImportError.

Why are we trying to import a testing fixture and not testing plone/python version?

**Comment by tisto** [comment]
@cekk that does not look like a proper way to test for plone.app.iterate to be present. I can imagine why p.a.robotframework fails then. Maybe @sneridagh can shed some light into this.

**Comment by tisto** [comment]
@cekk fixed with https://github.com/plone/plone.restapi/pull/1149

**Comment by tisto** [comment]
@cekk can you try again please with plone.restapi 8.3.0?

**Comment by cekk** [comment]
@tisto it works, Thanks!
