### ISSUE TITLE
Document version pins needed for Plone 4.3 (7.x.x)

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#1150]
Can we document somewhere the required version pins for Plone 4.3?

We already know that  plone.restapi 7.x is the last version that supports Plone 4.3, but what about all other packages?

Due to the EOL of python 2, many packages have been upgraded to python3-only versions, and running buildout in a Plone 4.3 with plone.restapi 7.x is a bit risky nowadays. 

If we could document this in the documentation and even in the README, the install process could be smoother.

**Comment by erral** [comment]
I have had to add the following ones to a Plone 4.3.20 buildout:

```
plone.restapi = 7.3.7
PyJWT = 1.7.1

six = 1.11.0
attrs = 21.2.0
plone.rest = 1.6.2
plone.schema = 1.3.0
# Last pyrsistent version that is python 2 compatible:
pyrsistent = 0.15.7

# Required by:
# jsonschema==3.2.0
functools32 = 3.2.3.post2

# Required by:
# plone.schema==1.3.0
jsonschema = 3.2.0

# Required by:
# importlib-metadata==1.3.0
pathlib2 = 2.3.5

# Required by:
# pathlib2==2.3.5
scandir = 1.10.0

# plone.app.contenttypes > 1.0
plone.app.contenttypes = 1.1.9
```

**Comment by tisto** [comment]
I guess this would be a combination of:

https://github.com/plone/plone.restapi/blob/7.x.x/plone-4.3.x.cfg#L7
https://github.com/plone/plone.restapi/blob/7.x.x/versions.cfg

This might help with the last Python 2 compatible versions:

https://github.com/kitconcept/buildout/blob/master/versions.cfg#L45

I am fine with adding this to the docs.
