### ISSUE TITLE
In Plone 4.3.x the Plone Site Root serializer renders only content in the actual language

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#116]
In multilingual sites using Plone 4.3.x and LinguaPlone, but presumably also when using p.a.multilingual 1.x in Plone 4.3.x, the site root serializer returns only one of the existing language folders because of the LinguaPlone catalog patch.

``` bash
(httpie) erral@lindari:~$ http GET www.eibar.eus Accept:application/json
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 255
Content-Type: application/json
Date: Mon, 30 May 2016 10:05:49 GMT
Server: nginx/1.9.15
Set-Cookie: I18N_LANGUAGE="eu"; Path=/
X-Frame-Options: SAMEORIGIN

{
    "@id": "http://www.eibar.eus/", 
    "@type": "Plone Site", 
    "items": [
        {
            "@id": "http://www.eibar.eus/eu", 
            "@type": "Folder", 
            "description": "", 
            "title": "Eibarko Udala"
        }
    ], 
    "items_total": 1, 
    "parent": {}
}
```

In this example we only get the `www.eibar.eus/eu` site, but there is also a `www.eibar.eus/es` site, and it is not excluded from navigation:

``` shell
(httpie) erral@lindari:~$ http GET www.eibar.eus/es Accept:application/json
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 30 May 2016 10:06:14 GMT
Server: nginx/1.9.15
Set-Cookie: I18N_LANGUAGE="es"; Path=/
Transfer-Encoding: chunked
X-Frame-Options: SAMEORIGIN

{
    "@id": "http://www.eibar.eus/es", 
    "@type": "Folder", 
    "UID": "17e3f116e075217c6d5396ef28d492a9", 
    "allowDiscussion": false, 
    "constrainTypesMode": 1, 
    "contributors": [], 
    "creation_date": "2010-10-21T06:21:37+00:00", 
    "creators": [
        "admin"
    ], 
    "description": {
        "content-type": "text/plain", 
        "data": ""
    }, 
...
}
```

In LinguaPlone environments this can be solved adding `Language='all'` keyword parameter to the catalog query, but can create some issues when used with p.a.multilingual 2.x such as in https://github.com/plone/plone.app.layout/issues/91

**Comment by djowett** [comment]
@erral Should the URLs should be different in this sentence?
> In this example we only get the www.eibar.eus/es site, but there is also a www.eibar.eus/es site

**Comment by erral** [comment]
Indeed, it's /eu, fixed.

**Comment by tisto** [comment]
@erral is this issue still present?

**Comment by djowett** [comment]
@tisto FYI  I got sponsored to work on a fix in https://github.com/plone/plone.app.layout/issues/91, and will do this coming week.  I'm not sure whether that will help in this issue, but @erral might have an idea.

**Comment by erral** [comment]
Yes, it is still present. We have it in two Plone 4.3.x sites with AT and LinguaPlone:

http://www.eibar.eus and http://egoibarra.eus 

But more than a plone.restapi issue is a LinguaPlone issue I think, because of the behavior of the catalog patch.

**Comment by tisto** [comment]
@erral @djowett thanks for the info. I will leave this issue open then and wait for fixes. :)

**Comment by djowett** [comment]
@erral is this fixed by my recent efforts?

**Comment by tisto** [comment]
@erral any updates here?

**Comment by erral** [comment]
AFAIK it is a LinguaPlone "feature" so nothing to do about it here. 

I am closing it.
