### ISSUE TITLE
Return not batched vocabularies given a query param b_size=-1

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#1264]

**Comment by ale-rt** [comment]
Good idea!
What about changing the batch parameter name to `b_size` and pass the value `-1`?
I am suggesting because historically that was the name used in classicland.
I do not know if that makes sense in voltoland.
If it does not, please disregard my comment and forgive me for the noise!
Ciao :)

**Comment by sneridagh** [comment]
Will do!

**Comment by sneridagh** [comment]
@ale-rt done! See PR! ^^

**Comment by ale-rt** [comment]
You are amazing :)
I wonder if this can be integrated in the `HypermediaBatch`, but this is another story :)
