### ISSUE TITLE
Create content (POST) should return id

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.restapi#128]
I think that on a POST its possible that the id is not sended or colisionates, may we return the new_id ?

@tisto

**Comment by tisto** [comment]
This is already somehow handled by HTTP. When we create a new resource the header of the response contains the location header with the full URL (which somehow included the id). I guess we can add an "id" field in the reponse. May I ask about your use case for this (just wondering)?

**Comment by lukasgraf** [comment]
The [documentation for the 201 Created response](http://plonerestapi.readthedocs.io/en/latest/crud.html#successful-response-201-created) to a `POST` is at odds with our current implementation anyway ([implementation returns `None` / `null`](https://github.com/plone/plone.restapi/blob/68c52cdfb2d3145f6a8aa0b3ccde410435dfe773/src/plone/restapi/services/content/add.py#L86)).

Should we change this to return the full resource representation, as currently stated in the docs? If so, how? Deserialize the newly create object again? What about `PATCH`?

We then still would need to add `id` to the serialization output, but I feel that would be acceptable, particularly once we separate schema fields and other non-field metadata like `UID` at the top-level (using a `fields` property).

@buchi what are your thoughts on this?

**Comment by tisto** [comment]
The two options we have for the implementation of POST/PATCH is that we can include or omit the resource representation (location header should always be present). We should just be consistent, in docs/implementation and regarding POST/PATCH. I don't have a strong opinion on that. Whatever works best for our use case would be the way to go I guess.

It would be interesting to hear what people prefer that actually implemented a form on top of GET/POST/PATCH.

**Comment by bloodbare** [comment]
My issue its more about the id. This value can be changed on POST for id conflict or id creation.

we already implemented in plone.server returning a 201, with LOCATION header and with a json response with new_id: XXXXX

REST CRUD implementation for DX on plone.server:
https://github.com/plone/plone.server/blob/master/src/plone.server/plone/server/api/dexterity.py

**Comment by mstaniszczak** [comment]
@tisto any new about this bug? We also need uid, for example of uploaded files, but for now API return always null.

**Comment by tisto** [comment]
@bloodbare 

The id attribute is not included in the response:

https://github.com/plone/plone.restapi/pull/143

And a POST request on a folder returns the serialized object (with the id attribute):

https://github.com/plone/plone.restapi/pull/144

Though, plone.restapi does not handle id collisions by itself:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/tests/test_content_post.py#L97

I guess we could discuss if this is something that should be handled by the client or by the server.

@mstaniszczak please create separate issues with a detailed description of your use case and the behavior that you would expect.

**Comment by tisto** [comment]
Fixed: https://github.com/plone/plone.restapi/pull/143 https://github.com/plone/plone.restapi/pull/144
