### ISSUE TITLE
Improve support and meaning for `default` and `missing_value` in serializers/deserializers

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#1282]
While trying to improve the select widget story in Volto, I found out one issue. Since Volto only sends "changed" field data in forms, `missing_value` are not being set correctly (since the part of the code that sets it, assumes that the field is present in the sent data (as null)), and validation fails (especially for array-ish fields). This provokes to "force" you to use `default` in them, which  is wrong. It's wrong, since `default` serves for another purpose.

Also, the combined use of `default` and `missing_value` is also kind of confusing, or I am missing something? Might be opening a Pandora's box here but... won't be more pragmatic to force internally a "missing_value" given the type of the field being used? I'm sure there's a reason why...

More background:

https://github.com/collective/example.contenttype/blob/volto/src/example/contenttype/example.py#L203

```
    list_field_checkbox = schema.List(
        title=u'List field with checkboxes',
        description=u"zope.schema.List",
        value_type=schema.Choice(
            values=[u'Beginner', u'Advanced', u'Professional'],
            ),
        required=False,
        missing_value=[],
        )
```

A list field declared like this, does not work on Volto now. On save, if the field value is untouched, it breaks.

/cc @tisto @ericof @tiberiuichim

**Comment by tiberiuichim** [comment]
As long as we're using z3c.form we have to abide to its API. I think your solution, to adopt the incoming value to the API of z3c.form is the proper one, given what we have.
