### ISSUE TITLE
Services are called without being mentioned in the request.

### ISSUE THREAD

**Issue by me-kell** [plone/plone.restapi#1328]
The following request calls several services (even without `--user`). Is it a feature or a bug?

```bash
curl \
    -s \
    -X GET http://192.168.45.133:8080/Plone \
    -H "Accept: application/json" \
    --user admin:secret
```

It calls at least the services `content`, `actions`, `breadcrumbs`, `navigation`, and `contextnavigation`.

And whatever Service configured with the following:

```xml
  <plone:service
    method="GET"
    for="zope.interface.Interface"
    factory=".get.MyServiceClassGet"
    name="@my_service_class"
    permission="zope2.View"
  />
```

**Comment by tiberiuichim** [comment]
It's a feature. It's due to the "expandable elements" support. If you want, you can start tracing code, starting here: https://github.com/plone/plone.restapi/blob/53bcce58e21edb2574a31579c82c386f46c9aff5/src/plone/restapi/serializer/dxcontent.py#L87

**Comment by me-kell** [comment]
Oh. I understand. The classes decorated with @implementer(IExpandableElement) are `__call__`ed.
Thank you.

**Comment by me-kell** [comment]
As far as I can see the `plone.restapi` documents `Expansion` (and most of its concepts) only from the perspective of a restapi's user. What I miss is a restapi developer's perspective.

I found it very usefull to study `plone.bobtemplate`'s [restapi_service](https://github.com/plone/bobtemplates.plone/blob/ca443a4c07bff82cfe42fb5864bfdc248aa5fb15/bobtemplates/plone/restapi_service/api/services/+service_class_name_normalized+/get.py.bob). But there is obviously not the best place to explain `Expansion`.

@fredvd: Maybe a goot place for documenting it could be `IExpandableElement`'s [docstring](https://github.com/plone/plone.restapi/blob/e12e1be6ba9e5de18ea4b089ece2c0e01a7f6f91/src/plone/restapi/interfaces.py#L123)
