### ISSUE TITLE
Set workflow timestamps in tests to a specific date/time.

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#133]
This is also annoying because every commit or pull request will update that file:

https://github.com/plone/plone.restapi/pull/131/files#diff-aacab0b0e85d224bdb693ec2f6cc0036L14

Any takers?

**Comment by lukasgraf** [comment]
@tisto would you consider [`freezegun`](https://github.com/spulec/freezegun) an acceptable test dependency?

I feel that would solve the underlying issue of highly variable data better than directly messing with the object creation time and workflow history.

**Comment by tisto** [comment]
@lukasgraf thanks for looking into this! I don't have any experience with freezegun but I don't see any reason why we can't add it as a testing dep.

**Comment by lukasgraf** [comment]
@tisto alright, I'll give it a shot! 👍
