### ISSUE TITLE
Change title in `index.rst`

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1343]
The current title of the documentation for plone.restapi is the following.

```
plone.restapi: A RESTful hypermedia API for Plone.
==================================================
```

When these docs are imported into the main documentation, it results in a rather long title in the navigation. See screenshot.

![Screen Shot 2022-03-20 at 5 36 39 PM](https://user-images.githubusercontent.com/102112/159193393-0a0957b0-0852-4f63-bacd-96aa38d858fc.png)

I propose to shorten the title to its name, and place the subtitle as a paragraph under the title. Unfortunately Sphinx does not support subtitles, only subheadings.

```
plone.restapi
=============

A RESTful hypermedia API for Plone.
```

![Screen Shot 2022-03-20 at 5 47 03 PM](https://user-images.githubusercontent.com/102112/159193404-2ffa3b6e-3134-4e84-a8e7-66296486bd4c.png)

Please let me know. Thank you!

**Comment by tisto** [comment]
@stevepiercy tbh I thought about changing that claim anyways. We do not provide a hypermedia API. Therefore I'd change the claim to "A RESTful API for Plone" and I am good with using the shortname in the sidebar. Maybe we should use "REST API" in the sidebar instead of "plone.restapi" then...

**Comment by stevepiercy** [comment]
Unfortunately, the title of the page and the navigation item always match. AFAIK, it is not possible to make them different.

Also consider SEO. "REST API" is generic, whereas "plone.restapi" is very specific.

I'll go with whatever title/link label you decide.

**Comment by jensens** [comment]
I think plone.restapi is often used in the text itself (and could be added to the subline), so REST API in the title is enough and would match better with the other headings.

Something different; I would order it differently, by importance for new site creators: 

1. Frontend, (usually the thing one starts with)
2. Rest api, (needed by a frontend dev soon).
3. Backend, (more advanced already)
4. Classic ui (only for those with old sites or special use cases)
5. Contributing to docs

**Comment by stevepiercy** [comment]
One more consideration is whether you want to continue to publish standalone docs on RTD. That also impacts SEO. Here's a preview of that, thanks to Netlify:

https://623868017133450009fe3c75--plone-restapi.netlify.app/

I don't have an opinion as I am not a core contributor to this package. It's up to y'all to make a final decision, and let me know what I should implement in a PR.

> Something different; I would order it differently, by importance for new site creators:

Let's focus on just plone.restapi's title in this issue in this repo. We can discuss renaming sections or adding missing content in the main docs' repo or the repo it imports.

**Comment by tisto** [comment]
I fully agree with @jensens here. Let's go with the title "REST API" and use plone.restapi in the body text.

I also like the idea of reflecting the architectural layers in the navigation/hierachy. That makes lots of sense to me.

**Comment by stevepiercy** [comment]
I created a new issue for a discussion in https://github.com/plone/documentation/issues/1207

I pushed a commit 783f8aad63172632ecded6f8a8f096e2fe0b3bff to existing PR https://github.com/plone/plone.restapi/pull/1337

**Comment by stevepiercy** [comment]
Closed by https://github.com/plone/plone.restapi/pull/1337

Oh, pretty!

https://6.dev-docs.plone.org/plone.restapi/docs/source/index.html
