### ISSUE TITLE
Convert plone.restapi docs from reStructuredText to MyST?

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1347]
Do the people who actually write documentation for `plone.restapi` prefer to write documentation in reStructuredText or MyST?

I don't have an opinion, except that continuing to write in reST means that I would not have to convert files, and that git history would be retained. AFAIK, when converting files, git history cannot track between a change in filename from `*.rst` to `*.md`. It's possible writing in MyST is easier as it is Markdown with adapted reST syntax tossed in, and so you might get more contributors.

_Originally posted by @stevepiercy in https://github.com/plone/plone.restapi/issues/1326#issuecomment-1051944086_

**Comment by jensens** [comment]
I am not a doc-writer here, but I would like to suggest to use the same markup in all Plone documentation if possible!

**Comment by tiberiuichim** [comment]
I think the issue is more complex with plone.restapi, as there's a bunch of inlined content. Compare the rendered output https://plonerestapi.readthedocs.io/en/latest/authentication.html with the source rst where there's a bunch of macros to inline the content. 

@tisto will know more about this.

**Comment by stevepiercy** [comment]
@tiberiuichim can you be specific, using git blame?

https://github.com/plone/plone.restapi/blame/master/docs/source/authentication.rst

A couple of concerns, specifically automatic conversion of reST to MyST and handling the http-example Sphinx extension, are covered here:

https://github.com/plone/plone.restapi/issues/1326#issuecomment-1052575672

**Comment by tiberiuichim** [comment]
https://github.com/plone/plone.restapi/blame/master/docs/source/authentication.rst#L74

**Comment by jensens** [comment]
It's been a while I wrote a Sphinx extension (10-12y), but IIRC they are not markup-specific. It produces a branch in the docutils tree. Extensions internally may utilize the ReST parser, but to the outside it does not matter. Given MyST understands custom Sphinx directives, this should work.

**Comment by stevepiercy** [comment]
> https://github.com/plone/plone.restapi/blame/master/docs/source/authentication.rst#L74

This is not a problem. I just did a test by running `rst-to-myst` to convert the files, and it rendered it exactly the same as reST with working tabs. It converts it to:

````
```{eval-rst}
..  http:example:: curl httpie python-requests
    :request: ../../src/plone/restapi/tests/http-examples/jwt_login_renew.req
```
````

I could do the whole project, and push to a branch for preview on Netlify.

**Comment by stevepiercy** [comment]
Nope.

```
/Users/stevepiercy/projects/Plone/documentation/submodules/plone.restapi/docs/source/authentication.md:77: WARNING: Pygments lexer name 'http:example' is not known
```

That makes sense in MyST because triple backticks followed by text is a code-block and lexer.

You were close. The directive must be surrounded by `{}`:

````
```{http:example} curl httpie python-requests
---
request: ../../src/plone/restapi/tests/http-examples/jwt_login_renew.req
---
```
````

That works, but the source looks messy and would require manual tweaks. I would much prefer automatic conversion to manual tweaks.

**Comment by tisto** [comment]
@stevepiercy I have to admit I am completely clueless about how MyST works and what switching would mean. Is the HTTP request examples the only thing that we potentially would have to change?

**Comment by stevepiercy** [comment]
@tisto here's an excellent summary: https://myst-parser.readthedocs.io/en/latest/explain/index.html

MyST is just another markup syntax, like Markdown, CommonMark, and reStructuredText. MyST is a superset of CommonMark and reStructuredText combined. You can write everything in Markdown or extended CommonMark, and sprinkle the occasional reST for Intersphinx, cross-references, glossary terms, admonitions (seealso, danger, warning, tip, note), or whatever is easier or useful to do in reST. This ability to combine the ease and simplicity of Markdown with the features of reST is MyST's super power. 🦸 

There is also the MyST parser, which converts MyST syntax to something Sphinx can parse.

When we converted the Trainings from reST, we used `rst-to-myst` for the automatic conversion. It did a pretty good job, with only minor fixes needed that the conversion tool could not handle, specifically sidebars. `rst-to-myst` will convert all reST syntax to MyST syntax automatically, including `http:example` directive and custom markup from Sphinx extensions.

If you want to compare MyST and reST syntaxes, have a look at this: https://myst-parser.readthedocs.io/en/latest/examples/index.html

Switching to MyST means that you could write documentation in Markdown, CommonMark, or reStructuredText. It's all MyST! The choice is yours.

**Comment by jensens** [comment]
@tisto I really recommend using MyST and then Markdown in the backend docs consistently too. Thus we have both, frontend and backend, documented using the same syntax and we save switching our brains from MD to ReST and back when writing docs for Plone.

**Comment by tisto** [comment]
@stevepiercy sounds too good to be true. :)

Can we then run the migration in a PR so we can check the output together and see what would be needed to finish this?

**Comment by stevepiercy** [comment]
@tisto yup, will do, and it will be automatically previewed using Netlify. Thus you can two browser windows open side by side to compare renderings.

**Comment by stevepiercy** [comment]
I'm going to hold off on this item until the CI workflow "Tests" passes again.

Then we can merge these two PRs:

- https://github.com/plone/plone.restapi/pull/1346
- https://github.com/plone/plone.restapi/pull/1351
