### ISSUE TITLE
REST API: GET content with schema frame

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.restapi#136]
It would be possible to create a frame called schema that returns the schema on the API ?

@tisto

**Comment by tisto** [comment]
@bloodbare you mean embedded in the main response, right? Or would the response then return just the schema? We could do the latter with just content negotiation.

**Comment by bloodbare** [comment]
I mean, GET /obj1?frame=schema 

I get the object and a field called schema with the schema

**Comment by lukasgraf** [comment]
@bloodbare That should absolutely be possible I think, once we get the prerequisites in place for doing framing in general. However, before we attack framing, we need to get our `@context`s sorted I think, see my comment in #6.

**Comment by tisto** [comment]
I think we solved that with "schema" expansion.
