### ISSUE TITLE
Is `workingcopy` available for Plone 5 only, or 6 as well?

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1369]
From the note on the docs:

https://6.dev-docs.plone.org/plone.restapi/docs/source/workingcopy.html

![Screen Shot 2022-04-16 at 1 34 39 PM](https://user-images.githubusercontent.com/102112/163690554-7644e241-69d7-4da5-b594-e57eb9c0fd24.png)

**Comment by avoinea** [comment]
@stevepiercy **Plone 5+**. I think the note is there for **Plone 4** only users.

**Comment by stevepiercy** [comment]
Thank you! Fixed in b51991a5307328fd0236a06d5193131925ea92f0 in https://github.com/plone/plone.restapi/pull/1375
