### ISSUE TITLE
Missing code example on Translations - Expansion?

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1374]
At https://6.docs.plone.org/plone.restapi/docs/source/endpoints/translations.html#expansion it implies that there should be a code example by virtue of a colon at the end of the final sentence, but there is none.

Should there be a code sample?

**Comment by Akshat2Jain** [comment]
https://6.docs.plone.org/plone.restapi/docs/source/translations.html#expansion page not found
@stevepiercy

**Comment by stevepiercy** [comment]
Link updated. The page moved to https://6.docs.plone.org/plone.restapi/docs/source/endpoints/translations.html#expansion. This is still an open issue.

**Comment by Akshat2Jain** [comment]
```
{
  "@id": "http://localhost:55001/plone/content-item",
  "@type": "Document",
  "@components": [
    {
      "@id": "http://localhost:55001/plone/content-item/@actions"
    },
    {
      "@id": "http://localhost:55001/plone/content-item/@breadcrumbs"
    },
    {
      "@id": "http://localhost:55001/plone/content-item/@translations"  <---- The @translations endpoint URL is added here.
    },
    {
      "@id": "http://localhost:55001/plone/content-item/@workflow"
    }
    ...
  ],
  "UID": "1f699ffa110e45afb1ba502f75f7ec33",
  "title": "Sample Content Item",
  ...
}
```
is this code okay to show the `@translations`?
@stevepiercy

**Comment by stevepiercy** [comment]
@Akshat2Jain the best way to find out is to write a test, as described in [Contributing to plone.restapi](https://6.docs.plone.org/plone.restapi/docs/source/contributing/index.html). This will give you immediate feedback. Then when you submit a pull request, the docs will be built and tests will run in the CI that maintainers can review.

**Comment by Akshat2Jain** [comment]
Hey @stevepiercy, Shouldn't the breadcrumbs page also have an expansion section? 

https://6.docs.plone.org/plone.restapi/docs/source/endpoints/breadcrumbs.html

**Comment by stevepiercy** [comment]
I will say "no" for this issue, but it could be a separate issue and pull request.

However, I just realized that expansion might not actually belong in [Endpoints](https://6.docs.plone.org/plone.restapi/docs/source/endpoints/index.html), but instead might belong in [Usage](https://6.docs.plone.org/plone.restapi/docs/source/usage/index.html), because expansion is more of technique to return a collection endpoints but is not an endpoint itself. This should be discussed with the maintainers. I will create a separate issue for this discussion.

**Comment by Akshat2Jain** [comment]
Got It!
