### ISSUE TITLE
@aliases endpoint

### ISSUE THREAD

**Issue by avoinea** [plone/plone.restapi#1393]
In Plone Classic for each object we have an action called `URL Management` pointing to `/@@manage-aliases`. These aliases are automatically added when an object is renamed in order to automatically redirect old URL to the new one. In Plone Classic the Editor is able to see them, add new ones, or remove existing ones.

In order to be able to replicate this behavior in Volto, we need a RestAPI endpoint called `@aliases`.
It should be listed in components and expandable and it should follow the RestAPI CRUD approach.

Verb | URL | Action
-- | -- | --
GET | `/test-page/@aliases` | List all aliases
POST | `/test-page/@aliases` | Add one or more aliases
DELETE | `/test-page/@aliases` | Remove one or more aliases
~~PATCH~~ | `/test-page/@aliases/{:id}` | Edit alias (not sure if we need this)
~~DELETE~~ | `/test-page/@aliases/{:id}` | Remove alias (not sure if possible as the id is a path)

See also https://github.com/plone/volto/issues/1178

**Comment by jensens** [comment]
On POST I would allow to add a list of aliases. I think this is supported by the UI of classic in some way.

**Comment by avoinea** [comment]
@jensens Yes, also on delete it should allow a list of aliases. Already discussed this with @Petchesi-Iulian

**Comment by davisagli** [comment]
Added in 8.27.0
