### ISSUE TITLE
@rules endpoint

### ISSUE THREAD

**Issue by avoinea** [plone/plone.restapi#1397]
In Plone Classic for each object we have a menu called `Rules` pointing to `/@@manage-content-rules`. Here you can see and assign Content Rules contextually.

In order to be able to replicate this behavior in Volto, we need a RestAPI endpoint called `@rules`.
It should be listed in components and expandable and it should follow the RestAPI CRUD approach.

Verb | URL | Action
-- | -- | --
GET | `/test-page/@rules` | List rules assigned here
POST | `/test-page/@rules` | Assign rule to this context
DELETE | `/test-page/@rules/{:id}` | Unassign content rule to this context

See also https://github.com/plone/plone.restapi/issues/324

**Comment by ericof** [comment]
Implemented by #1496
