### ISSUE TITLE
Provide needed image meta data for responsive images in listings / preview images

### ISSUE THREAD

**Issue by MrTango** [plone/plone.restapi#1399]
As just discussed with @pnicolli @giuliaghisini and some other people here in bucharest, we need a way to provide needed meta data like image width, height, scale url and so on to render the images in listings on the frontend side.

This should be non-breaking and opt-in.

I have two ideas how this could be archived.

1. Adding a service endpoint which will provide the meta for all images of the listing and using it with expand when ever we need preview images in a listing.
2. Integrating the meta data directly into the serializer of the listing, when ever we ask for it via request parameter like previewimages=1 or image_metadata=1.

The second option would be the cleanest for the front-end to consume and should break nothing, as is would be opt-in via request parameter.

What do you think?

@tisto @sneridagh @avoinea @datakurre @thomasmassmann

**Comment by MrTango** [comment]
also related issues are: #939 and #2097 or PR: https://github.com/plone/volto/pull/2103

**Comment by datakurre** [comment]
@MrTango What are "preview images" in this context? I listened to the discussion, but seemingly missed that.

**Comment by datakurre** [comment]
Obviously, there are possible performance issues. I'd guess, listings are currently based on catalog (until "fullobjects" are requested). But images sizes are not indexed, and neither are image scales. So, resolving scales would require reading that directly from the objects.

On the other hand, we do have https://github.com/plone/plone.outputfilters/blob/master/plone/outputfilters/filters/resolveuid_and_caption.py, but result from that is probably cached on Plone Classic (I recall that was part of portal transform, using its volatile cache).

**Comment by cekk** [comment]
First implementation here: https://github.com/plone/Products.CMFPlone/pull/3521

**Comment by datakurre** [comment]
@cekk @jensens Very nice solution!

**Comment by mauritsvanrees** [comment]
This was implemented. Is anything left to do? There may be more places where the metadata can be used, but @davisagli probably fixed the most important ones today in https://github.com/plone/plone.restapi/pull/1498
Closing. Feel free to reopen or add a new issue.

**Comment by davisagli** [comment]
@mauritsvanrees #1498 took care of using the new approach when serializing an image field. We also need to add the `image_scales` catalog metadata to the summary serialization so that it is available in query results, and actually make use of it instead of the old scale URLs when rendering images in listings.
