### ISSUE TITLE
Question: Content Creation without history 

### ISSUE THREAD

**Issue by arky** [plone/plone.restapi#1418]
When you create a new content using Plone.Restapi (Custom content type), the system creates a history and stores on the disk (zoedb) of relstorage(postgre, my*sql).  

If you attempt a large scale content creation, this would quickly fill up the disk and the system would go down. 

It would be a good idea to introduce a flag content creation without creating a history to circumvent this issue. 

Any thoughts and suggestion would be highly appreciated.

**Comment by davisagli** [comment]
I'm not sure I understand what you want to happen. Storing a new content item in the database is an unavoidable part of creating it. If you mean the CMFEditions versions that show up in the item's history in the UI, those can be avoided by disabling versioning for the content type.
