### ISSUE TITLE
Outdated unstable black version 20.8b1 used in CI

### ISSUE THREAD

**Issue by jensens** [plone/plone.restapi#1426]
I recommend to update to a latest stable version, in beta series there were often changes in the formatting and the version does not reflect what is used in Plone Core elsewhere (where applied). 
Also its a PITA when working with the code base if some outdated version is required.

**Comment by tisto** [comment]
@mauritsvanrees @jensens do we have a place where we define the current version of black that we are using?

@jensens prio "high" for code analysis? :)

**Comment by tisto** [comment]
Fix: https://github.com/plone/plone.restapi/pull/1427

**Comment by jensens** [comment]
Well, high, because it really hurts while developing for Restapi in coredev. But it's merged, thanks!
