### ISSUE TITLE
Add relations endpoint

### ISSUE THREAD

**Issue by pbauer** [plone/plone.restapi#1432]
A relation endpoint should allow to get, add and delete relation tuples per context similar to the relation module in plone.api (https://6.docs.plone.org/plone.api/relation.html). 

It should also allow to get, add and delete relation tuples globally to a relations control panel (https://github.com/plone/volto/issues/3096).

**Comment by pbauer** [comment]
I think to support all use-cases that plone.api and the comntrolpanel offer we need 2 endpoints with different names. E.g. `@contentrelations` which operates on the context and `@relations` which works on the portal. I think using the same for both use-cases is not possible because a Dexterity site root object can have relations of its own. 

`@relations` could then allow arbitrary queries for source, target and relation to add, get and delete relations and also get the data for the controlpanel 

`@contentrelations` could be a convenience-api that can get, add and delete where the context is eiother the srouce or the target.

**Comment by pbauer** [comment]
We discussed it some more and would propose the names `@relations` for the endpoint that uses the context (by default as source) and `@manage-relations` for the endpoint on the portal that can do arbitrary calls and interact with all kinds of relations without using the context.

**Comment by pbauer** [comment]
We discussed it again some more and @sneridagh and me agreed that `@relations` and `@relations-catalog` might be a good choice.

**Comment by ksuess** [comment]
Proposal for implementation.

**No endpoint on context, but one single endpoint /@relations on portal root.
@relations deals with the source/target/relation parameters.**

@pbauer and me pondered the relations endpoint.  
@pbauer will implement it.

**Comment by ksuess** [comment]
I'll take over to implement the new universal service (No endpoint on context, but one single endpoint /@relations on portal root. @relations deals with the source/target/relation parameters. @relations without parameters responds with stats).
Any objections, @pbauer?
