### ISSUE TITLE
Add Matomo tracking code to https://plonerestapi.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1447]
Is there a reason to keep https://plonerestapi.readthedocs.io/en/latest/ now that we have https://6.dev-docs.plone.org/plone.restapi/docs/source/index.html?

If not, then I would propose to delete the RTD project and update the README to use the new authoritative source.

**Comment by tisto** [comment]
@stevepiercy I understand behind having one authoritative source. Though, plonerestapi.readthedocs.org is linked in a lot of places. Removing it would lead to lots of broken links. It is also indexed in Google and we would lose that. Therefore I would not recommend just removing it. I am not sure if it would be possible to create a proper redirect.

in addition, plone.restapi is kind of a "product" that is more than just a part of Plone (e.g. for the headless CMS story). In the past, we often had packages that had their own docs on RTD in addition to the Plone docs.

plone.restapi is also still an add-on product for older versions of Plone and this wouldn't be reflected if we would just add it to the Plone core docs.

**Comment by stevepiercy** [comment]
Thanks for the explanation. That makes sense.

That informs how we would want to implement tracking with Matomo. It sounds like it we should have two separate tracking codes: one for `plone.restapi` docs on RTD, and one for the main documentation where `plone.restapi` docs are imported. We already have the latter. @ericof and @fredvd are working on this. It could inform us of how people find `plone.restapi` docs on RTD.

As an aside, [RTD has good redirect configuration](https://docs.readthedocs.io/en/stable/user-defined-redirects.html).
