### ISSUE TITLE
New endpoint to expose the Site title and the current navigation root title

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#1462]
See https://github.com/plone/volto/issues/3531 and https://github.com/plone/volto/issues/3530

**Comment by cekk** [comment]
i'm working on a similar feature in our policy package: https://github.com/RedTurtle/redturtle.volto/compare/logo_miniatures

I made a "site-settings" endpoint that should return all basic site informations like title and logo (with scales).
It's still a work-in-progress but if can be useful for the community i can move it into plone.restapi

**Comment by erral** [comment]
I think that this kind of feature is definetely useful
