### ISSUE TITLE
Reorganize navigation items in docs

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1486]
The docs are rendered as a huge flat list, with not enough thought for organization. I propose to organize and sort them as follows.

- Put endpoint docs into new directory `endpoints/`.
- Put usage docs into new directory `usage/`. These include items that span the endpoints.
- Create a new `contributing` directory for how to contribute.

```
introduction  # has toctrees for content-negotiation and plone-content

usage/
    authentication
    batching
    content
    customization
    exploring
    i18n
    serialization
    sharing
    types-schema
    blocks

endpoints/
    actions
    addons
    breadcrumbs
    comments
    contextnavigation
    controlpanels
    copymove
    database
    email-notification
    email-send
    expansion
    groups
    history
    locking
    navigation
    portrait
    principals
    querystring
    querystringsearch
    registry
    roles
    searching
    system
    tiles
    translations
    tusupload
    types
    users
    vocabularies
    workflow
    workingcopy

upgrade-guide

contributing -> contributing/index
contributing/
    index
    conventions
```

Please let me know what y'all think. Thank you!

**Comment by jensens** [comment]
Lgtm

**Comment by davisagli** [comment]
Looks like a good improvement to me.

I am not sure if we should add contributor docs here, or if plone.restapi should be mentioned as a special case in the top-level contributor section (i.e. the one in plone/documentation that I still need to work on). I guess it makes sense to add a section here, and then mention it with a link from the top level contributor docs.

**Comment by stevepiercy** [comment]
> I am not sure if we should add contributor docs here, or if plone.restapi should be mentioned as a special case in the top-level contributor section (i.e. the one in plone/documentation that I still need to work on). I guess it makes sense to add a section here, and then mention it with a link from the top level contributor docs.

You got it. See https://github.com/plone/documentation/issues/1278

**Comment by stevepiercy** [comment]
There's a weird one that looks like it should be in `endpoints`, but is placed under Introduction.

https://plonerestapi.readthedocs.io/en/latest/plone-content.html

I think that it should be entitled "Plone Content Types" and moved into `endpoints`. I will do that in the PR, but if you have a different opinion, please speak up.

**Comment by stevepiercy** [comment]
I am also going to merge the `content-negotiation` page into the `introduction` page. Its content is minimal, and a separate page for introductory stuff is unusual. It also renders a strange collapsible navigation that is not necessary.
