### ISSUE TITLE
Error while installing plone.restapi

### ISSUE THREAD

**Issue by victorchrollo14** [plone/plone.restapi#1489]
after making a fork and cloning to local machine.
  * run make command 
  * add eggs = rest.api to buildout 
  * run bin/buildout 
  
 We get the following error:
    * # Error: The requirement ('importlib-metadata<4.3,>=1.1.0') is not allowed by your [versions] constraint (0.23)
      importlib-metadata = 2.0.0

**Comment by victorchrollo14** [comment]
I am self assigning this issue.

**Comment by wesleybl** [comment]
@victorchrollo14 To contribute to Plone you must first sign the Contributors Agreement.

See: https://plone.org/foundation/contributors-agreement

**Comment by wesleybl** [comment]
@victorchrollo14 what is the result of the command:

```
python3 --version
```

?

By default `make` installs Plone 5.2. If your Python is 3.10, you might be trying to install Plone 5.2 with Python 3.10. Plone 5.2 does not support Python 3.10. Python 3.8 only.

This line:

https://github.com/plone/plone.restapi/blob/dfb88d317460c824fa9a99abbcc9320e2e40bc2b/Makefile#L6

needs to be changed to:

```
version = 3.8
```

Or else this variable must be Python 3.10 for Plone 6 and Python 3.8 for Plone 5.2

**Comment by victorchrollo14** [comment]
When I ran the make command initially, I was using python 3.10.5. I asked some community about the same, they told me that plone only support 3.6, 3.7 and 3.8. So I set the local python versions to python 3.7.13 using pyenv. I got the same error after running it using python 3.7.13.
![Screenshot (36)](https://user-images.githubusercontent.com/89346667/189790729-d81160ae-c0fc-466c-994c-bbdc43c32cf9.png)

**Comment by victorchrollo14** [comment]
> @victorchrollo14 To contribute to Plone you must first sign the Contributors Agreement.
> 
> See: https://plone.org/foundation/contributors-agreement
Ok , thank you. I will go sign the contributors agreement.

**Comment by victorchrollo14** [comment]
> @victorchrollo14 what is the result of the command:
> 
> ```
> python3 --version
> ```
> 
> ?
> 
> By default `make` installs Plone 5.2. If your Python is 3.10, you might be trying to install Plone 5.2 with Python 3.10. Plone 5.2 does not support Python 3.10. Python 3.8 only.
> 
> This line:
> 
> https://github.com/plone/plone.restapi/blob/dfb88d317460c824fa9a99abbcc9320e2e40bc2b/Makefile#L6
> 
> needs to be changed to:
> 
> ```
> version = 3.8
> ```
> 
> Or else this variable must be Python 3.10 for Plone 6 and Python 3.8 for Plone 5.2

Does plone 6 support python 3.10?

**Comment by wesleybl** [comment]
> I got the same error after running it using python 3.7.13.

It was actually a slightly different error. But I saw that you are trying to use Plone 6 now. Recently Plone 6 removed support for Python 3.7. So I don't think it's worth it for you to continue there.

> Should I download the agreement pdf , take a printout and then sign it. Or should I just edit the pdf and share.

I think you should print, fill out, sign, scan and email.

> Does plone 6 support python 3.10?

Yes. Then you can use the command:

```
make build-plone-6.0
```

**Comment by victorchrollo14** [comment]
ok cool , Thank you.

**Comment by wesleybl** [comment]
> Does plone 6 support python 3.10?
Yes. Then you can use the command:

However, I think `plone.restapi` has not been tested with Python 3.10. So I think the best version for you to use in Plone 6 in `plone.restapi` would be Python 3.9.

**Comment by victorchrollo14** [comment]
I tried running it with 3.10. I'm getting the same error as before. I'll try using 3.9.

**Comment by wesleybl** [comment]
> However, I think plone.restapi has not been tested with Python 3.10. So I think the best version for you to use in Plone 6 in plone.restapi would be Python 3.9.

Oh sorry. In fact it is already being tested in Python 3.10:

https://jenkins.plone.org/job/pull-request-6.0-3.10/31

Then you can try.

**Comment by victorchrollo14** [comment]
Ok

**Comment by wesleybl** [comment]
> I tried running it with 3.10. I'm getting the same error as before.

I noticed that the `build-plone-6.0` target depends on [.installed.cfg](https://github.com/plone/plone.restapi/blob/dfb88d317460c824fa9a99abbcc9320e2e40bc2b/Makefile#L68). And `.installed.cfg` [runs the buildout without a parameter](https://github.com/plone/plone.restapi/blob/dfb88d317460c824fa9a99abbcc9320e2e40bc2b/Makefile#L42). The parameterless buildout installs [Plone 5.2](https://github.com/plone/plone.restapi/blob/c284b560d1a5cbb75a6bfb780c39fdfd139c4fb9/buildout.cfg#L2). So maybe the `build-plone-6.0` target should depend directly on [bin/buildout](https://github.com/plone/plone.restapi/blob/dfb88d317460c824fa9a99abbcc9320e2e40bc2b/Makefile#L44).

**Comment by victorchrollo14** [comment]
Inside buildout.cfg we have extends = plone-5.2.x.cfg
Might this have anything to do with the problem

**Comment by victorchrollo14** [comment]
@ale-rt told me to remove 
[versions:python36] from plone-5.2.x.cfg, On removing that line we don't get the importlib error.
    Getting distribution for 'importlib-metadata==2.0.0'.
    Got importlib-metadata 2.0.0.

Now it gives an error saying that:
   *   File "/home/victor/Projects/plone/plone.restapi/lib/python3.10/site-packages/zc/buildout/easy_install.py", line 1751, in 
      _move_to_eggs_dir_and_compile
       [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
       ValueError: not enough values to unpack (expected 1, got 0)

**Comment by ale-rt** [comment]
You are obviously using Python 3.10, which is not good for Plone 5.2.
Check the previous messages I posted about this topic in the forum.

**Comment by victorchrollo14** [comment]
Ok I'll look into that , thank you.
 @wesleybl told that plone 6 supports python 3.10.
So I tried installing plone 6, which gave me the same error.

**Comment by wesleybl** [comment]
@victorchrollo14 see my comment: https://github.com/plone/plone.restapi/issues/1489#issuecomment-1244859400

**Comment by victorchrollo14** [comment]
👍@wesleybl , I don't have much idea about makefiles , I'll learn it up quick and work on it.

**Comment by davisagli** [comment]
It's not clear whether this was user error or a bug. I'm going to close the issue. If it is still a problem, please open a new issue with more specific steps to reproduce the issue.
