### ISSUE TITLE
types endpoint failing with AttributeError: lookupSchema

### ISSUE THREAD

**Issue by lukasgraf** [plone/plone.restapi#150]
```
GET http://localhost:8080/Plone/@types/Document
```

```
2016-10-22 12:06:19 ERROR Zope.SiteErrorLog 1477152379.920.0579750084626 http://localhost:8080/Plone/@types/Document
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 20, in __call__
  Module plone.restapi.services, line 15, in render
  Module plone.restapi.services.types.get, line 50, in reply
  Module plone.restapi.types.utils, line 134, in get_jsonschema_for_portal_type
  Module plone.restapi.types.utils, line 108, in get_jsonschema_for_fti
  Module plone.restapi.types.utils, line 37, in get_ordered_fields
AttributeError: lookupSchema
```

(On both Plone 4.3.x and Plone 5.0.4)

**Comment by lukasgraf** [comment]
Was caused by not having `plone.app.contenttypes` installed, so I had `DynamicViewTypeInformation`s instead of `DexterityFTI`s.

Apparently the `@types` endpoint only supports DX FTIs so far.

**Comment by jaroel** [comment]
This is also an issue for the site root:
2017-04-28 15:55:37 ERROR Zope.SiteErrorLog 1493387737.640.088023899385 http://localhost:8080/Plone/@types/Plone%20Site
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 20, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.types.get, line 52, in reply
  Module plone.restapi.types.utils, line 169, in get_jsonschema_for_portal_type
  Module plone.restapi.types.utils, line 132, in get_jsonschema_for_fti
AttributeError: lookupSchema
