### ISSUE TITLE
Published content without effective date set does not show up in @navigation -> items

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#1521]
Plone 6.0.0b3, plone.restapi 8.30.0

Full report:

https://community.plone.org/t/plone-restapi-navigation-items-empty-for-migrated-content-items-visible-after-editing-them/15759/2

Published subobjects without effective date set are not available in `@navigation -> items`

**Comment by davisagli** [comment]
@zopyx What value of `effective` is indexed for the item that is not included? It should be indexed with DateTime(1970, 0) if no effective date is set, but maybe something is going wrong there: https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/content.py#L591

**Comment by jensens** [comment]
Since this is not reproducible with the the default Plone setup: Whats steps are needed? Just removal of `plone.dublincore` is not enough it seems.

**Comment by zopyx** [comment]
Yes, that's one of these weird errors. I compared the instance dicts of objects after manual vs. programmatic modifications and could not find an error.
