### ISSUE TITLE
Implement service to check and run Plone upgrade

### ISSUE THREAD

**Issue by ericof** [plone/plone.restapi#1525]
One missing feature in the headless implementation of plone.restapi is the ability to upgrade a Plone site.

**Comment by davisagli** [comment]
And, create one. Right?

**Comment by ericof** [comment]
> And, create one. Right?

Create a Plone site?

**Comment by davisagli** [comment]
Currently creating a Plone site requires Python code, or using the @@plone-addsite view on the Zope root. It could be handy to have a REST service for this too.

**Comment by ericof** [comment]
This is already implemented, so closing the issue.
