### ISSUE TITLE
Automatically update version in translated_messages_addons.resp after release.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#1538]
The version number in `http-examples/translated_messages_addons.resp` must be updated after every release, otherwise the 'no uncommitted changes' test will fail the next time someone runs the tests or makes a PR.

This should be possible with a [`zest.releaser` entry point](https://zestreleaser.readthedocs.io/en/latest/entrypoints.html) specific for `plone.restapi`. An example of such an entry point is in `i18ndude` for updating the output of the command line help in the documentation. The parts are:

- [`setup.py` registration](https://github.com/collective/i18ndude/blob/5.5.0/setup.py#L62-L65)
- [`setup.cfg` registration](https://github.com/collective/i18ndude/blob/5.5.0/setup.cfg#L1-L3)
- [the code for the hook](https://github.com/collective/i18ndude/blob/5.5.0/src/i18ndude/utils.py#L190)

I guess it only needs to be in one of `setup.py` or `setup.cfg`, not both. But it has been a while since I did this, so I am not sure. Having it in `setup.cfg` should mean that you get an error when the hook is for some reason not found. This may or may not be what you want. Having it in `setup.py` should mean it is available globally whenever you release any package, so you need to take care to only have it really do something when releasing `plone.restapi`, but this is an easy check to add.

The best hook would probably be `zest.releaser.postreleaser.middle`.

**Comment by mauritsvanrees** [comment]
Example of manual change after release: commit cb63e1ac4aff0570bedba0b88bceb31c34325a88.
The 'test no uncommitted changes' actually [fails](https://github.com/plone/plone.restapi/actions/runs/3495378069/jobs/5852075925) there, but that is for different reasons.

**Comment by tisto** [comment]
@mauritsvanrees thanks for creating this issue. I was just about to create one. Just for reference I added a comment in the commit that introduced this:

https://github.com/plone/plone.restapi/commit/baa018e65dff1766cf8723b05ef956a107b0ee8f#r90677638

I am wondering if zest.releaser is the way to solve this. We freeze datetime values in the plone.restapi testrunner and I was wondering if we can't monkeypatch the setup.py version during the testrun. I have no clue what's the better way I just wanted to add this as an idea to discuss here...
