### ISSUE TITLE
add RDBMS insert,delete,modify,query to restAPI

### ISSUE THREAD

**Issue by adam139** [plone/plone.restapi#1543]
I have some Web applications based Plone 5 and MySQL or Oracle through by Sqlalchemy.
Now,I plan to update them to Plone 6 and Volto frontend. But I found plone.restAPI do not support RDBMS.
I expect upgrade restAPI service to support RDBMS.

**Comment by ale-rt** [comment]
Just my 2 c.

Plone by default does not use a RDBMS but uses an object DB.
Therefore I do not see the benefit in developing that functionality in plone.restapi.
It would indeed be something cool to have in an addon.

**Comment by adam139** [comment]
I agree that develop an addon for operating the RDBMS restapi.

**Comment by jensens** [comment]
I would see those endpoints as partif an addon.
