### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by pgacv2** [plone/plone.restapi#156]
docs/source/_json/types_document.json#L115

"nolonger" should be "no longer."

**Comment by gforcada** [comment]
Thanks for reporting it! It's already fixed on master

**Comment by gforcada** [comment]
I had to revert it because travis complained about it... @tisto @buchi how are docs supposed to be updated?

**Comment by tisto** [comment]
@gforcada this fix does not make any sense because this file is auto-generated code by our documentation. This has nothing to do with plone.restapi I think. @pgacv2 is also not a foundation member, shouldn't that have been reported in the pull request as well?

**Comment by buchi** [comment]
@gforcada This is a typo in p.a.dexterity that has to be fixed there. https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/behaviors/metadata.py#L160-L161

**Comment by gforcada** [comment]
@buchi thanks, fixed!
