### ISSUE TITLE
ExpiredSignatureError: Signature has expired -- returns 500 instead of 400

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#159]
Given a expired token, the server returns a 500 and the message:

```
{
  "message": "Signature has expired", 
  "type": "ExpiredSignatureError"
}
```
And the error:

```
  Module jwt.api_jwt, line 75, in decode
  Module jwt.api_jwt, line 104, in _validate_claims
  Module jwt.api_jwt, line 149, in _validate_exp
ExpiredSignatureError: Signature has expired
```

It should be somehow a 401 or maybe give a chance to renew the token (I don't know if that's possible getting at this point.

**Comment by tisto** [comment]
@sneridagh the server should return a 401 (unauthorized). I think the client should take care of the token renewal. Auto-renewing the token feels to be a bit too much to me. @buchi opinions?

**Comment by tisto** [comment]
@sneridagh I just double checked and it turns out the current implementation is correct. An invalid token returns a HTTP 400, which is correct according to the RFC:

https://tools.ietf.org/html/rfc6749#section-5.2

The authorization server responds with an HTTP 400 (Bad Request)
   status code (unless specified otherwise) and includes the following
   parameters with the response:

        ...
        invalid_grant
               The provided authorization grant (e.g., authorization
               code, resource owner credentials) or refresh token is
               invalid, expired, revoked, does not match the redirection
               URI used in the authorization request, or was issued to
               another client.

--

Please provide us with the necessary information to reproduce the 500 you encountered.

**Comment by tisto** [comment]
@sneridagh I added a test to show that the server returns a 400 response: 

https://github.com/plone/plone.restapi/pull/160

**Comment by sneridagh** [comment]
@tisto It would be difficult to reproduce (and test), since you need an expired token. The raise came directly from jwt.api_jwt, maybe we can intercept it and put the correct 400 status code in the response instead of the 500.

**Comment by tisto** [comment]
@sneridagh right. I would like to write another test to trigger that problem. I just need to figure out how to generate an expired token. @buchi do you have a pointer for me?

**Comment by lukasgraf** [comment]
@tisto I believe creating a token with an `exp` in the past should work? https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/pas/plugin.py#L193

**Comment by tisto** [comment]
@sneridagh I created a functional test case for auth from the scratch:

https://github.com/plone/plone.restapi/pull/164/files#diff-ba94937d2482a112f9b033a9a89deb4bR124

I still can not reproduce the problem. What kind of resource do you try to access?

Here is the full pull request:

https://github.com/plone/plone.restapi/pull/164

**Comment by squarewave24** [comment]
using `pyjwt==1.7.1` and having the same problem. catching the exception and re-raising seems like a backwards solution :(

**Comment by tuyennta** [comment]
I got the same problem as @squarewave24 , same pyjwt version.
But it weird, I only get this error when running my api on heroku worker, on my local machine it works as expected (return 401)

This is my Procfile content for heroku:
`web: NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn wsgi:app --conf gunicorn.conf.py -t 120
`
I run this command on local machine then get no errors:
`NEW_RELIC_CONFIG_FILE=newrelic.ini newrelic-admin run-program gunicorn wsgi:app --conf gunicorn.conf.py -t 120
`
