### ISSUE TITLE
Add parameters to users DELETE endpoint

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#1598]
We have been hit by this issue that was raised [in the Community Forum some time ago](https://community.plone.org/t/alternate-way-do-delete-users/3009). We can't delete users in our Volto site because it has a lot of users and content, and the deleting goes through all objects walking up them all.

The solution is to pass `delete_memberareas` and `delete_localroles` as `False` to the `deleteMembers` method of `portal_membership` (knowing, of course, that local roles will not be removed).

So, how can we expose this in the `@users` endpoint's `DELETE` method?

It looks like `DELETE` method calls should not have any request body, so the only alternative is to pass those options as parameters in the url, say

```http
DELETE /@users/erral?delete_localroles=0&delete_memberareas=0
```

Is this acceptable or do you see any other way to handle this?

**Comment by davisagli** [comment]
Another way would be with a custom request header, but the solution with the query string looks fine to me.

**Comment by Coder-aadarsh** [comment]
Well passing those options as query parameters in the URL is a valid approach for handling this issue. As you mentioned, DELETE requests should not have a request body, so passing the options as query parameters is the appropriate way to do it.
