### ISSUE TITLE
@contextnavigation endpoint uses plone.api

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#1641]
The `@contextnavigation` endpoint uses `plone.api` in its implementation, which, if I am not wrong, is not allowed by our policy:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/contextnavigation/get.py#L8

**Comment by kshitiz305** [comment]
HI I would like to contribute to it, may I know what should be the ideal API that needs to be used.

**Comment by stevepiercy** [comment]
@kshitiz305 
please read and follow [Contributing to Plone](https://6.docs.plone.org/contributing/index.html) and [First-time contributors](https://6.docs.plone.org/contributing/first-time.html). As far as what needs to be done, @erral may have more information.

**Comment by kshitiz305** [comment]
@stevepiercy I have already gone through the agreement and would like to start contribution this would be my second contribution the project

**Comment by stevepiercy** [comment]
@kshitiz305 unless I am mistaken, you are not a member of the Plone GitHub organization, nor do you have any contributions to this project.

- https://github.com/orgs/plone/people?query=kshitiz305
- https://github.com/search?q=repo%3Aplone%2Fplone.restapi%20kshitiz305&type=code

**Comment by kshitiz305** [comment]
@stevepiercy I had sent the Signed agreement Once the agreement he is verified by your team the pull request will be merged
https://github.com/plone/plone.app.contentmenu/pull/48

**Comment by erral** [comment]
The contextnavigation endpoint uses a `plone.api.content.get_state` call to get the content's state

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/contextnavigation/get.py#L401

But the use of plone.api is only allowed in tests of this plone.restapi package, so this call should be replaced with the proper call to the get the state of the content.

You can check some other parts of plone.restapi to find the proper method to be called.

**Comment by davisagli** [comment]
@erral plone.api is already used in a few places. I think it is no problem, since plone.restapi is considered a core addon that sits on top of CMFPlone. It does not create a circular dependency, as long as plone.api does not import from plone.restapi.

@jensens Did I get it right?
