### ISSUE TITLE
plone.autoform.directives.read_permission doesn’t work in restapi

### ISSUE THREAD

**Issue by folix-01** [plone/plone.restapi#1662]
plone.autoform.directives.read_permission directives seem to not work with restapi(the field is never shown if use this directive)

**Comment by davisagli** [comment]
Please give the specific steps to reproduce the problem

**Comment by folix-01** [comment]
Just try to sign any field using this techique https://github.com/plone/plone.autoform#:~:text=class%20IMySchema(model.Schema)%3A%0A%20%20%20%20form.read_permission(secret%3D%27cmf.ManagePortal%27)%0A%20%20%20%20form.write_permission(secret%3D%27cmf.ManagePortal%27). And try to test if it is visible via RESTApi of plone

**Comment by folix-01** [comment]
@davisagli I just tried it on the content get endpoint, using the `site administrator` and `member` users.
