### ISSUE TITLE
Document steps to contribute that are specific to plone.restapi

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1664]
> But ideally, you have `black` installed locally, and format the code before committing. You can install it by running the `make` command inside the `plone.restapi` folder. After running `make`, you can run `make black`. This will automatically format the code for you. Some IDEs also have integration with `black`, to format the code when saving.
> 
> The `make` command will also install all of the package's dependencies. Then you can run the tests locally, with the command `make test`.

This should go into the documentation: https://6.docs.plone.org/plone.restapi/docs/source/contributing/index.html. It's not in the README. At the very least, an output of the `make help` command would be good.

_Originally posted by @stevepiercy in https://github.com/plone/plone.restapi/issues/1655#issuecomment-1622111298_

**Comment by Akshat2Jain** [comment]
@stevepiercy, Why this issue is still open?

**Comment by davisagli** [comment]
@Akshat2Jain I'll close it now. In order for github to close it automatically when the PR is merged, the PR description needs to say "Fixes #1664" or "Closes #1664"
