### ISSUE TITLE
Is expansion an endpoint or a usage technique?

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.restapi#1677]
I just realized that expansion might not actually belong in [Endpoints](https://6.docs.plone.org/plone.restapi/docs/source/endpoints/index.html), but instead might belong in [Usage](https://6.docs.plone.org/plone.restapi/docs/source/usage/index.html), because expansion is more of technique to return a collection endpoints but is not an endpoint itself. This should be discussed with the maintainers.

_Originally posted by @stevepiercy in https://github.com/plone/plone.restapi/issues/1374#issuecomment-1666430379_

**Comment by davisagli** [comment]
@stevepiercy Yes, https://6.docs.plone.org/plone.restapi/docs/source/endpoints/expansion.html should be moved to the Usage section.

It's okay for the pages about specific endpoints to include examples of how to use them via expansion, if they support it. https://6.docs.plone.org/plone.restapi/docs/source/endpoints/navroot.html is a page that was added recently which shows how to use the endpoint both standalone and via expansion.

**Comment by stevepiercy** [comment]
Looking at the http request/response examples, it appears that there are currently eight components that support expansion. Is that right?

```
actions
aliases
breadcrumbs
contextnavigation
navigation
navroot
types
workflow
```

**Comment by davisagli** [comment]
@stevepiercy Yeah, that looks right (with the addition of `translations` in #1676)
