### ISSUE TITLE
Github Actions are skipped

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#1694]
https://github.com/plone/plone.restapi/pull/1570

![Use-incoming-request-to-produce-location-for-tus-upload-by-instification-·-Pull-Request-1570-·-plone-plone-restapi](https://github.com/plone/plone.restapi/assets/632105/0ee62d1d-d3c2-4bbf-8dae-6518bed0674d)

**Comment by stevepiercy** [comment]
Although this is misleading, it is OK. If you scroll down, you will notice that there are duplicate jobs that do run on _push_ but not on _pull request_. See https://github.com/plone/plone.restapi/issues/1656 and an example workflow file https://github.com/plone/plone.restapi/blob/master/.github/workflows/black.yml#L5.

**Comment by tisto** [comment]
@stevepiercy I just saw that and reverted my experiment on the master branch. Though, I am not sure if I am happy with the tradeoff here. Being able to run pull requests on forks is a nice feature. However, if this means that the display of the CI is misleading we might have to reconsider.

**Comment by stevepiercy** [comment]
It is misleading, until you realize that each job has a distinction of when it should run in parentheses. Once I saw that, I understood.

The alternatives are to pay for Enterprise GitHub where we have granular control over permissions, but we are not made of money, or we could reopen the gates to allow anyone to push to `master` who has signed the Plone Contributor Agreement, but that risk is completely unacceptable. I suppose someone could scream into the abyss that is GitHub feature requests, and ask them to hide jobs that are skipped, but I'm sure they have reasons for this UI decision.
