### ISSUE TITLE
Code that seems to do nothing

### ISSUE THREAD

**Issue by tiberiuichim** [plone/plone.restapi#1703]
https://github.com/plone/plone.restapi/blob/ed192208499989b379de8534a3aa12d037316db4/src/plone/restapi/services/navigation/get.py#L166C2-L167

**Comment by tisto** [comment]
@tiberiuichim it used to do an escape(). I guess this was not reviewed after a search/replace:

https://github.com/plone/plone.restapi/commit/293e859a6f6ad6596a455448a46d08864acf7f6f

cc @sneridagh

**Comment by sneridagh** [comment]
Could be a leftover from a merge, or it went inadvertently after the change... I don't think it has any real purpose. It would be save to remove it, I guess.
