### ISSUE TITLE
jwt_auth PAS plugin is active without being installed

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#1711]
Create a Plone 6.0.7 ClassicUI site with plone.restapi in the eggs, but not installed.
Go to `Plone/acl_users` and check that `jwt_auth` is not in the plugins.

Now add an image, select an image larger than 1MB, and save the add-form:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 391, in publish_module
  Module ZPublisher.WSGIPublisher, line 269, in publish
  Module ZPublisher.BaseRequest, line 619, in traverse
  Module Products.PluggableAuthService.PluggableAuthService, line 244, in validate
  Module Products.PluggableAuthService.PluggableAuthService, line 560, in _extractUserIds
  Module plone.restapi.pas.plugin, line 100, in extractCredentials
  Module plone.restapi.deserializer, line 8, in json_body
  Module ZPublisher.HTTPRequest, line 1058, in get
  Module ZPublisher.HTTPRequest, line 1370, in __get__
zExceptions.BadRequest: data exceeds memory limit
```

The BadRequest means that Zope needs to be configured to allow bigger uploads.  See https://github.com/plone/Products.CMFPlone/issues/3848

But `plone.restapi.pas.plugin` should **not** be in this traceback.  It should not be active unless it is in `acl_users/plugins`.

**Comment by davisagli** [comment]
@mauritsvanrees I can't reproduce this. I updated my coredev 6.1 buildout and created a new classic UI site. Then I was able to upload an image without any errors. plone.restapi is not installed, nor in the PAS plugins.

From what I can see, it is installed as part of the plone.restapi default profile: https://github.com/plone/plone.restapi/blob/main/src/plone/restapi/setuphandlers.py#L52

**Comment by wesleybl** [comment]
@davisagli I haven't tested it in Plone 6.1 but I managed to reproduce this problem in Plone 6.0.7.

**Comment by davisagli** [comment]
@wesleybl What steps did you take to set up the site?

**Comment by wesleybl** [comment]
I accessed:

http://localhost:8080

- I clicked on the light blue button ("Create Classic Plone site")
- In my creation form I left the language "Portuguese (Brazil)" and the time zone "Sao_Paulo"
- I clicked on "Create Plone site"
- I added an Image type and selected an image larger than 1 mb

**Comment by davisagli** [comment]
@wesleybl This ticket is about the fact that the jwt_auth plugin is used when it shouldn't be. The 1mb file upload limit is a separate problem (here it just reveals a traceback showing that jwt_auth's patch was in effect).

See https://github.com/plone/Products.CMFPlone/issues/3848 for more about how to increase the limit on file upload size.

**Comment by wesleybl** [comment]
@davisagli but the file size error is evidence that the plugin is working without plone.restapi being installed. On the site I created, plone.restapi is not installed, but I still see it in the file upload error traceback.

**Comment by davisagli** [comment]
@wesleybl Okay right, I follow your logic now. It is the plugin's attempt to read the request body as JSON which triggers hitting the memory limit.

I'll check again when I find time.

**Comment by wesleybl** [comment]
@davisagli @mauritsvanrees I found out what it is. In my Zope instance that I managed to simulate the problem, I had already created a standard Plone site before. On this default Plone site `plone.restapi` is installed. Installing `plone.restapi` enables `jwt_auth` in the Zope root `acl_users`:

https://github.com/plone/plone.restapi/blob/f90329dfe49aa483517861a610b5175d68e0b6be/src/plone/restapi/setuphandlers.py#L34

So if you have a default Plone installed, all other Plone sites will be affected.

I think we can close this issue now.

**Comment by mauritsvanrees** [comment]
Ah, thanks for digging that up @wesleybl.  I confirm your analysis.

But why is the plugin created at the Zope root acl_users as well?  Okay, this is to support [logging in root Zope users](https://github.com/plone/plone.restapi/pull/412).  Seems to make sense.

Thank you both for having a look.  I close this.
