### ISSUE TITLE
Global Site tabs should also be customizable with customize_entry

### ISSUE THREAD

**Issue by tiberiuichim** [plone/plone.restapi#1713]
https://github.com/plone/plone.restapi/blob/8abf2055a5002f89505d7c17a20768f661806bde/src/plone/restapi/services/navigation/get.py#L153

https://github.com/plone/plone.restapi/blob/8abf2055a5002f89505d7c17a20768f661806bde/src/plone/restapi/services/navigation/get.py#L80-L100

**Comment by tisto** [comment]
@tiberiuichim not sure if I get this one. portal_tabs is already configurable:

https://github.com/plone/plone.restapi/blob/8abf2055a5002f89505d7c17a20768f661806bde/src/plone/restapi/services/navigation/get.py#L188

What else would you like to be able to configure?

**Comment by tiberiuichim** [comment]
@tisto It's not a matter of "is it configurable", it's a case of "If I have my own custom `customize_entry`, it should be applied to everything in the generated navigation tree, including the toplevel tabs". As we can see in the Plone navigation code, the `topLevelTabs` allows even Links to be used, so it's not like "if it's top-level section, it's special". https://github.com/plone/Products.CMFPlone/blob/3129403f3524a31a15dae152edefb9380486f1f8/Products/CMFPlone/browser/navigation.py#L139-L142

**Comment by tisto** [comment]
@tiberiuichim ok, got it. I guess this was more or less a conscious decision. I re-implemented the navigation tree algorithm multiple times in my career and I found it inefficient (aka slow) and super hard to understand. Therefore we decided that a simpler approach, that is more optimized toward the default Volto use case would be better (without all the customization options). 

In the end, we do not have a navigation portlet any longer. Therefore the question here is: do we want to support ClassicUI and the old way or do we fully embrace optimizing the Volto use case.

Since ClassicUI never made the move towards using plone.restapi (and as far as I know they don't intend to) I did not really see the use case so far.

Though, maybe I did not fully grasp your use case here.

**Comment by tiberiuichim** [comment]
@tisto this is not about conceptual issues, this is a simple simple small implementation detail. Regardless of how we do the implementation in restapi (the reality is that we actually use CMFPlone code in it), it's a simple matter of (pseudocode):

```
def mynav():
     toplevel = [entry1, entry2]
     for entry in toplevel:
           entry[items] = self.customize(item) for item in subtree(entry)
     return toplevel
```

So, my whole thesis is that `self.customize()` should be called on the toplevel entries rather then only on the subchild, just to make the handling of the whole navtree completely uniform. Even though the result data structure is uniform, the toplevel entries are treated differently, because `customize()` is not called on them. My proposal is to have this sort of pseudocode:

```
def mynav():
     toplevel = [entry1, entry2]
     for entry in toplevel:
           entry[items] = self.customize(item) for item in subtree(entry)
     toplevel = [self.customize(entry) for entry in toplevel]
     return toplevel
```

It's strictly related to calling `customize_entry` on the toplevels. 

https://github.com/plone/plone.restapi/blob/8abf2055a5002f89505d7c17a20768f661806bde/src/plone/restapi/services/navigation/get.py#L153

**Comment by tisto** [comment]
@tiberiuichim ok, that makes sense. Thank you for the clarification!

**Comment by tiberiuichim** [comment]
In the end I've declared a custom `@@portal_tabs_view` and declared a `customize_entry` there, because the [default implementation already includes that part](https://github.com/plone/Products.CMFPlone/blob/39f44ee5c2d888b9ba7b0179af3ed8ed01bedc2e/Products/CMFPlone/browser/navigation.py#L161)

It's actually not even possible to achieve a customize_entry for portal tabs in plone.restapi, as it's "too late", `topLevelTabs()` only returns dicts and no brains.
