### ISSUE TITLE
Endpoint for retrieve the current user information

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#172]
When in an app we need to retrieve basic information about the current logged in user, like display name, username, email or even avatar.

What do you think that would be the right naming for such an endpoint?
Something like `@users/current` don't feels right enough... and could clash with a user named "current" (unlikely, though...).

In the future we will require some endpoint to perform actions over the curent user as well such password change and the like...

@bloodbare @buchi @lukasgraf any insight?
/cc @tisto

**Comment by tisto** [comment]
@sneridagh question would be if we would still need such an endpoint if we include the information about the currently logged in user in any request anyways: 

https://github.com/plone/plone.restapi/issues/179

**Comment by tisto** [comment]
Will close for https://github.com/plone/plone.restapi/issues/211
