### ISSUE TITLE
Include addable types constraints in plone.restapi

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#173]
Right now there is no way for a client to tell which content types are addable in a certain context (or globally).

The "types" endpoint just lists all existing content types, a first step would be to include the global_allow attribute there.

Though, we still need to include the information which content types are addable in a certain context. This would need to be embedded in the regular content response I guess. 

Problem is we need to somehow solve the actions/framing API design in order to properly implement this.

**Comment by jaroel** [comment]
- add 'addable' to type info, based on context.getAllowedTypes. Same as the add menu.
- add 'global_allow' to type info.
- allow @types on all context.

Should do?:
- mutate/set allowed types on context
