### ISSUE TITLE
Mistake in documentation about creating-a-resource-with-post

### ISSUE THREAD

**Issue by mr-rob** [plone/plone.restapi#174]
The example provided for python-requests is faulty. (http://plonerestapi.readthedocs.io/en/latest/crud.html#creating-a-resource-with-post)
Instead of `requests.post('http://localhost:8080/Plone/folder', auth=('admin', 'admin'), headers={'Accept': 'application/json'}, params={'@type': 'Document'})`
it should be `requests.post('http://localhost:8080/Plone/folder', auth=('admin', 'admin'), headers={'Accept': 'application/json'}, json={'@type': 'Document'})` 
(replace `params` with `json`)

**Comment by envy7** [comment]
@mr-rob the page you mentioned http://plonerestapi.readthedocs.io/en/latest/crud.html#creating-a-resource-with-post dosen't exist and here http://plonerestapi.readthedocs.io/en/latest/content.html#creating-a-resource-with-post
the python-requests example
`requests.post('http://nohost/plone/folder', headers={'Accept': 'application/json'}, json={'@type': 'Document', 'title': 'My Document'}, auth=('admin', 'secret'))`
seems correct is this is an outdated issue?

**Comment by tisto** [comment]
@mr-rob we replaced all our examples with a new system. Could you please check if this problem still persists?

**Comment by mr-rob** [comment]
All good!
