### ISSUE TITLE
Community Forum App Icon Not Filling Correctly.

### ISSUE THREAD

**Issue by danielnabil** [plone/plone.restapi#1765]
**Issue Description:**
The image in the mobile app for the community forum does not properly fill the icon.

**To Reproduce**
1-Download The app from Google Browser

**Expected behavior**
Ensure that the Plone logo fills the icon properly across different mobile apps.

**Screenshot:**
![WhatsApp Image 2024-03-26 at 19 00 51_dd8d51e3](https://github.com/plone/plone.restapi/assets/141129283/86dada70-26d5-41d5-ba14-51a68600a047)

**Software:**
Android Version: [11]
Model Name: [Galaxy A52]

**Comment by davisagli** [comment]
This has nothing to do with plone.restapi
