### ISSUE TITLE
No way to determine whether next/ previous should be used from a content response

### ISSUE THREAD

**Issue by JeffersonBledsoe** [plone/plone.restapi#1797]
If `Enable next previous navigation` is unchecked or the `Next previous navigation` is disabled, the `next` and `previous` keys are still included in the response. This means that currently the only way to know whether the `Next/ Previous` should be used is to get the schema information for the content type and lookup the information there, but this requires a logged-in user.

## Proposed solutions

- A `Next/ previous enabled` key is added  to the content response which indicated whether the next/ previous should be used or not.

## Other options

- The 'Next' and 'Previous' keys are not included if the behaviours aren't enabled or the toggle behaviour is on but the toggle is unselected.
  - Unfavourable due to this being a breaking change in the response

**Comment by davisagli** [comment]
I'd suggest a variation on your "other option": if the behaviors aren't enabled or the toggle behavior is on but the toggle is disabled, then set `next_item` and `previous_item` to an empty object. This is backwards compatible with the current implementation when there isn't a next/previous item or there's an error looking it up.
