### ISSUE TITLE
if there's a check for "'path' in item" then accessing directly item['path'] is unsafe

### ISSUE THREAD

**Issue by tiberiuichim** [plone/plone.restapi#1801]
https://github.com/plone/plone.restapi/blob/0e86c7663b82dbdde862eab11e859bf269142ce9/src/plone/restapi/services/navigation/get.py#L162-L166

**Comment by davisagli** [comment]
@tiberiuichim The `"path" in item` check looks unnecessary here, but I don't see an obvious bug. `render_item` is called with items from the `navtree` property, and it includes the `path` key for each item.

If you encountered an error from this, please re-open with more information about the steps to reproduce the error.

**Comment by rohnsha0** [comment]
The original code tries to access `item["path"]`, but it doesn't check if "path" is actually in the dictionary first. This can cause a KeyError if "path" is missing. Even though the code does check for "path" later on, it's too late to avoid the potential error.

**Comment by rohnsha0** [comment]
when caught, it can be changed... for future erros... and can be marked as an enhancement

**Comment by stevepiercy** [comment]
@rohnsha0 we need:

1. Steps to reproduce the issue that you observed.
2. Full stack trace.

A code analysis provides neither of these items. Thank you!
