### ISSUE TITLE
Cannot update JWT keyring and store token properties

### ISSUE THREAD

**Issue by sauzher** [plone/plone.restapi#1803]
Open `Plone/acl_users/jwt_auth/manage_config`

- check `use keyring` and `store tokens` checkbox
- save
Result:
The values are back to blank/False

Solve:
The input fields in the ZPT need a `value="True"` ([here](https://github.com/plone/plone.restapi/blob/37d02e7772b1b402ef74b8e55bc7ea4ad786d014/src/plone/restapi/pas/config.zpt#L23C13-L23C14) and [here](https://github.com/plone/plone.restapi/blob/37d02e7772b1b402ef74b8e55bc7ea4ad786d014/src/plone/restapi/pas/config.zpt#L35)) to please the Bool casting in updateConfig here:

https://github.com/plone/plone.restapi/blob/37d02e7772b1b402ef74b8e55bc7ea4ad786d014/src/plone/restapi/pas/plugin.py#L148-L149

**Comment by davisagli** [comment]
Fixed in #1804
