### ISSUE TITLE
@search endpoint path.query does not work with VHM

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#186]
Given a site is behind a VHM config using a root server name, so the instance name is hidden, when you request

`@search?path.query=/`

You don't get nothing, and if you use the name of the instance:

`@search?path.query=/Plone`

 it works fine.

For consistency I would match the VHM configuration, so the query root matches the root of the server. Thus, the users don't have to know the instance name behind a server deployment.

/cc @tisto

**Comment by lukasgraf** [comment]
@sneridagh I agree with the desired behavior you described. Hopefully I'll get around to a fix for this soon.

**Comment by sneridagh** [comment]
Cool! I remember to have a similar bug while implementing p.a.m. and the
test fixture for testing it was insane :(

Please tell me if I can help in sonething.


On Thu, 19 Jan 2017 at 19:57, Lukas Graf <notifications@github.com> wrote:

@sneridagh <https://github.com/sneridagh> I agree with the desired behavior
you described. Hopefully I'll get around to a fix for this soon.




—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/plone/plone.restapi/issues/186#issuecomment-273865259>,
or mute the thread

**Comment by sunew** [comment]
@sneridagh and @lukasgraf this was fixed by csengers PR (and I have fixed restricting to multiple paths behind vhm in https://github.com/plone/plone.restapi/pull/615 )

I close this issue :)
