### ISSUE TITLE
Null value representation. WAS: How to clear a datetime field with json?

### ISSUE THREAD

**Issue by pabo3000** [plone/plone.restapi#187]
It is Plone site with plone.restapi installed. There is a dx content type with a zope.schema.Datetime field. It is declared in this way:

```
<model xmlns="http://namespaces.plone.org/supermodel/schema">
  <schema>
    <field name="due" type="zope.schema.Datetime">
      <description/>
      <title>due</title>
      <required>False</required>
    </field>
  </schema>
</model>
```
Let's assume the value of the field is any Datetime. But now the value should be unset by a json rest call (Update, Patch. After that call the field should be unset. How does the json call look like?

I have tested some possibilties which were not successful:

```
PATCH {}
PATCH {"due":""}
PATCH {"due":"None"}
PATCH {"due":null}
PUT {}
```
I think there should be a possibility to reset a Datetime field via rest. Therefore I append this issue.

**Comment by tisto** [comment]
@pabo3000 we indeed need a way to represent null values in the API. I will look into it...

**Comment by tisto** [comment]
I did some initial research and I think using PATCH {'my-field': null} is the way to go. Since a PATCH by definition only contains a partial resource, not sending a field is not an option here.

@robgietema @ebrehault what do you think? How does plone-react and the angular sdk currently handle this?

I plan to work on this during the sprint next week...

**Comment by davisagli** [comment]
`PATCH {"my-field": null}` makes sense to me as the way to set a field's value to `None` in Python.

**Comment by lukasgraf** [comment]
In the case of Dexterity, to **unset** a field the stored value being written should actually be `field.missing_value` I believe, which is not necessarily Python `None`.

See [`missing_value` in `zope.schema`](https://github.com/zopefoundation/zope.schema/blob/919388ca4e26346f1a4463e0fecc8ad2fd9f871b/src/zope/schema/_bootstrapfields.py#L88-L95) and  [p.a.dexterity docs on field properties](https://docs.plone.org/external/plone.app.dexterity/docs/reference/fields.html#field-properties)

Unfortunately, that is semantically different from just setting a field's value to `None`, which one might also want to do.

Either way, I think it's imporant that we're really clear about the exact semantics of the operation in question: Is it supposed to **unset** a field, or **set it to a null value**?

**Comment by csenger** [comment]
I added support for null/None in #513 . It will set the value to field.__missing_value__. It's dx only.

There is an theoretical edge case where None is a valid value and missing_value is not None (None is the default). But it would be a broken use case and we chose a clean implementation over adding more complexity and marker values to plone.restapi.
