### ISSUE TITLE
Fix plone.restapi demo.

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#188]
Our heroku demo app does not work reliably, the deployment is fragile and hard to maintain: http://stormy-headland-44390.herokuapp.com/Plone/

I think it is essential that we provide developers an easy way to test and explore plone.restapi. I could imagine to set up and maintain a demo for plone.restapi on our servers. Other ideas or opinions?

**Comment by prakharjoshi** [comment]
Heroku is always a pain to maintain, we can deploy the plone instance on Digital Ocean.

**Comment by tisto** [comment]
@prakharjoshi do they offer free instances?

**Comment by prakharjoshi** [comment]
@tisto No they cost around $5 per month for basic machine. But for free hosting we can use openshift. look at this once https://www.openshift.com/devpreview/

**Comment by tisto** [comment]
@prakharjoshi hardware isn't really a problem. As said, I could provide a server. The only downside is that I have to maintain it myself...

**Comment by prakharjoshi** [comment]
@tisto  Yeah maintenance will be a burden but AFAIK, only heroku provide free services rest all charge us for their services. If we have to pay then we should use AWS.
