### ISSUE TITLE
Convention for non-resource action names in URLs

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#194]
We need a convention for action names (or resource attributes) in plone.restapi. We decided to just map over ZODB object attributes, which is fine. Though, if we design API "actions" such as reset the password of a user (e.g. /plone/@users/timo/reset_password), we need a convention that we can stick to. Please not this ticket is not about object attribute naming conventions, we are talking about URLs.

Options are:

- underscore: /plone/@user/timo/reset_password
- camel case: /plone/@user/timo/ResetPassword
- lower camel case: /plone/timo/@user/resetPassword
- spinal-case /plone/@user/timo/reset-password
- no separator: /plone/@user/timo/resetpassword

**Comment by tisto** [comment]
Discussion started here: https://github.com/plone/plone.restapi/issues/179

**Comment by tisto** [comment]
Here are my initial thoughts:

1) underscore/snake case: 

PRO:

- Pythonic
- We (mostly) use it for our object attributes
- Readability: there_is_some_scientific_evidence_that_underscore_is_better_readable_than_camel_case vs. thereIsSomeScientificEvidenceThatUnderscoreIsBetterReadableThanCamelCase

CON:

- We like it because we know it
- We expose implementation details to the API consumer
- underscore is not what JS developers are used to
- underscore is not considered best practice for JSON
- my frontend devs tell me they don't like it

2) CamelCase (lower/upper):

PRO:

- my frontend devs like it
- in sync with what the JS world uses
- in sync with the JSON spec

CON:

- readability: thereIsSomeScientificEvidenceThatUnderscoreIsBetterReadableThanCamelCase
- could lead to problem with case insensitive components/libs
- it reminds me of Java/Zope :)

3) Spinal case

PRO:

- it feels right for URLs
- readability is not as good as snake case but definitely better that camel case: case there-is-some-scientific-evidence-that-underscore-is-better-readable-than-camel-case

CON:

- readability not as good as snake case
- not in sync with the JS/JSON world

4) no separator:

CON:

- hard to read
- not used much

**Comment by tisto** [comment]
I tend to make a decision between snake_case and spinal-case. Bottom line is we are talking about URL naming, so the pro argument I had on CamelCase is not valid and the readability of CamelCase is really bad. No separator is also out, because of the bad readability. 

I slightly tend to spinal-case because it feels natural to use it in URLs.

The "REST Resource Naming Guide" makes a case against snake_case in URLs because the underscore can be "partially obscured or completely hidden in some browsers or screens":

http://restfulapi.net/resource-naming/

RFC3986 seems to prefer hyphens over underscores:

```
Modifications: 

This change required all rule names that formerly included underscore characters to be renamed with a dash instead.
```

It specifically mentions hyphens in the scheme:

```
3.1.  Scheme:

   Scheme names consist of a sequence of characters beginning with a
   letter and followed by any combination of letters, digits, plus
   ("+"), period ("."), or hyphen ("-").  Although schemes are case-
   insensitive, the canonical form is lowercase and documents that
   specify schemes must do so with lowercase letters.  An implementation
   should accept uppercase letters as equivalent to lowercase in scheme
   names (e.g., allow "HTTP" as well as "http") for the sake of
   robustness but should only produce lowercase scheme names for
   consistency.

      scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )

```

Though RFC3986 of course allows underscores as well:

```

2.3.  Unreserved Characters

   Characters that are allowed in a URI but do not have a reserved
   purpose are called unreserved.  These include uppercase and lowercase
   letters, decimal digits, hyphen, period, underscore, and tilde.

      unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

https://www.ietf.org/rfc/rfc3986.txt

Opinions? @lukasgraf @sneridagh @bloodbare @buchi @erral anybody else?

**Comment by tisto** [comment]
Ok, here is another thing:

When you create an object in Plone, say "My Folder". Plone will automatically map the blank to a hyphen (-> "my-folder". Therefore our constructed URLs will always use hyphens. If we start to use underscores, we will end up with mixed URLs, e.g. "/my-folder/@send_url_to_user".

One could argue this is a pro argument because we can differentiate between content and an action. Though, my personal opinion is that this leads to confusing URLs. For URL consistency I'd go with hyphens then...

**Comment by tisto** [comment]
Just one more note about why we shouldn't use CamelCase in URLs. URLs are case sensitive (RFC3986). Therefore if an API consumer does not use the correct upper-/lowercase combination (e.g. lower vs. upper camel case) the URL will not be found. This could become incredibly frustrating.

**Comment by tisto** [comment]
Google seems to prefer hyphens (for SEO) as well: 

"We recommend that you use hyphens (-) instead of underscores (_) in your URLs."

https://support.google.com/webmasters/answer/76329

Though, one could we are designing an API, not a public facing website. The front end could use a different URL scheme.

**Comment by erral** [comment]
For front-end sites we have travelled from CamelCase to spinal-case and now we stick to spinal-case, Google likes it and it's simpler to share and write.

For API designing I would also go for spinal-case, just to keep consistent with other URLs.

**Comment by lukasgraf** [comment]
@tisto in URLs, I prefer **spinal-case** as well, for pretty much all the reasons you described.

**Comment by tisto** [comment]
spinal-case it is. Added to docs.
