### ISSUE TITLE
Improve the file/image upload endpoint

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#197]
The current implementation of the deserialiser for the file fields only supports accepting a JSON representation of the field (commonly in BASE64). This implementation is fine for migrations and import/export scenarios but we found out that is very difficult to implement this with real world widgets and UI components out there that are using a multipart/form-data POST request to upload files.

I think that we need a way to build an endpoint that is capable of handle the creation of field/image very much like the existing in p.a.content that it's used for the folder_contents pattern.

It would also be nice to be able to support TUS OOTB (I think that the current @vangheem  implementation should be updated to TUS 1.0.0).

@bloodbare @ebrehault @buchi @lukasgraf @vangheem @datakurre @erral @tisto 
What do you think? What solution are you using right now for standard widgets?

**Comment by sneridagh** [comment]
Related to #79

**Comment by erral** [comment]
We are right now using it in a import/export scenario between Plone sites using base64 encoded content.

**Comment by ebrehault** [comment]
I do not manage files via the REST API at the moment but I agree JSON with base64 is not enough here.

**Comment by lukasgraf** [comment]
Absolutely, inlined base64 is very limited in many regards, and most likely will need to be accompanied with additional modes of transportation I think.

@sneridagh we're not currently using that part of the API from the frontend side (I think - at least I'm not). As for backend-to-backend, it's a "good enough for now" kind of situation.

The challenge with other options is that some of the content negotiation / request dispatching stuff in `plone.rest[api]` is still somewhat tied to the `application/json` media type if I'm not mistaken.

**Comment by davisagli** [comment]
Looks like this was implemented: https://plonerestapi.readthedocs.io/en/latest/tusupload.html
