### ISSUE TITLE
Make @types endpoint provide a 'mode' attribute for widget visibility.

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#198]
Currently there is no way to hide a widget, we need a boolean "visible" attribute for hidden fields. cc @ebrehault

**Comment by tisto** [comment]
We might want to re-use the z3c.form concept of a "mode" attribute that can be input|display|hidden:

http://docs.plone.org/develop/addons/schema-driven-forms/form-types/display-forms.html

**Comment by ebrehault** [comment]
+1

**Comment by tisto** [comment]
Pull request: https://github.com/plone/plone.restapi/pull/204

**Comment by tisto** [comment]
Solved in https://github.com/plone/plone.restapi/pull/237
