### ISSUE TITLE
Example how to use ReactJS with plone.restapi

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#202]
I have something similar in mind to what we did with:

https://github.com/collective/tutorial-blog-angular2

e.g. starter tutorials, examples, ...

Here are a few things that we tackled with Angular 1/2 and that I would like to see for React:

- Authentication
- Routing
- Form generation (from json schema?)

**Comment by prakharjoshi** [comment]
@tisto Its really a great Idea to have a sample app using restAPI in react too. I will suggest we should use redux instead of flux when we build this app. Ideas ?

**Comment by tisto** [comment]
Will close the issue. We have a working example: https://github.com/plone/plone-react
