### ISSUE TITLE
Tile serialization support

### ISSUE THREAD

**Issue by tomgross** [plone/plone.restapi#203]
As a developer I want to use plone.restapi to expose and create mosaic/tile content with the plone.restapi to have a parity in the content an editor/user sees and the content which is handled with plone.restapi. 

In 1.0a8 the situation is the following:
- all content of the ILayoutAware behavior (content, contentLayout and customContentLayout) is exposed on GET since they are stored as normal schema
- Creating content of the ILayoutAware behavior does via PUT not work, since creating of tiles is missing only the layout and the _content_ of transient tiles is created (in the content storage)
- Creating of persistent tiles via PUT does not work, since they are stored as Annotations, which are not handled by plone.restapi at the moment. -> Maybe handling Annotations with plone.restapi is a different/more generic issue?

**Comment by tisto** [comment]
@tomgross this is definitely something we have on our todo list. We already discussed the annotations issue. Though, finishing the core functionality of plone.restapi is higher priority right now. 

We can re-evaluate after the Beethoven sprint in March (or have a remote session during the sprint to discuss this). If you want to work on it though feel free to start. Ideally, you would do a documentation-first approach, so we can discuss the API design on that basis.

**Comment by tomgross** [comment]
@tisto I won't have time to work on this myself but I can sponsor some money to have the mosaic part implemented.

**Comment by tomgross** [comment]
Close in favor of #350
