### ISSUE TITLE
Users endpoint does not expose custom user properties

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#211]
The user properties in the plone.restapi serializer are currently hard-coded:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/user.py#L21

It would be nice if plone.restapi would expose custom user properties automatically. Problem might be that this differs significantly between Plone 4 and 5.

**Comment by tisto** [comment]
Plone 4: https://github.com/plone/plone.app.users/blob/1.2.x/README.rst
Plone 5: https://github.com/plone/plone.app.users/blob/master/README.rst

**Comment by lukasgraf** [comment]
I think this came up in earlier discussions around serializing user properties:

We might want to be careful here about exposing people's custom properties (at least by default), because it's conceivable that people store sensitive information in custom user properties, like access tokens.

**Comment by tomgross** [comment]
Did someone look into http://www.simplecloud.info/ for the user / roles / password endpoints?

**Comment by davisagli** [comment]
This was fixed at some point.
