### ISSUE TITLE
Vocabularies endpoint

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#212]
We need an endpoint for vocabularies.

**Comment by ebrehault** [comment]
we do, and in schemas, the `choices` property must either contain the possible vocabulary values (as it is now) or a url to the vocabulary endpoint (question: how do we choose between explicit list or link?)

**Comment by csenger** [comment]
How should we handle vocabulary security? Vocabularies are utilities and usually have no permissions attached to them (through they could). There might be method calls in the vocabulary factory that check permissions somehow. But usually people write a vocabulary and secure the form/view that uses the vocabulary. I think we can't trust any vocabulary is secure to retrieve.

This is connected to the vocabulary link in the schema. We don't want to end up with a schema that contains a vocabulary link, but the user is not allowed to get the vocabulary.

* We can mark vocabularies that are safe or even include permission when we mark them, but that might get in conflict with the declaration of the utility. 
* We can mark vocabularies as 'rest serializable' and make sure all vocabularies we mark out of the box are either fine for anonymous users, or are secured through zcml/code.

**Comment by erral** [comment]
Vocabularies have also a human readable text that usualy is translated through po files. We may want to provide all those translations also the in vocabulary information.

**Comment by tisto** [comment]
Done: https://github.com/plone/plone.restapi/pull/219
