### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#215]
Right now it is not possible to do a full user registration process via plone.restapi.

1) Register a new user with an email address
2) User receives an email
3) User confirms the email and chooses a password

(we need to include all possible scenarios, with different settings).

**Comment by csenger** [comment]
The user registration for managers and anonymous users is very similar.
But the fields for the user registration are different depending on the user (Manager or Anonymous) and for Anonymous on the ISecuritySchema settings.

A generic front end needs the info which fields are allowed in a certain context. There are 2 possible options to archive this.

* Provide the relevant portal settings to the front end and replicate the business logic.
* Extend the endpoint to provide a list of allowed and required fields. Maybe with a json schema similar to the @types endpoint.

**Comment by tisto** [comment]
Pull request was merged: https://github.com/plone/plone.restapi/pull/255
