### ISSUE TITLE
Use plone.api in plone.restapi

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#234]
plone.api is shipped with core but not allowed to use in core packages to prevent circular dependencies and possible infinite loops.

Though, plone.restapi, even if we ship it with core in the future, will always be just a consumer of plone.api. It is highly unlikely and not desirable that plone.api depends in any way on plone.restapi (though, one could come up with examples if you really want).

Therefore we think it is not only save, but also desirable to use plone.api in the core. For one thing this will avoid re-implementing functionality in plone.restapi that already exists in plone.api. Though, this might also lead to a situation in the future where a Python developer might be able to implement plone.restapi endpoints with just mastering plone.api, without the need to understand the underlying stack.

We discussed this matter at the Beethoven Sprint in Bonn today with @jaroel @witsch @sneridagh @bloodbare @vangheem and others and reached an agreement.

CC @plone/framework-team: if you have any objections, please let us know asap. Even though, we do not have a PLIP to include plone.restapi in core yet, it would not be desirable to have to remove the plone.api dependency we are about to introduce.

**Comment by jensens** [comment]
Core is not allowed to do, because we have no clear boundaries in our dependency graph.

So, I would really like to define the line below and above plone.api in Plone core. So plone.restapi is the first consumer of plone.api and this makes perfect sense. I am also open discussing to allow usage of plone.api for other packages in future. 

I think important is to document the boundary and also great would be to have a test ensuring it, if this is possible.

**Comment by witsch** [comment]
@jensens, I completely agree & ftr, what you said was also a significant part of the discussions we had at the sprint.

Meanwhile, I've started to work on a [small tool](https://github.com/witsch/apitizer) to help refactor code to use `plone.api`.  It uses the [rope refactoring library](https://github.com/python-rope/rope) to hopefully automate most of the changes we want.  The first version can rewrite all uses of `getToolByName` (to `plone.api.portal.get_tool`) while keeping the (`plone.restapi`) tests happy.  I'm planning to set up a (throw-away) pull request to reflect any progress there…

**Comment by tisto** [comment]
@jensens I fully agree with you and share your concerns. The idea would be that we make plone.restapi an exception to the no-plone.api rule. I think we can safely assume that no Plone core package ever will rely on plone.restapi. plone.restapi is supposed to be the same facade to HTTP that plone.api is on the Python-level. If this is the case, the only thing we have to make sure is that plone.api never uses any plone.restapi code (something which is highly unlikely).

To be honest, right now I am not even sure if it makes much sense to integrate plone.restapi into the core at all. We are way more flexible when we keep the package and release cycle independent from Plone releases. We could ship with plone.restapi, but right now I do not see a big advantage (from a technical point of view).

Though, in any case, it would be helpful if the @plone/framework-team could discuss this matter at the next meeting. I will try to attend, but I can not promise anything right now. I always felt that fwt discussions are better if the person who proposes a change does not take part in the (initial) dicussion. :)

**Comment by davisagli** [comment]
plone.api is currently used by plone.restapi, and it seems to be working out

**Comment by sneridagh** [comment]
@davisagli but only in tests if I'm not mistaken. Although the desire was to have green light to use plone.api in the actual p.restapi code, so we can rid of a lot of duplicated code in p.restapi. 

However, this is a challenge that we should face in the years to come.
