### ISSUE TITLE
Add interfaces in content GET response

### ISSUE THREAD

**Issue by ebrehault** [plone/plone.restapi#242]
We need an `interfaces` attribute which will contain a list of strings corresponding to the interfaces implemented by the content object.

It is needed for view matching in client-side traversal.

Note: It might not be by default (a expand could work).

**Comment by erral** [comment]
This is also needed as we saw on the Angular training at PloneConf 2017, to get the global navigation correctly in contexts where a navigation root interface is added (subsites, ...)

**Comment by erral** [comment]
I have started a branch implementing an `@interfaces` endpoint which is expandable. See the pull-request for more information.
