### ISSUE TITLE
Getting rid of test content note on docs

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#252]
We currently have this not on our auto-generated json responses in our docs:

"These docs are generated by code tests, therefore you will see some ‘test’ contenttypes appear here."

This is unnecessary if we just do not add the test content types and objects on the test fixture level. This is bad practice anyways.

**Comment by lukasgraf** [comment]
@tisto agreed 👍 

I'm currently working on a follup-up PR to #248 where I convert the remaining hand-written example requests/responses to test-recorded ones, and clean up the `test_documentation.py` a bit. I'll drop that note with that as well.

But I'm waiting with that PR until the dust has settled regarding the sprint PRs, so I don't screw everyone over with merge conflicts 😉

**Comment by tisto** [comment]
I think this has been solved. @lukasgraf please re-open if you disagree.
