### ISSUE TITLE
Create Docker image with plone.restapi

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#277]
For JS developers it is hard to set up Python and run Buildout in order to get a backend they can work against. We should provide Docker images to make their lives easier.

**Comment by tisto** [comment]
@avoinea @svx I would like to provide developers with ready-to-use Plone docker images with plone.restapi. Ideally, we would auto-generate and upload the images as part of our CI process. Would you be up for a discussion how to accomplish that?

**Comment by avoinea** [comment]
@tisto @svx I didn't use plone.restapi, yet, but yes, we can have a chat on this topic ;)

**Comment by svx** [comment]
Sure ! Lets chat ! :)

**Comment by tisto** [comment]
@avoinea @svx cool! Do you guys have time today? I'm available online on IRC/gitter.

**Comment by tisto** [comment]
@avoinea @svx turns out this is harder than I thought. When I add the docker service Travis uses Ubuntu 16.04 with a somehow broken Python 2.7. Any chance you have a working Plone travis config with a docker service?

**Comment by avoinea** [comment]
:( nope!

**Comment by svx** [comment]
Nope, sorry ! :(

**Comment by svx** [comment]
@tisto Does is needs to be on Travis ? @gforcada wants to add nightly/weekly docker builds to jenkins, would that be a solution for plone.restapi, too ?

**Comment by gforcada** [comment]
@svx given some guidance I can try to do it myself, but it will take a bit of time as I've never done any docker image :-/

**Comment by tisto** [comment]
Done.
