### ISSUE TITLE
Workflow endpoint not returning all transitions

### ISSUE THREAD

**Issue by robgietema** [plone/plone.restapi#278]
Steps to reproduce:

Create a new Page as admin, workflow state is private.

Expected to see 'Submit for publication' and 'Publish' as transitions but only 'Submit for publication' is returned.

**Comment by sneridagh** [comment]
This is related to #178

**Comment by tisto** [comment]
Right. That dual authentication again. We really need to fix this. It confuses everybody who works with plone.restapi...

**Comment by tisto** [comment]
Will close this bug since admin is no valid plone.restapi user. @robgietema feel free to re-open if you disagree or if the problem persists with other users.
