### ISSUE TITLE
Workflow history should also return title

### ISSUE THREAD

**Issue by robgietema** [plone/plone.restapi#279]
The current workflow history items only show the id of the review_state. The title should be included also so it can be shown in the UI.

**Comment by tisto** [comment]
Absolutely. This is something we should fix asap.

**Comment by tisto** [comment]
@sneridagh I guess we will need this very soon in our project, we already have a frontend dev working on this ticket. Would you mind looking into this and create a ticket in our internal issue tracker to fix this?

**Comment by sneridagh** [comment]
@tisto done.
