### ISSUE TITLE
Undeclared dependency on Products.PasswordResetTool

### ISSUE THREAD

**Issue by tomgross** [plone/plone.restapi#293]
There is a undeclared dependency on Products.PasswordResetTool in plone.restapi 1.0a10.

Products.PasswordResetTool is gone in Plone 5.1

see plone.restapi-1.0a10-py2.7.egg/plone/restapi/services/users/add.py
from Products.PasswordResetTool.PasswordResetTool import ExpiredRequestError

**Comment by erral** [comment]
We are removing some other undeclared dependencies for Plone 4.3 at #292 we can handle this there too.

**Comment by tisto** [comment]
@tomgross thanks! I am wondering if there is a tool that could detect undeclared dependencies like that...

**Comment by lukasgraf** [comment]
@tisto [`z3c.dependencychecker`](https://github.com/reinout/z3c.dependencychecker) will report undeclared dependencies like that. It can result in some false positives though, so it's not necessarily suited to be wire up in a strict CI check, but I've found it to be very helpful indeed to run manually on occasion, e.g. before doing a release.

**Comment by tisto** [comment]
Fixes: 

Undeclared dep: https://github.com/plone/plone.restapi/pull/295
Dep check: https://github.com/plone/plone.restapi/pull/296

**Comment by tisto** [comment]
Plone 5.1 buildout and travis conf: https://github.com/plone/plone.restapi/pull/297

**Comment by tisto** [comment]
Fixed in https://github.com/plone/plone.restapi/pull/295
