### ISSUE TITLE
Improve error handling using Zope Exceptions (or create custom ones)

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#307]
I've started to stumble upon certain cases where I think that we could use better error handling using either existing Zope exceptions or create custom ones (if that makes any sense). This would help us to return proper error messages as well.

What do you think?
@tisto @buchi @lukasgraf @csenger

**Comment by davisagli** [comment]
Better error messages are always good, but I'll close this since it isn't specific enough to be actionable.
