### ISSUE TITLE
Deprecation Policy

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#317]
We need a proper deprecation policy for plone.restapi. I would like to have this in place even in alpha phase. The idea is that we always deprecate a component before finally removing it. Ideally, this would lead to a situation where you can be sure you can upgrade to the next version without breaking anything if no deprecation messages show up in your logs.

@jensens it would be great if you could share your findings with us during PLOG.

**Comment by jensens** [comment]
With help of the community, I already documented different deprecation methods here https://docs.plone.org/develop/styleguide/deprecation.html

I am here at PLOG, grab me out of what I am ever doing and I will try to help,

**Comment by tisto** [comment]
Thank you @jensens!

**Comment by tisto** [comment]
@jensens I added a deprecation message to the deprecated endpoints in plone.restapi. Though, since enabling deprecation messages in Plone is not the default I am concerned that people will not see those messages. Therefore I am thinking about writing an additional log message to the console if there is a request on a deprecated endpoint. If you have time, I'd like to hear your opinion on that.

**Comment by jensens** [comment]
Well, I would like to see all deprecation follow the Python way. I don't think it is a good idea to act differently here. 

We could change our defaults in a way that UnifedInstaller and all training/documentation switches deprecation messages on by default.

**Comment by tisto** [comment]
@jensens I agree that this is the desirable way and deprecation messages should be on by default. Though our main project right now has lots of legacy code, so enabling deprecation messages is not really an option for us right now. Still, I would really like being able to see if any front-end call is using deprecated calls. 

I am still considering to add additional logger messages, at least for the transition period (both our project and Plone itself).

**Comment by tisto** [comment]
@jensens do you know if it possible to enable deprecation messages for a single package? I am asking because I would like to just see plone.restapi deprecation messages in our setup for now. This would allow us to stick with the standard deprecation mechanism.

**Comment by jensens** [comment]
@tisto I never tried this. Since Deprecation Messages are a kind of [warnings](https://docs.python.org/2/library/warnings.html), the question is if the filter can be configured to show only warnings of a specific type for a specific package. I wildly guess this is possible with a custom ``warningsfilter``.

**Comment by tisto** [comment]
Establishing a deprecation policy is extremely hard when it comes to RESTful APIs. Most breaking changes are within the response of an endpoint. It is just impossible to notify an API consumer up front about changes. The backend has no idea how a consumer uses the current API. I will therefore close this issue now. This is something that we still need to solve on Plone core level.
