### ISSUE TITLE
Follow RFC 7396 on HTTP PATCH

### ISSUE THREAD

**Issue by Rotonen** [plone/plone.restapi#320]
The JSON merge patch [[1]](https://tools.ietf.org/html/rfc7396) is the strategy currently chosen for HTTP PATCH, but that would require the use of the `application/merge-patch+json` content type. With `application/json` one should expect a defined format of change descriptions (ie. `{"operation": "replace", "title": "My New Document Title"}` vs. `{"title": "My New Document Title"}`) [[2](https://tools.ietf.org/html/rfc5789)]

Fully adhering to this is thus a simple matter of tweaking and documenting the expected content type.

[1] https://tools.ietf.org/html/rfc7396
[2] https://tools.ietf.org/html/rfc5789

**Comment by davisagli** [comment]
As far as I'm aware, we're not using this merge patch strategy consistently. Each deserializer can implement a different strategy. And anyway, the RFC is only in proposed status.
