### ISSUE TITLE
Exposing API Version?

### ISSUE THREAD

**Issue by jensens** [plone/plone.restapi#328]
This is only a rough question/idea.

In a project, there was the question "if the Plone API supports 'versioning'" - whatever they understand by this term.
It turned out the other project partner uses WSO2 (https://en.wikipedia.org/wiki/WSO2) to talk to all external services. 

Anyway, WSO2 does some kind of API abstraction and supports different versions of the same API and so it needs (or would like to have) a version string of the plone.restapi version. Overall I think it is a good idea if plone.restapi broadcasts its version string somewhere, i.e. in headers or payload metadata. I don't know if plone.restapi does this by now (I can not find any version like string there) nor did I evaluate if there is some widely used standard around.

This is just a question: 
1) Do we have this feature?

if not:

2) Is the idea to broadcast the API version good? 
3) Does it have disadvantages? 

if we want it:

4) How would you implement it?

**Comment by tisto** [comment]
@jensens: here is the short version: 

http://plonerestapi.readthedocs.io/en/latest/conventions.html#versioning

I don't think exposing the API version makes a lot of sense for plone.restapi right now. If we do so, we should use the HTTP header and not the URL.

**Comment by tisto** [comment]
@jensens let me know if this answers you question. If this is the case we can close this issue.

**Comment by jensens** [comment]
Thanks, yes it answers my question. 
Because of the nature of traversable resources, exposing the API version in URL makes no sense, indeed.
Given that consumers of the plone.restapi expect to read some version string from somewhere it would at least not hurt to expose it in the HTTP header. 
OTOH it also adds expectations to the API we dont want to fullfil at this point. 

I close this issue now and may reopen it, but only if there are new/better reasons are brought up.
