### ISSUE TITLE
Comments API

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#329]
plone.app.discussion-based comments should be exposed via the API. I guess an expandable "comments" endpoint that can be embedded would be the best option. We have to come up with a data structure that reflects nested comments.

First task would be to write the documentation how the API should look like.

**Comment by prakharjoshi** [comment]
This is a rough idea of what these APIs may look like...

So we will store all the conversations for an object and each conversation can have multiple comments.

API to fetch all the conversations for an object ` /api/<obj>/conversations` 
To get specific conversation for an object `/api/<obj>/conversations/<id>`

  `/api/<obj>/conversations/<id>` will provide the list of all the comments for an conversation. with each comment as an retrievable item.

`/api/<obj>/conversations/<id>/comments/<id>`To retrieve a particular comment from an conversation. Here parent comment of each conversation will start with Id 0 and rest will follow the incremental behaviour.

This is just the initial idea for the APIs implementation. It needs a lot of improvements. @tisto ideas ?

**Comment by tisto** [comment]
@prakharjoshi thank you! I think you got the basic endpoints right. We do not have a static "/api" endpoint though. plone.restapi uses content negotiation on the original object URL. Next step would be to define the JSON format of the endpoint and make sure it works with our new expansion mechanism (see https://github.com/plone/plone.restapi/blob/414bdb0c2e86aa0ba2e195674d8bb5023b4980ec/docs/source/expansion.rst). Feel free to create a pull request with an rst document in docs/source/comments.rst where you outline the docs for this endpoint (just if you feel like it of course).

**Comment by tisto** [comment]
Finished and released with https://pypi.python.org/pypi/plone.restapi/1.0a16
