### ISSUE TITLE
Workflow comment and include contained items missing

### ISSUE THREAD

**Issue by robgietema** [plone/plone.restapi#333]
The current workflow transition api doesn't provide the option to specify a comment when doing a transition. Also you are not able to specify the transition should also apply to all contained items.

**Comment by buchi** [comment]
Providing a comment is already supported. You just have to provide it in the body. E.g.

```
POST /plone/front-page/@workflow/publish HTTP/1.1
Accept: application/json
Authorization: Basic YWRtaW46c2VjcmV0
Content-Type: application/json

{
    "comment": "Publishing the front page..."
}
```

Need to document that though.
