### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by robgietema** [plone/plone.restapi#337]
Most i18n should be handled on the frontend but fields like tiles of contenttypes etc should be returned correctly by the REST API. My suggestion is to use the "Accept-Language" header for this.

**Comment by tisto** [comment]
Using the "Accept-Language" header sounds like a sensible thing to do. So the idea would be that plone.restapi returns the translated titles when the "Accept-Language" header is properly set on all items that can be translated and falls back to English if the header is not set. cc @erral @sneridagh

**Comment by erral** [comment]
Plone already reads the "Accept-Language" header and returns all the relevant messages translated, so I would say that the only thing to do is to add the proper calls to Message Catalogs on the relevant endpoints, right?

**Comment by tisto** [comment]
Ok, cool. Then we just need to check where it makes sense to call the message catalog and replace those calls. Any takers?

**Comment by erral** [comment]
It looks like the Accept-Header is treated correctly, it gets translated to Zope's HTTP_ACCEPT_LANGUAGE header, but somehow it is not hooked into the language negotiator, because I need to explicitly add the target_language parameter to zope.i18n.translate method.

**Comment by erral** [comment]
Adding the proper context to the translate method works. I will prepare some tests about it.

**Comment by erral** [comment]
We are already translating the fti title in the `@types/Document` endpoint, so we only need to to the same on the plain `@types` call
