### ISSUE TITLE
Controlpanels Endpoint

### ISSUE THREAD

**Issue by jaroel** [plone/plone.restapi#342]
Support @controlpanels[/panelname].

**Comment by jaroel** [comment]
Some controlpanels have custom error handling: https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/controlpanel/browser/language.py#L27

**Comment by jaroel** [comment]
Maybe just use named IControlpanel[Serializer/Deserializer] adapters?

class IControlpanelDeserializer(IDeserializeFromJson):
    def get_schema():
        pass

@implementor(IControlpanelDeserializer)
@adapter(IRegistry)
class EditingControlpanelDeserializer(object):
    pass

**Comment by jaroel** [comment]
class Get(Service):
    def reply(self):
        return getAdapters

**Comment by tisto** [comment]
https://github.com/plone/plone.restapi/pull/339
