### ISSUE TITLE
Create user throwing exception 'Property 'username' is not allowed'

### ISSUE THREAD

**Issue by UmeshRajani** [plone/plone.restapi#352]
Trying this example given in doc: http://plonerestapi.readthedocs.io/en/latest/users.html#create-user
```
{
    "description": "Professor of Linguistics",
    "email": "noam.chomsky@example.com",
    "fullname": "Noam Avram Chomsky",
    "home_page": "web.mit.edu/chomsky",
    "location": "Cambridge, MA",
    "password": "colorlessgreenideas",
    "username": "noamchomsky"
}
```
This throws exception, given below
```
{
  "error": {
    "errors": [
      {
        "field": "username",
        "message": "Property 'username' is not allowed."
      }
    ],
    "message": "Error in fields. Property 'username' is not allowed.",
    "type": "WrongParameterError"
  }
}
```

While all other user REST API works fine, except this one
If I remove 'username' from json request body, it creates username having value as email

**Comment by tisto** [comment]
@UmeshRajani thank you for your bug report. Could you please let us know if you are on a vanilla Plone site (which version?) and especially if you have email-as-login configured. The required fields for the users depend on that setting.

**Comment by UmeshRajani** [comment]
Plone 4.3.10 (4313)
CMF 2.2.9
Zope 2.13.24
Python 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
PIL 3.2.0 (Pillow)
Non-vanilla 

But now I got it from your hint
Security option 'Use email address as login name'  was checked, I unchecked it and tried then it works.

**Comment by UmeshRajani** [comment]
But the problem is, here we will use mail only for for the login on plone, so anyway 'Use email address as login name' remain checked only so if we create user then I will be issue again,

So basically when we want to create user then first we have to uncheck  'Use email address as login name'
Then again we have to check this option login with mail after user creation.

As per my understanding, 'username' should be there in REST whether this 'Use email address as login name' is enabled or not

**Comment by jaroel** [comment]
The field "username" is not allowed when email login is enabled. There is no need to do the enable/disable workaround.

I've added this to the documentation!
