### ISSUE TITLE
Endpoint for Dexterity Content Types Editing

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#355]
We need an endpoint that allows to add/edit/delete a dexterity content type schema. If we want to be able to share JS code between a possible JS-PloneFormGen implementation, we might want to rely on JSON-Schema for this. The question would be if this is sufficient for both use cases.

@ebrehault @robgietema @sneridagh @jaroel opinions?

**Comment by ebrehault** [comment]
JSON Schema (+ our specific extensions regarding form aspects like fieldset, widgets, etc.) should be fine for the schema itself, so it should work for the PFG use case, but it cannot cover the content type definition needs (we will miss the associated GS types/mytype.xml infos).

**Comment by avoinea** [comment]
@tisto Now that we also have `/@controlpanels/dexterity-types/:type-id` we have 2 options here.

We either extend this one and implement `/@controlpanels/dexterity-types/:type-id/metadata` (kind of hard to do and counter-intuitive) or finish the `@types/{type-id}` one, IMHO **more clean and generic**.

Thus, we'll have:

Verb | URL | Action
-- | -- | --
GET | /@types/Document | Already implemented (we may need to add some more info, like: field coming from a behavior).
PATCH | /@types/Document | Update defaults
PUT | /@types/Document | Re-order fields, move to another fieldset
-- | -- | --
POST | /@types/Document | Creates a new `field/fieldset`
GET | /folder/Document/{:id} | Get field/fieldset info
DELETE | /folder/Document/{:id} | Remove field/fieldset
PATCH | /@types/Document/{:id} | Update field settings

**Comment by avoinea** [comment]
@tisto I think this can be closed and add a more specific and updated ticket for PloneFormGen, if needed.
