### ISSUE TITLE
[RFC] Sync/double-check plone.api and plone.restapi

### ISSUE THREAD

**Issue by gforcada** [plone/plone.restapi#356]
*As restapi is already supposed to be in sync with guillotina, now also with plone.api* 😄 

That's actually not my idea but @MrTango: https://github.com/plone/plone.api/pull/370#issuecomment-300767549

I guess that here, the synchronicity that we should aim is mostly at vocabulary, so that we name things in both API's consistently.

**Opinions?**

**Comment by tisto** [comment]
I appreciate your aim for keeping names in sync. 

Though, I would like to point out that it is a common misconception that plone.restapi and plone.api are related in any way. plone.restapi is a RESTful API (resources + HTTP verbs), not a RPC-like API like WSAPI4Plone (single API endpoint with multiple methods). 

We have a different architectural style, different methods, different resources and imports, different naming conventions (snake vs. dash) and no 1:1 mapping (except some very rare exceptions, Maik mentioned one of them).

We should, of course, try to keep the method names in sync, if they do the exact same thing and exist in plone.restapi. This is what we tried so far. I do not think we can automate that in any way though.

Also, keep in mind that we currently do not use plone.api in plone.restapi. With https://github.com/plone/plone.restapi/issues/298 I stopped any efforts of moving plone.restapi into the core, including moving to use plone.api. I just don't have time right now to fix issues in Plone core myself.

**Comment by tisto** [comment]
@gforcada are you ok with closing this issue? As said, I agree with your intention but it won't help to keep this ticket open. :)

**Comment by gforcada** [comment]
Sure, it was @MrTango idea actually, if we want an actionable task, we could go over plone.api naming and check if the usage is consistent with the naming here at restapi and fix the names.

If no one feels up for that task, we can close and reopen it later on when the issue arises again.
