### ISSUE TITLE
CSRF handling in angular frontends

### ISSUE THREAD

**Issue by saily** [plone/plone.restapi#36]
After short discussion on #plone i want to raise this up as an issue here. Currently my post-requests to backend fail after upgrading to `plone.protect >= 3.0` because i do not ship a token within the request. 

How do you guys handle this?

**Comment by buchi** [comment]
We simply disable CSRF protection for API requests that write to the database. Because API requests require a specific HTTP header (`Accept: application/json`) we should be safe from CSRF attacks. It shouldn't be possible to set that header in a link.
