### ISSUE TITLE
heroku created link gives following error to have a live preview 

### ISSUE THREAD

**Issue by Viswasai-M** [plone/plone.restapi#367]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

https://intense-falls-67581.herokuapp.com/

**Comment by tisto** [comment]
@Viswasai-M thank you for reporting this. We are aware that the heroku link is broken. We are working on a new demo instance. In the meantime you can use http://plonedemo.kitconcept.com/ which has plone.restapi installed.
