### ISSUE TITLE
sitemap.xml.gz endpoint

### ISSUE THREAD

**Issue by ebrehault** [plone/plone.restapi#372]
When we use Plone as a backend for a front site, we can indicate in our local robots.txt the path to the sitemap.xml.gz provided by Plone.
But obviously, the URLs contained in this file use the backend URL, not the front one.
We need an endpoint which would take a domain as parameter and return a sitemap.xml.gs where URLs use this domain.

**Comment by tisto** [comment]
@sneridagh how did we solve that problem for kitconcept.com/blog?

**Comment by davisagli** [comment]
sitemap.xml.gz was implemented in volto
