### ISSUE TITLE
Support for deserializing review_state

### ISSUE THREAD

**Issue by Shriyanshagro** [plone/plone.restapi#374]
Review_state are not deserialized for any content type.
 [bug reported in plone.importexport](https://github.com/Shriyanshagro/plone.importexport/issues/4)

**Comment by tisto** [comment]
@Shriyanshagro please provide us with a more specific and detailed error report. We need a curl example call (feel free to use plonedemo.kitconcept.com) and the current response and the expected response.

**Comment by Shriyanshagro** [comment]
After doing a serialising, and then deserializing to another site, I noticed that -

Wrokflow state was not kept
_Suggested solution_: check for the review_state field as well in data and modify it as well.

**Comment by Shriyanshagro** [comment]
As due to lack of response from plone.restapi. I myself has [resolved](https://github.com/Shriyanshagro/plone.importexport/commit/2f533c30d63ae98544bf2942decdc1c13349cea0#diff-d5a05274b32a6ba9490e5ea40b72bf71R155) this issue to support my [addon](https://github.com/Shriyanshagro/plone.importexport/). This issue was originally raised [here](https://github.com/Shriyanshagro/plone.importexport/issues/4)

**Comment by tisto** [comment]
@Shriyanshagro I am sorry but you can not expect developers to fix issues that are not properly reported. You need to provide at least a curl/wget example with the actual and expected output. If you just ignore my advice, there is nothing we can do here...

**Comment by Shriyanshagro** [comment]
No worry, I already found a fix for this.
You may want to look into other potential issue #396, which I have raised earlier.

**Comment by loechel** [comment]
@tisto just for the record, it was an underlying issue in plone.app.contentlisting that cause some problem in plone.app.contentlisting that I solved in https://github.com/plone/plone.app.contentlisting/pull/22 if the content class did not have an associated workflow, e.g. Files and Images
