### ISSUE TITLE
Support for serializing review-state

### ISSUE THREAD

**Issue by Shriyanshagro** [plone/plone.restapi#376]
If the related_item object/file/content doesn't have a review_state, then serializer throws a WorkflowException.
[Details and Steps to reproduce the error](https://github.com/Shriyanshagro/plone.importexport/issues/1)

While it works well for the related_item with defined review state.

Solution:
get the review state of an object, only if it has it, else pass.

**Comment by tisto** [comment]
@Shriyanshagro please provide us with a more specific and detailed error report. We need a curl example call (feel free to use plonedemo.kitconcept.com) and the current response and the expected response.

**Comment by Shriyanshagro** [comment]
Steps to reproduce the error:

1. Add a file object (Using any type of file)
2. Add a page, and from the "Categorization" tab, go to the "Related Items" and choose the file added in step 1
3. When trying to serialize the site, you get the WorkflowException.

This is caused by the fact that, the particular file does not have a workflow, while it executes well if review_state of the file is defined earlier.

_Suggested solution_: A check on the key before retrieving review_state of an object.

`Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.importexport.browser.view, line 323, in export
  Module plone.importexport.browser.view, line 236, in serialize
  Module plone.importexport.browser.view, line 236, in serialize
  Module plone.importexport.browser.view, line 218, in serialize
  Module plone.restapi.serializer.dxcontent, line 77, in __call__
  Module plone.restapi.serializer.dxfields, line 24, in __call__
  Module plone.restapi.serializer.converters, line 34, in json_compatible
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.converters, line 60, in list_converter
  Module plone.restapi.serializer.converters, line 34, in json_compatible
  Module zope.component.hookable, line 33, in __call__
  Module zope.component.hooks, line 104, in adapter_hook
  Module plone.restapi.serializer.relationfield, line 17, in relationvalue_converter
  Module plone.restapi.serializer.summary, line 31, in __call__
  Module plone.app.contentlisting.realobject, line 70, in review_state
  Module Products.CMFCore.WorkflowTool, line 263, in getInfoFor
WorkflowException: No workflow provides '${name}' information.`

**Comment by arsenico13** [comment]
I hit the same problem.
I looked into the PR list but I didn't see anything regarding this issue. I might write one.
