### ISSUE TITLE
Searching for IDexterityContainer objects returns the wrong @id

### ISSUE THREAD

**Issue by david-batranu** [plone/plone.restapi#381]
When `fullobjects` is used, the `@id` returned is that of the query, instead of the actual object id. For example:

`curl -i -H "Accept: application/json" "http://localhost:8080/Plone/@search?portal_type=DXContainer&fullobjects" --user admin:admin`

will return something similar to:

```
{
  "@id": "http://localhost:8080/Plone/@search?portal_type=DXContainer",
  "items": [
    {
      "@id": "http://localhost:8080/Plone/@search?portal_type=DXContainer",
      "@type": "DXContainer",
      "UID": "ab035e389a1a444f8d38769c8335374b",
      "created": "2017-07-11T10:45:05+00:00",
      "id": "item-1",
      ...
    },
  ],
  "items_total": 1
}
```
instead of 

```
{
  "@id": "http://localhost:8080/Plone/@search?portal_type=DXContainer",
  "items": [
    {
      "@id": "http://localhost:8080/Plone/item-1",
      "@type": "DXContainer",
      "UID": "ab035e389a1a444f8d38769c8335374b",
      "created": "2017-07-11T10:45:05+00:00",
      "id": "item-1",      
      ...
    },
  ],
  "items_total": 1
}
```

`"@id": "http://localhost:8080/Plone/@search?portal_type=DXContainer",` instead of
`"@id": "http://localhost:8080/Plone/item-1",`

I believe the issue is in the [dxcontent serializer](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/dxcontent.py#L127).

**Comment by tisto** [comment]
@david-batranu thank you for your detailed bug report!
