### ISSUE TITLE
Checkout of plone.restapi fails 

### ISSUE THREAD

**Issue by riker1** [plone/plone.restapi#393]
mr.developer dies on trying to get checkout of plone.restapi. 

replacing ssh URL to https yields successful checkout

change line 32 from git git@github.com:plone/plone.restapi.git to:

[sources]
plone.restapi = git https://github.com/plone/plone.restapi.git

**Comment by tisto** [comment]
@riker1 this has nothing to do with plone.restapi. You are not using mr.developer properly in your project. Please check the mr.developer docs. This is how your sources section should look like:

```
[sources]
plone.restapi = git git://github.com/plone/plone.restapi.git pushurl=git@github.com:plone/plone.restapi.git branch=master
```
