### ISSUE TITLE
ComponentLookupError on instance start

### ISSUE THREAD

**Issue by szakitibi** [plone/plone.restapi#395]
I created a own Plone 4.3.x package with _plone.restapi_ as dependency, did not use the out of box buildouts from the repo.
The buildout went O.K., but when I started the instance, I got the following error:

```
...
    raise ComponentLookupError(interface, name)
zope.configuration.config.ConfigurationExecutionError: <class 'zope.component.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'cmf.ModifyPortalContent')
  in:
  File "/home/ubuntu/.buildout/eggs/plone.restapi-1.0a20-py2.7.egg/plone/restapi/services/content/configure.zcml", line 20.2-25.6
    <plone:service
      method="PATCH"
      for="Products.CMFPlone.interfaces.IPloneSiteRoot"
      factory=".update.ContentPatch"
      permission="cmf.ModifyPortalContent"
      />
```

Seems like the _cmf.ModifyPortalContent_ permission is missing. Including _Products.CMFCore_ package in the _plone/restapi/services/content/configure.zcml_ did fix the issue for me.
```
<configure
    xmlns="http://namespaces.zope.org/zope"
    xmlns:plone="http://namespaces.plone.org/plone"
    xmlns:zcml="http://namespaces.zope.org/zcml">

  <include package="Products.CMFCore" />

  <plone:service
    method="GET"
    for="Products.CMFPlone.interfaces.IPloneSiteRoot"
    factory=".get.ContentGet"
    permission="zope2.View"
    />
  ...
```

**Comment by tisto** [comment]
@szakitibi thanks for the bugreport. Can you please provide a minimal buildout.cfg to reproduce the problem?

**Comment by szakitibi** [comment]
Here's the basic package what I used for my buildout [development-4.cfg](https://github.com/szakitibi/basic.rest/blob/master/development-4.cfg).

**Comment by lukasgraf** [comment]
@szakitibi I can reproduce the issue with the buildout you provided (easy enough since you're using `ftw-buildouts` 😉 )

I believe your suggested fix is the correct approach - by using permissions, the `plone.restapi` ZCML has a dependency on `Products.CMFCore`'s `permissions.zcml`, and should therefore declare that dependency by loading the ZCML explicitly. I'll create a pull-request shortly to address this.
