### ISSUE TITLE
Use Dexterity Schema and Behaviors to get the Object Schema.

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#4]
Instead of iterating over all possible interfaces, just iterate over the dexterity type schema and all behaviors.

**Comment by davisagli** [comment]
Probably use this: https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/utils.py#L69

**Comment by tisto** [comment]
I created a branch that uses the plone.dexterity helper functions to look up the schema + the behaviors:

https://github.com/plone/plone.restapi/commit/291f8c424f7058dcaab95206d49ec14fa4035a76

It somehow seems title, description, dates, etc. are not looked up properly.
