### ISSUE TITLE
Building docs on Plone 5

### ISSUE THREAD

**Issue by jaroel** [plone/plone.restapi#400]
We currently build the plone.restapi docs on Plone 4 - for historical reasons I've been told.
I'd propose to build the plone.restapi docs on Plone 5 instead, as newer features (like the controlpanels endpoint) may be Plone 5 only.

**Comment by tisto** [comment]
@jaroel give us a few weeks. Then we will be fully on Plone 5 with our internal project. :)

**Comment by jaroel** [comment]
\o/

**Comment by tisto** [comment]
We should re-consider moving to Plone 5.0 to build the docs now, especially with new features that work for Plone 5 only. @buchi @lukasgraf would you be ok with that?

**Comment by lukasgraf** [comment]
@tisto 👍 from me

**Comment by buchi** [comment]
Sure. 👍

**Comment by tisto** [comment]
PR WIP: https://github.com/plone/plone.restapi/pull/474

**Comment by tisto** [comment]
Done.
