### ISSUE TITLE
Feature request: Add Sitemap service

### ISSUE THREAD

**Issue by ericof** [plone/plone.restapi#407]
Expose the sitemap contents at /@sitemap endpoint.

**Comment by ebrehault** [comment]
I guess you mean this endpoint should return the sitemap as a JSON, right? (because I suggested a sitemap endpoint to return the sitemap.xml.gz https://github.com/plone/plone.restapi/issues/372, so we need to pick accurate names for both).

That would definitely be useful, but maybe it could be extended to a more global need: navigation trees.
A sitemap is a navigation tree starting from the site root and having an infinite depth.

So maybe `@navigation-tree` (having 2 parameters: root and depth)?

**Comment by ericof** [comment]
That sounds like a better approach, I will improve this, after my talk.

**Comment by ericof** [comment]
@ebrehault: In here, what is the expected response we want do return?
i.e.: 
```json
{
  "Creator": "test_user_1_",
  "Description": "",
  "Title": "Some Folder",
  "UID": "2cfa412b4739468faa94e4896f65a490",
  "absolute_url": "http://localhost:55001/plone/folder",
  "children": [
    {
      "Creator": "test_user_1_",
      "Description": "",
      "Title": "A document",
      "UID": "83329c5eb0464c07866d6972c66ea31b",
      "_pruneSubtree": true,
      "absolute_url": "http://localhost:55001/plone/folder/doc1",
      "children": [],
      "creation_date": "2017-10-30T14:17:14+00:00",
      "currentItem": false,
      "currentParent": false,
      "depth": 2,
      "getRemoteUrl": "",
      "getURL": "http://localhost:55001/plone/folder/doc1",
      "id": "doc1",
      "link_remote": "",
      "no_display": false,
      "normalized_id": "doc1",
      "normalized_portal_type": "document",
      "normalized_review_state": "private",
      "path": "/plone/folder/doc1",
      "portal_type": "Document",
      "review_state": "private",
      "show_children": false,
      "useRemoteUrl": false
    }
  ],
  "creation_date": "2017-10-30T14:17:14+00:00",
  "currentItem": false,
  "currentParent": false,
  "depth": 1,
  "getRemoteUrl": "",
  "getURL": "http://localhost:55001/plone/folder",
  "id": "folder",
  "link_remote": "",
  "no_display": false,
  "normalized_id": "folder",
  "normalized_portal_type": "folder",
  "normalized_review_state": "private",
  "path": "/plone/folder",
  "portal_type": "Folder",
  "review_state": "private",
  "show_children": true,
  "useRemoteUrl": false
}
```
would be the equivalent to the Plone navigation tree.
Should we sanitise this or return as it is?

**Comment by ebrehault** [comment]
I guess we expect the same kind of response as a the /@search endpoint https://github.com/plone/plone.restapi/blob/master/docs/source/_json/search.resp but instead of a flat list, we would get a tree structure.

**Comment by tisto** [comment]
We auto-generate a sitemap in Volto already. So I guess we can close that issue.
