### ISSUE TITLE
AT: DateTimeField deserialization odd

### ISSUE THREAD

**Issue by jensens** [plone/plone.restapi#417]
A customer of us uses collective.jsonify to grab data from very old Plone sites. 
Then he imports it using plone.restapi into a Plone 4.3.

This fails to some point for Archetypes DateTime fields.

Now he has an own event content type with DateTimeField like so:

```
    atapi.DateTimeField(
        'startDate',
        widget=atapi.CalendarWidget(
            description='',
            label=_(u'label_event_start', default=u'Event starts'),
            visible={"edit": "invisible", "view": "visible"},
        ),
        accessor='start',
        languageIndependent=False,
    ),
```

When he call the restapi with ....

```
{
  '@type':'MyEvent',
  duration:'',
  endDate:'2014-10-16T01:58:00+02:00',
  startDate:'2014-10-01T01:58:00+02:00',
  title:'Nikolaus Gansterer: When thought becomes matter and matter turns into thought '
}
```

then he gets a traceback telling me the value is not a `DateTime`` but a unicode:

```
Error while retrieving Plone Content: StatusCodeError: 500 - 
{"message":"'unicode' object has no attribute 'strftime'",
"traceback":["File \"/var... File \"/var/www/theming/eggs/Products.ZCatalog-3.0.2-py2.7.egg/Products/ZCatalog/Catalog.py\", 
line 415, in recordify","    attr = attr()","","  File \"/var/www/theming/noeku-kunstraum15/src/noeku.event/noeku/event/content/event.py\",
line 75, in end_formatted","    return noeku_formatted_date(self,self.end(),1)","","  File \"/var/www/theming/noeku-kunstraum15/src/noeku.event/noeku/event/content/utils.py\", 
line 78, in noeku_formatted_date","    format_date = date.strftime('%w|%d|%m|%Y|%-I|%I|%H|%M')"],"type":"AttributeError"}
```

Now I found this test expecting DateTime deserialization resulting in unicode strings.

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/tests/test_atfield_deserializer.py#L59-L63

This does not make much sense to me and looks like a bug. The stored result should be an old style ``DateTime``.

What do you think?

**Comment by tisto** [comment]
Off the top of my head, I'd say the API should accept anything that looks remotely like a string/DateTime. Following the robustness principle: "Be conservative in what you do, be liberal in what you accept from others". 

@buchi might be able to shed some light into this though.

**Comment by buchi** [comment]
@jensens The DateTimeField setter already implements a conversion from string to DateTime. See https://github.com/plone/Products.Archetypes/blob/master/Products/Archetypes/Field.py#L1609. Thus I decided to not implement another one in plone.restapi and just pass the datetime string to the setter. This seems to work for default AT content types. Not sure why it doesn't work for your custom content type.
