### ISSUE TITLE
Question about iterating dexterity fields

### ISSUE THREAD

**Issue by jone** [plone/plone.restapi#42]
I'm currently changing the serialization as discussed in #38.

While looking at the current implementation I was wondering why iterating over dexterity fields is implemented that way.
See [`get_object_schema`](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/utils.py#L7-L23):
```python
def get_object_schema(obj):

    # Iterate over all interfaces that are provided by the object and filter
    # out all attributes that start with '_' or 'manage'.
    for iface in providedBy(obj).flattened():
        for name, field in getFields(iface).items():
            no_underscore_method = not name.startswith('_')
            no_manage_method = not name.startswith('manage')
            if no_underscore_method and no_manage_method:
                yield name, field

    # Iterate over all behaviors that are assigned to the object.
    assignable = IBehaviorAssignable(obj, None)
    if assignable:
        for behavior in assignable.enumerateBehaviors():
            for name, field in getFields(behavior.interface).items():
                yield name, field
```

I would have used [`plone.app.dexterity.utils.iterSchemata`](https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/utils.py#L69-L77) with `zope.schema.getFieldsInOrder` (or `zope.schema.getFields`).

@tisto what is the advantage of this approach compared to using the dexterity utils `iterSchemata` ?

**Comment by lukasgraf** [comment]
There is an existing discussion about this point in #4 - seems that there were some issues with looking up some fields when using `iterSchemata()`.

**Comment by tisto** [comment]
@jone I tried to refactor my code to use plone.app.dexterity.utils.iterSchema. Though, it broke my tests and it did not work as I expected. Would be nice if we could re-use that.

**Comment by jone** [comment]
Ok then, I've swiched to `iterSchemata` in my branch (#39) at 432ee38b3d68195b2c362081647f674d44d368f3 .
Looks good to me: the non-field attributes (`icon`, `meta_type`, `isPrincipiaFolderish`, ..) got dropped, but for me that is correct since those are not fields but internal attributes.
