### ISSUE TITLE
IRichTextValue serializer uses value.output instead of value.output_relative_to

### ISSUE THREAD

**Issue by jaroel** [plone/plone.restapi#424]
See https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/converters.py#L139

Also see https://github.com/plone/plone.app.textfield/issues/24

**Comment by tisto** [comment]
@jaroel that sounds like a possible breaking change that we have to fix before moving into the beta stage. What do you think?

**Comment by jaroel** [comment]
@tisto It might break stuff that, on a non-root context, depends on .output being rendered using the site root.
I cannot imagine something like that, unless someone used a ITransform that only works with ISiteRoot.

I'm not against fixing this before moving to beta. That's what alphas are for.
