### ISSUE TITLE
remove append_json_to_links ?

### ISSUE THREAD

**Issue by jone** [plone/plone.restapi#44]
The [``append_json_to_links``](https://github.com/plone/plone.restapi/blob/e824b9479b5e74dfb362146dd027168ff17f8a9b/src/plone/restapi/utils.py#L26) utils function seems not to be used at all.
Can we remove it?

**Comment by tisto** [comment]
This function was used to make it easier to allow users to navigate "through the API" in the browser. The idea is that if you append "format=json" (or "@@json") to your URL you can just browse the URL by clicking the links in your browser, without the need to create a dedicated API browser. I would like to keep or re-add the functionality.

**Comment by marcyang001** [comment]
Heroku only works well in Firefox. Can we also make it work well in Chrome as well?
