### ISSUE TITLE
Impossible to retrieve private images and files from standard GET contents using the token auth

### ISSUE THREAD

**Issue by sneridagh** [plone/plone.restapi#452]
Given an standard GET content from a file or image, it returns a `download` property with the URL of the API server e.g.:
```
content-type: "image/jpeg",
"download": "https://server/the-image/@@images/image",
...
```
but accessing to the image by the browser itself throws a 401, since the resource should be accessed with the token header. You can workarround this by making the request via JS, but it feels highly cumbersome.

@buchi what do you think?

/cc @jaroel @tisto

**Comment by jaroel** [comment]
Also see #148

**Comment by tisto** [comment]
Ok, let's re-open #148 and close this one. We will try to explore the react proxy option for our project.
