### ISSUE TITLE
Should we expose path aliases on the response?

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.restapi#464]
I would like to know if it's a good idea to expose the path aliases managed by plone.app.redirector:

```pycon
>>> obj = portal['bar']
>>> from zope.component import getUtility
>>> from plone.app.redirector.interfaces import IRedirectionStorage
>>> storage = getUtility(IRedirectionStorage)
>>> storage.redirects('/'.join(obj.getPhysicalPath()))
['/Plone/baz', '/Plone/foo']
```

if so, what would be a good name? `@aliases`?

**Comment by tisto** [comment]
Good point and good question. So if we would expose that information, it would mean that the frontend will handle the redirect itself, correct? Would it be possible that we do not expose that information and that the backend just handles the redirect via HTTP?

I think we have to answer the question on which level we plan to handle the problem before we can move on to discuss implementation details.

What do you think @robgietema @ebrehault @sneridagh @lukasgraf @buchi?

**Comment by erral** [comment]
This could be handled in plone.rest where the 404 response is created. See https://github.com/plone/plone.rest/issues/60

**Comment by buchi** [comment]
What's you goal by exposing path aliases? Do you want to build a frontend for managing redirects like Products.RedirectionTool or do you want to handle redirects in the frontend? For the latter the backend should return 301 responses with a Location header.
For managing redirects a dedicated endpoint would make sense. I would rather call it `@redirects`. And I would avoid physical paths. Should be paths relative to the Plone site.

**Comment by hvelarde** [comment]
@buchi in fact, I have no use case; I was just playing around plone.restapi and noticed that we're not exposing this information; after reading your comment I think it may make sense in case somebody wants to build a frontend for managing the redirects.

right now I have no time for implementing this, but I want to keep a reference to this PR I made today as it can serve for a future implementation (we only need to remove the site name from the physical path):

https://github.com/collective/collective.jsonify/pull/31/files

**Comment by tisto** [comment]
Closing the issue. Nothing we can really do right now if we don't have a use case.
