### ISSUE TITLE
@search endpoints fails when searching with fullobjects=True parameter in a site with Archetypes content

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#481]
the "include_items" parameter was added to Dexterity object serializer, both for plain items and for folderish ones:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/dxcontent.py#L45
https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/dxcontent.py#L113

This was not the case in Archetypes, where only was added to folderish items:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/atcontent.py#L35
https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/atcontent.py#L89

This breaks ~Archetypes Collection~ search results serializer when calling with `?fullobjects`, because it calls the serializer with the include_items parameter and it fails with an exception:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/serializer/catalog.py#L88

```2018-01-24T08:57:21 ERROR Zope.SiteErrorLog 1516780641.880.499275435646 https://www.eibar.eus/eu/@search
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 23, in __call__
  Module plone.restapi.services, line 19, in render
  Module plone.restapi.services.search.get, line 12, in reply
  Module plone.restapi.search.handler, line 65, in search
  Module plone.restapi.serializer.catalog, line 88, in __call__
TypeError: __call__() got an unexpected keyword argument 'include_items'
```

I will try to provide a failing test and a fix in a pull-request.

**Comment by erral** [comment]
Example in a live site:

Plone 4.3.x with Archetypes:

- https://www.eibar.eus/eu/@search?portal_type=News+Item :ok: 
- https://www.eibar.eus/eu/@search?portal_type=News+Item&fullobjects=True :x: 

Plone 5.0.x with Dexterity:

- https://www.kulturaz.eus/@search?portal_type=News+Item :ok: 
- https://www.kulturaz.eus/@search?portal_type=News+Item&fullobjects=True :ok:

**Comment by mjmare** [comment]
Same problem here with Plone 5.1rc2 + plone.restapi 1.1.0
