### ISSUE TITLE
No installation instructions in documentation

### ISSUE THREAD

**Issue by ajayns** [plone/plone.restapi#486]
The readme.md and the documentation have provided no information provided on setting up Plone with buildout. This maybe confusing for beginners as they don't have any idea on how to get started and install Plone locally with restapi.

I feel this needs to be mentioned in the documentation.

Rough sketch of what I feel needs to be added:
Installation:
checkout https://github.com/plone/plone.restapi
set up a Python virtualenv
python bootstrap.py
bin/buildout -Nv -c plone-5.0.x.cfg

Running an instance of Plone:
./bin/instance fg one

**Comment by ajayns** [comment]
@jaroel @tisto @kakshay21 Any insights?

**Comment by tisto** [comment]
@ajayns sounds good. I'd be more than happy to review a pull request. The postman documentation section also needs an update, as you mentioned on community.plone.org.

**Comment by kakshay21** [comment]
@ajayns  I was planning to add this and the consistency of documentation in the same branch.
But no problem. I haven't started that part yet. You can work on it!

**Comment by davisagli** [comment]
There are several options for how to install, currently documented at https://6.dev-docs.plone.org/install/index.html
