### ISSUE TITLE
Basic Newman tests for Plone rest APIs

### ISSUE THREAD

**Issue by prakharjoshi** [plone/plone.restapi#489]
As now the resp APIs are stable and are out in production, we should also start testing rest APIs with Newman. Ideas? @tisto

**Comment by gforcada** [comment]
@prakharjoshi this tag that you used ``03 type: feature (plip)`` is meant for Plone wide big changes, see https://docs.plone.org/develop/coredev/docs/plips.html you probably wanted the ``04 type: enhancement`` ?

**Comment by prakharjoshi** [comment]
@gforcada Thanks for correcting me there. I have updated the label on the issue.

**Comment by tisto** [comment]
@prakharjoshi absolutely! Would you be interested in looking into this? It would also be great to reach out to the postman folks and ask if they offer an Open Source plan that would allow us to publish the plone.restapi API specs.

**Comment by prakharjoshi** [comment]
@tisto Definitely I will look into this and start creating a collection for the Plone rest APIs.
