### ISSUE TITLE
When is the @ prefix is used for fields in the output?

### ISSUE THREAD

**Issue by jensens** [plone/plone.restapi#491]
It seems to me, that serialized keys that are *not* fields from the main-schema or the behaviors are unprefixed, while other information (like `@type`, `@id`, `@components` is prefixed with an `@`.

Just that this is not consistent: `parent` is not prefixed. What is the rule here?

Looking at https://plonerestapi.readthedocs.io/en/latest/serialization.html I can not find any hint.

**Comment by tisto** [comment]
@jensens you are correct. @id and @type come from JSON LD, we might want to mention that somewhere in the docs. 

Maybe we should rename "@components" to just "components" to be consistent with the JSON LD standard. Though, my personal feeling is that we have to refactor the way we handle expansion anyways at some point. There is no way we can use our current expansion mechanism to work well with reference fields for instance.
