### ISSUE TITLE
Endpoint or parameter for setting the UID

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#497]
If you are using plone.restapi for migrations then it is necessary to preserve the original UID (because they are used for references or links within rich text.

The best solution is likely to extract the `uid` from a POST request. However a security with Modify Portal Content permission should not be able to mess up the original UID. Instead setting the UID should require higher rights like Manage Portal.

**Comment by tisto** [comment]
@zopyx +1. I think plone.restapi should set the UID on POST and PATCH requests for migrations (and check for the "Manage portal" permission. Shouldn't be hard to implement...

**Comment by tisto** [comment]
FYI: Workaround if anybody is looking for it: https://community.plone.org/t/how-to-retain-uuid-when-migrating-content-type/6913

**Comment by michelececcacci** [comment]
is this still open?

**Comment by ericof** [comment]
Fixed on #1173
