### ISSUE TITLE
WARNING plone.namedfile.utils unpack requires a string argument of length 6

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#498]
plone.restapi 1.1.0 emits sometimes the following warning 
``
2018-02-16 15:12:29 WARNING plone.namedfile.utils unpack requires a string argument of length 6
```

**Comment by tisto** [comment]
@zopyx how can we reproduce that error? Are you sure this comes from plone.restapi?

**Comment by zopyx** [comment]
Not sure. I have not seen this issues again with Plone 5.2RC3 and plone.restapi 4.0.0. Possibly obsolete.

**Comment by tisto** [comment]
Closing. Feel free to re-open when it pops up again.
