### ISSUE TITLE
Undeclared dependency on plone.app.contenttypes

### ISSUE THREAD

**Issue by lukasgraf** [plone/plone.restapi#51]
The [import of `ICollection` in the serializer code](https://github.com/plone/plone.restapi/blob/17b585a4c76704a0a6f89524f8a87792c519ddfe/src/plone/restapi/serializer/__init__.py#L8) introduced in #39 adds a new, implicit dependency on `plone.app.contenttypes`.

Until now, `plone.app.contenttypes` is [only a test dependency](https://github.com/plone/plone.restapi/blob/17b585a4c76704a0a6f89524f8a87792c519ddfe/setup.py#L46-L47), and I'd really like to keep it that way.

Can we use an alternative to the `ICollection` interface to recognize collections?

**Comment by tisto** [comment]
I don't see an alternative to the Interface recognition here. We could create a conditional import and check for this interface only if p.a.contenttypes is installed though. I personally wouldn't mind a hard dependency on p.a.contenttypes. I know this package sometimes causes pain and needs some love, but only legacy instances do not use.

**Comment by lukasgraf** [comment]
@tisto hmm, I kinda do mind a hard dependency on `p.a.contenttypes`. We do actually have such a legacy instance (Plone 4.3.2) which we can't simply upgrade to the most recent 4.3.x yet until some `z3c.form` woes are sorted out :wink: 

I'll open a PR to rewrite this using a conditional import sometime soon.

**Comment by tisto** [comment]
@lukasgraf I know, this is why I just stated my personal preference and left the decision to you. :)
