### ISSUE TITLE
The live demo heroku link doesn't work

### ISSUE THREAD

**Issue by witekdev** [plone/plone.restapi#52]
I get:
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.
If you are the application owner, check your logs for details.

when trying to access: http://arcane-sierra-8467.herokuapp.com/Plone/@@json

**Comment by tisto** [comment]
@witekdev thanks for the info. Will try to find time to look into it...

**Comment by tisto** [comment]
The heroku demo is back online. Though, I think we removed the @@json view at some point. Therefore it is impossible to browse the api via browser.

**Comment by tisto** [comment]
Will close the issue here for now. New issue has been filed: https://github.com/plone/plone.restapi/issues/60

**Comment by witekdev** [comment]
Thanks for the update.
