### ISSUE TITLE
When using this package as a dependency in plone.importexport, I get zope.configuration.config.ConfigurationExecutionError: <class 'zope.interface.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'plone.app.controlpanel.Overview')

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.restapi#526]
Please check https://github.com/collective/plone.importexport/issues/13. I only solved it by explicitly adding:

`plone.restapi-2.0.0-py2.7.egg/plone/restapi/services/controlpanels/configure.zcml`:

```
  <include package="plone.app.controlpanel" file="permissions.zcml"/>
```

And to `plone.restapi-2.0.0-py2.7.egg/plone/restapi/services/multilingual/configure.zcml`:

```
    <include package="plone.app.multilingual" file="permissions.zcml"/>
```

Should this be added here? Why the problem happens in a plone.importexport context but [not in your CI](https://travis-ci.org/plone/plone.restapi/builds/371875639)?

**Comment by tisto** [comment]
@idgserpro please provide us with more information so we can help. Try to provide us with a minimal example that we can use to re-produce the problem.

**Comment by idgserpro** [comment]
Just by running https://github.com/collective/plone.importexport#installation this error would raise. But I just tested and it seems the error is gone. If you test it like it's stated in the link and `bin/instance fg` works I think this issue an be closed.

**Comment by tisto** [comment]
Fixed and released with https://pypi.org/project/plone.restapi/3.7.4/#id1
