### ISSUE TITLE
X-XSS-Protection

### ISSUE THREAD

**Issue by IolaneAndrade** [plone/plone.restapi#528]
**plone.restapi makes it possible to disables XSS filtering?**

in my plone site I used the plone.restapi to configure CORS and enable a link of a streaming to be transmitted on the site.
However streaming is only working for anonymous users to watch.

I believe it could be **X-XSS-Protection**, and I would like to customize it

**Comment by tisto** [comment]
I think this is a duplicate of #155. Let's continue the discussion there...
