### ISSUE TITLE
Any option to disable batching (for @search)?

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#530]
Is there a way to disable the batching feature for particular endpoints? In my case I need to query the ZCatalog over `@search` and I need all results without batching.

**Comment by tisto** [comment]
@zopyx have you tried setting the batch_size param to a high value? http://plonerestapi.readthedocs.io/en/latest/batching.html?highlight=batching#parameters

**Comment by tisto** [comment]
cc @ajayns ^^^

**Comment by ajayns** [comment]
@tisto 
Yes, I've gone through the `batch_size` parameter, but for the plugin, which is supposed to support any number of items, it's not good to have a particular number as a limit right? So a recursive approach was the best to go with unless there exists an option to prevent batching itself.

The approach I've used for fetching the whole list of content objects by going through each branch can be seen [here](https://github.com/collective/gatsby-source-plone/blob/d4dd3a9bcfd050b00d3a4a90ff7358a9b618f3fd/src/gatsby-node.js#L51-L60) @zopyx 

https://github.com/collective/gatsby-source-plone/blob/d4dd3a9bcfd050b00d3a4a90ff7358a9b618f3fd/src/gatsby-node.js#L51-L60

**Comment by tisto** [comment]
@ajayns maybe this is already implemented but we could say that using "batch_size=-1" will disable batching. Maybe also "batch_size=0" and "batch_size=False". Could you do a quick check of how the current implementation behaves? Then we can draft a solution to this.

**Comment by tisto** [comment]
@ajayns it seems the implementation is more complex than I thought. See #303 for details. I am closing this issue since it is a duplicate.
