### ISSUE TITLE
@types/Event TypeError: ... is not JSON serializable

### ISSUE THREAD

**Issue by datakurre** [plone/plone.restapi#574]
```
Plone 5.1.2.1 (5112)
CMF 2.2.12
Zope 2.13.27
Python 2.7.15 (default, Apr 29 2018, 23:18:59) [GCC 7.3.0]
PIL 5.0.0 (Pillow)
RESTful hypermedia API for Plone. – (plone.restapi 3.2.2.dev0) 
```

`curl -H "Accept: application/json" --user "admin:admin" "http://localhost:8080/Plone/@types/Event"`

```
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 23, in __call__
  Module plone.restapi.services, line 22, in render
  Module json, line 251, in dumps
  Module json.encoder, line 209, in encode
  Module json.encoder, line 434, in _iterencode
  Module json.encoder, line 408, in _iterencode_dict
  Module json.encoder, line 408, in _iterencode_dict
  Module json.encoder, line 408, in _iterencode_dict
  Module json.encoder, line 442, in _iterencode
  Module json.encoder, line 184, in default
TypeError: datetime.datetime(2018, 6, 28, 22, 0, tzinfo=<DstTzInfo 'Europe/Helsinki' EEST+3:00:00 DST>) is not JSON serializable
```

**Comment by datakurre** [comment]
* [ ] start.default is datetime object
* [ ] start.default_timezone is function
* [ ] end.default is datetime object
* [ ] end.default_timezone is function
* [ ] recurrence.first_day is function

**Comment by davisagli** [comment]
This is addressed in the branch where I also worked on improving the vocabularies endpoint, and probably should be moved from there to a separate branch since the vocab changes are not backwards-compatible.

David Glick
(mobile)

**Comment by tisto** [comment]
@davisagli any chance you can give us a pointer to that code? If you don't have the time maybe someone else can factor that out and create a new pull request.

**Comment by davisagli** [comment]
Here: https://github.com/plone/plone.restapi/commit/8f82b34c8126292fbc4142c1a4fb05eaf1742253

The important parts of that are calling widget parameters that are callable, and adapting the properties to IJsonCompatible so that dates get serialized.

**Comment by tisto** [comment]
@davisagli thanks! Any pointers to the tests? :)

**Comment by davisagli** [comment]
Yeah, yeah...okay, here's a PR that includes these fixes and a test. :) https://github.com/plone/plone.restapi/pull/618
