### ISSUE TITLE
Installation of 3.2.x on Plone 4.3 fails

### ISSUE THREAD

**Issue by wobsta** [plone/plone.restapi#575]
I observe the folling error during buildout:

>     ZopeXMLConfigurationError: File "/home/wobsta/plone/tagung/buildout/eggs/plone.restapi-3.2.1-py2.7.egg/plone/restapi/configure.zcml", line 72.4-78.8
>     ConfigurationError: ('Unrecognized parameters:', 'name')

The older 3.1.0 release, however, works flawlessly.

**Comment by tisto** [comment]
@wobsta thanks for the bug report. Could you please provide the full trace and the exact Plone 4.3 version you are using? We are testing plone.restapi on Travis. Though, it could be that we did not catch all possible configurations.

**Comment by wobsta** [comment]
I'm on Plone 4.3.6 with all security patches in place (at least as far as I know). Please find the buildout log attached. The error goes away when I pin version 3.1.0 ...

[buildout.log](https://github.com/plone/plone.restapi/files/2149206/buildout.log)

**Comment by tisto** [comment]
@wobsta I just tried a fresh 4.3.14 buildout, that works without an issue. Will try 4.3.6 now:

```
[buildout]
extends = https://dist.plone.org/release/4.3.14/versions.cfg
parts = instance

[instance]
recipe = plone.recipe.zope2instance
http-address = 8080
user = admin:admin
eggs =
    Plone
    plone.restapi

[versions]
setuptools =
zc.buildout =
```

**Comment by tisto** [comment]
Plone 4.3.6 works as well for me:

```
[buildout]
extends = https://dist.plone.org/release/4.3.6/versions.cfg
parts = instance

[instance]
recipe = plone.recipe.zope2instance
http-address = 8080
user = admin:admin
eggs =
    Plone
    plone.restapi

[versions]
setuptools =
zc.buildout =
```

**Comment by tisto** [comment]
@wobsta do you have Dexterity installed on your site? The buildout run fails at that line:

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/configure.zcml#L72

This shouldn't be executed at all if you do not have Dexterity installed.

https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/configure.zcml#L68

**Comment by tisto** [comment]
@sneridagh any idea? ^^^

**Comment by wobsta** [comment]
@tisto: I do have dexterity installed on this site. It seems to be used by some of the content types in use. (Didn't wrote that myself.)

> wobsta@dpg-websrv:~/plone/tagung/dev$ grep -i dexterity bin/instance
>   '/home/wobsta/plone/tagung/buildout/eggs/plone.app.dexterity-2.0.13-py2.7.egg',
>   '/home/wobsta/plone/tagung/buildout/eggs/plone.directives.dexterity-1.0.2-py2.7.egg',
>   '/home/wobsta/plone/tagung/buildout/eggs/plone.dexterity-2.2.4-py2.7.egg',

@sunew: I'm on plone.behavior 1.0.3:

> wobsta@dpg-websrv:~/plone/tagung/dev$ grep -i plone.behavior bin/instance
>   '/home/wobsta/plone/tagung/buildout/eggs/plone.behavior-1.0.3-py2.7.egg',

**Comment by tisto** [comment]
@wobsta pls provide the plone.schema version and try to pin plone.schema to 1.2.0.

**Comment by sunew** [comment]
the name attribute for plone:behavior directice was added in plone.behavior 1.1
https://pypi.org/project/plone.behavior/#id7

this explains your problem.

**Comment by tisto** [comment]
A version pin in setup.py makes sense IMHO.
