### ISSUE TITLE
Documentation: dates changes in .resp on 5.2

### ISSUE THREAD

**Issue by sunew** [plone/plone.restapi#576]
On current 5.2 coredev build, the creation and modification dates change.

```
diff --git a/src/plone/restapi/tests/http-examples/content_get.resp b/src/plone/restapi/tests/http-examples/content_get.resp
index 3cee366..58602ab 100644
--- a/src/plone/restapi/tests/http-examples/content_get.resp
+++ b/src/plone/restapi/tests/http-examples/content_get.resp
@@ -22,7 +22,7 @@ Content-Type: application/json
   "allow_discussion": false, 
   "changeNote": "", 
   "contributors": [], 
-  "created": "2016-10-21T19:00:00+00:00", 
+  "created": "2016-10-21T21:00:00+00:00", 
   "creators": [
     "admin"
   ], 
@@ -34,7 +34,7 @@ Content-Type: application/json
   "is_folderish": false, 
   "language": "", 
   "layout": "document_view", 
-  "modified": "2016-10-21T19:00:00+00:00", 
+  "modified": "2016-10-21T21:00:00+00:00", 
   "parent": {
     "@id": "http://localhost:55001/plone/folder", 
     "@type": "Folder", 


```

**Comment by tisto** [comment]
@sunew hmm. That shouldn't be the case. We freeze the dates for the documentation to avoid this problem. How do you get to that diff? 

@lukasgraf any idea?

**Comment by sunew** [comment]
@tisto simply by running the documentation test on coredev 5.2 
Its off by two hours - tz related.

**Comment by lukasgraf** [comment]
`plone.dexterity` determines the local TZ once, at module load time [in `plone.dexterity.content`](https://github.com/plone/plone.dexterity/blob/242a6272043e344a4fdc38ee5ebcd76f7669cc22/plone/dexterity/content.py#L54). This is then used for DC metadata like [`CreationDate`](https://github.com/plone/plone.dexterity/blob/242a6272043e344a4fdc38ee5ebcd76f7669cc22/plone/dexterity/content.py#L492-L501).

I got surprised by this in a different context just recently, I could imagine that it's related to what we're seeing here.

**Comment by davisagli** [comment]
Fixed in https://github.com/plone/plone.restapi/pull/1647
