### ISSUE TITLE
End point for showing status messages?

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#584]
Is there yet an endpoint that I can query to get the status messages for the current user?

Use case: I have a PAS plugin that tries to authenticate the user with an external service. It may get an informative error message back ('you have too many concurrent sessions open') that I would like to show to the user. I use `api.portal.show_message` for that. After this, the rest of the PAS machinery continues normally, likely resulting in an anonymous user, which is fine.

In standard Plone, the status message shows up fine.
With `plone.restapi` I never get the message, and I don't see an endpoint for this in the documentation on https://plonerestapi.readthedocs.io/.

In this specific case, I could override the `@login` endpoint and check the status messages there, or use some other way of passing this error message to the `@login` endpoint. I am in fact already overriding it (see #582) so that should be doable.

But in general it seems useful to be able to get the status messages via an endpoint.

Or possibly add them in a key `status_messages` in *all* replies. But that would be a bigger change.

**Comment by tisto** [comment]
@mauritsvanrees we currently do not have an endpoint for status messages. What we do so far is that the backend returns error messages that the frontend (e.g. Plone-React) can pick up and show to the user.

**Comment by davisagli** [comment]
Adding a status message sets the `statusmessages` cookie, so they should already be available in your client after making a request that adds a status message. Maybe you just need to check for and display this cookie after each request to the server.
