### ISSUE TITLE
Make JWT token_timeout configureable

### ISSUE THREAD

**Issue by MrTango** [plone/plone.restapi#625]
Right now the timeout is hardcoded in the PAS plugin:

https://github.com/plone/plone.restapi/blob/58b63530fb0753276670829742bf45e15ad35024/src/plone/restapi/pas/plugin.py#L53

But for testing purposes and higher security needs this shoud be configureable thru the plone.registry.
This would be good to have i a future controlpanel.

**Comment by lukasgraf** [comment]
@MrTango it already already is 😉 
`ZMI -> acl_users -> jwt_auth -> "Configuration" tab`

![jwt_token_timeout](https://user-images.githubusercontent.com/405124/46608773-2e30ea00-cb06-11e8-97e0-f576a60b38a2.png)

Or do you actually mean a control panel outside the ZMI, in addition to the Plugin configuration?

**Comment by buchi** [comment]
The timeout is already configurable in the ZMI.
