### ISSUE TITLE
HTTP examples in docs are broken

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#627]
It seems all our HTTP examples in the docs are broken, e.g.:

https://plonerestapi.readthedocs.io/en/latest/authentication.html#json-web-tokens-jwt

**Comment by lukasgraf** [comment]
@tisto I looked into this.

There is a bug in the recently released `sphinxcontrib-httpexample==0.10.0` that prevents requests/responses being included from the filesystem, like we do in `plone.restapi`. I created an issue: collective/sphinxcontrib-httpexample#41

The reason we're getting the newest version is that there's no version constraint in [`docs/source/readthedocs-requirements.txt`](https://github.com/plone/plone.restapi/blob/master/docs/source/readthedocs-requirements.txt), which is used by the [RTD build](https://readthedocs.org/dashboard/plonerestapi/advanced/).

---

![rtd_build](https://user-images.githubusercontent.com/405124/47271650-d1a8e280-d57b-11e8-829a-9dd9179a78eb.png)

---

So our version constraints from [`requirements.txt`](https://github.com/plone/plone.restapi/blob/master/requirements.txt) at the package root don't apply to the RTD build. I tried changing the build to use that `requirements.txt`, but that resulted in some CSS issues and lots of visual changes, so I switched it back.

For now I'll do a PR that just pins 'sphinxcontrib-httpexample` in `readthedocs-requirements.txt` to fix the issue at hand - I might have time to look some more into the reqirements story as a whole next week.
