### ISSUE TITLE
No metadata fields with GET on a folderish resource

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#681]
`items`  contains only URL and title of subresources contained with a Folder. This usually not enough for generating even minimal listings . For fetching additional metadata on a resource you need to perform individual requests for each item of `items`. This is inefficient. 

```
        {
            "@id": "https://server.onkopedia.com/de/news",
            "@type": "Folder",
            "description": "",
            "review_state": "published",
            "title": "Nachrichten"
        },
```

The `@search` endpoint supports  the `metadara_field` query parameter for receiving additional metadata for all found items.

We need something similar for GET on a folderish resource in order to build efficient frontends. An application must be able to fetch all related `items` with all requested metadata in one API call instead using #(len(items)) additional API calls.

**Comment by sneridagh** [comment]
The @search endpoint supports a `fullobjects` parameter: 
https://plonerestapi.readthedocs.io/en/latest/searching.html?highlight=fullobjects#retrieving-full-objects

You have the option to enhance the GET serializer to match your requirements using a more specific adapter.

I guess that it would make sense to add the `fullobjects` param to the GET by default, something to discuss about it.

**Comment by zopyx** [comment]
You want to support both `fullobjects` and `metadata_fields` for the sake of API consistency. But `fullobjects` is not a replacement for `metadata_fields` because `fullobjects` wakes up all objects while the `metadata_fields` information could be determined more efficiently from the brains.
