### ISSUE TITLE
Start using Black

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#693]
I'd like to give Black a shot for plone.restapi. Though, we should carefully think about the time where we introduce it because all existing pull requests might require a significant amount of time to re-base.

**Comment by davisagli** [comment]
@tisto speaking from experience, it's not too bad because as long as all the code in the open pull requests is syntactically valid, you can just run black on the branches at the same time you do on master, and end up making the same changes in both places.

**Comment by mauritsvanrees** [comment]
To not change too much in current core Plone code, I usually call black with a small bash wrapper:

```
$ cat ~/bin/blackmy 
#! /bin/sh
black --skip-string-normalization --line-length 79 $*
```

The skip-string-normalization option tells black to not change single quotes to double quotes.
Both settings are up for discussion (and `black` would like you to not actually discuss this, but simply accept its defaults).
I don't want to start such a discussion here.  Just a small report from one person who is starting to use `black` more and more.

**Comment by tisto** [comment]
@mauritsvanrees thank you for sharing! Though, I personally prefer to go all in. After using prettier in JS I don't want to go back. I want an opinionated auto-formatter without any customizations. I actually dislike that black allows those customizations, even though I disagree with their 88 chars decision. :)

**Comment by davisagli** [comment]
@mauritsvanrees you can also put the configuration in pyproject.toml instead of using a shell wrapper. https://github.com/ambv/black#pyprojecttoml

**Comment by idgserpro** [comment]
Do you have plans to add this across all codebase? How should we document this in https://docs.plone.org/develop/styleguide/python.html?

Another example: the official .editorconfig in https://docs.plone.org/develop/styleguide/editor.html is different from the file here in plone.restapi. Should we use it?

**Comment by mauritsvanrees** [comment]
Yes, there is [PLIP 2754](https://github.com/plone/Products.CMFPlone/issues/2754) that wants to do this over the whole Plone code base.

**Comment by idgserpro** [comment]
> Another example: the official .editorconfig in https://docs.plone.org/develop/styleguide/editor.html is different from the file here in plone.restapi. Should we use it?

bobtemplates.plone creates an `.editorconfig`.

**Comment by idgserpro** [comment]
Shouldn't this be closed after https://github.com/plone/plone.restapi/pull/734/ was merged?

**Comment by Rotonen** [comment]
Seems you opted to pepper the line length breakages black prefers for readability with inline `#noqa` comments instead of turning all line length checking off in the linters used.

Only one thing should be in control of line length and it should be black.
