### ISSUE TITLE
Change workflow state of an object with plone.restapi

### ISSUE THREAD

**Issue by adrianschulz** [plone/plone.restapi#73]
Is there a way to change the workflow state of an object with plone.restapi? In the documentaton (http://plonerestapi.readthedocs.org/en/latest/introduction.html) I didn't see anything about it.

**Comment by tisto** [comment]
No. This is not implemented yet.

**Comment by adrianschulz** [comment]
Thank you for your answer. 
I am wondering if it's already on your todo list because I think it would be an interesting feature.

**Comment by tisto** [comment]
It's planed for milestone 0.5.
