### ISSUE TITLE
How to set relatedItems?

### ISSUE THREAD

**Issue by zopyx** [plone/plone.restapi#732]
The documentation for setting a relation  https://plonerestapi.readthedocs.io/en/latest/serialization.html#relations is a bit short.

On the source side we have  a list of UIDs (from AT content) and need to set them as `relatedItems` on the related resource. Source and target system use the same UIDs. 

What is the correct data format for settings UIDs? Any example?

**Comment by buchi** [comment]
You can set `relatedItems` either by UID, path, URL or intid.

Examples:

```json
{
  "relatedItems": [
    "158e5361282647e39bf0698fe238814b",
    "5597250bda4b41eab6ed37cd25fb0979"
  ]
}
```

```json
{
  "relatedItems": ["/page1", "/page2"]
}
```

```json
{
  "relatedItems": [
    "http://localhost:8080/Plone/page1",
    "http://localhost:8080/Plone/page2"
  ]
}
```

```json
{
  "relatedItems": [347127075, 347127076]
}
```

**Comment by zopyx** [comment]
Thanks...this example should be put into the documentation. It's more understandable than having text only.
