### ISSUE TITLE
plone.restapi breaks Plone 5.0.4 File bulk uploads

### ISSUE THREAD

**Issue by mjmare** [plone/plone.restapi#74]
Having Plone.restapi (plone.restapi 0.1, plone.rest = 1.0a5) installed breaks the file upload functionality in a stock Plone 5 (at least in versions 5.0.3/4). Dragging files into the upload area and pressing upload yields the text "The file upload failed" just below the filename and nothing happens. 

![my_docs_ _site](https://cloud.githubusercontent.com/assets/1711378/14566081/4a9169ba-032e-11e6-9e60-9a88fd84fbdc.png)

I have installed plone restapi with:
`auto-checkout = plone.restapi

eggs =
    Plone
    Pillow
	plone.restapi

[sources]
plone.restapi = git https://github.com/plone/plone.restapi
`
and running buildout -c develop.cfg.

Disabling the restapi egg restores file uploads. 

The Plone error log show two errors (after clearing "Ignored exception types"):

`Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 523, in traverse
  Module ZPublisher.HTTPResponse, line 727, in debugError
NotFound:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Debugging Notice</strong></p>

  Zope has encountered a problem publishing your object.<p>
Cannot locate object at: http://localhost:8080/testing/my-docs/fileUpload</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>`

and:

`Traceback (innermost last):
  Module ZPublisher.Publish, line 127, in publish
  Module ZPublisher.BaseRequest, line 508, in traverse
  Module ZPublisher.BaseRequest, line 332, in traverseName
  Module zope.traversing.namespace, line 112, in namespaceLookup
  Module Products.CMFPlone.traversal, line 39, in traverse
  Module plone.resource.traversal, line 27, in traverse
NotFound`

**Comment by tisto** [comment]
@mjmare thanks for the detailed bug report. we will look into it!

**Comment by mjmare** [comment]
You're welcome!

**Comment by lukasgraf** [comment]
This issue most likely originates in `plone.rest`.

The failing request is made to the `fileUpload` browser view with `Accept: application/json`.
 
If a request with an `Accept` header other than `text/html` is handled, [`mark_as_api_request()`](https://github.com/plone/plone.rest/blob/c31662a13fdd8ea6b6db5769cd140d7d8776f0b4/src/plone/rest/events.py#L7-L22) flags the request with `IAPIRequest` as soon as at least one service registered for that content-type and HTTP method exists in the service registry.

This will then cause a `KeyError` to be raised in [`plone.rest.traverse`](https://github.com/plone/plone.rest/blob/c31662a13fdd8ea6b6db5769cd140d7d8776f0b4/src/plone/rest/traverse.py#L19-L25) because the conditions don't match. => 404

Failing test (for `plone.rest`):

```python
#class TestTraversal(unittest.TestCase):

    def test_json_request_to_regular_view_still_possible(self):
        obj = self.traverse('/plone/some-view')
        self.assertEquals(obj(), '{"msg": "Hello from SomeView"}')
```

```python
from Products.Five.browser import BrowserView
import json

class SomeView(BrowserView):
    def __call__(self):
        return json.dumps({'msg': 'Hello from SomeView'})
```
```xml
  <browser:page
    name="some-view"
    for="*"
    class=".tests.view.SomeView"
    permission="zope2.View"
    />
```

/cc @buchi

**Comment by tisto** [comment]
This is actually a plone.rest issue. Moved it there: https://github.com/plone/plone.rest/issues/50

**Comment by lukasgraf** [comment]
@mjmare fixed in current `master` of `plone.rest` (see plone/plone.rest#53).
