### ISSUE TITLE
Serialization of multiple vocabulary entries leads to Server Error

### ISSUE THREAD

**Issue by ukretschmer** [plone/plone.restapi#788]
https://github.com/plone/plone.restapi/blob/cbf3c07c94c8b9d4d624b6e31c4d21f9f3b94a6d/src/plone/restapi/serializer/dxfields.py#L71

**Error**

```
2019-08-24 19:06:54 ERROR Zope.SiteErrorLog 1566666414.130.724885414754 http://localhost:8080/Plone/test/GET_application_json_
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 23, in __call__
  Module plone.restapi.services, line 21, in render
  Module plone.restapi.services.content.get, line 18, in reply
  Module plone.restapi.serializer.dxcontent, line 125, in __call__
  Module plone.restapi.serializer.dxcontent, line 83, in __call__
  Module plone.restapi.serializer.dxfields, line 71, in __call__
TypeError: unhashable type: 'dict'
```

**Steps to reproduce**
Create a DX contenttype with a multi selection field, configure it to use a vocabulary for available options. Than create an object of that type with at least one chosen term.

**Problem**
At plone.restapi.serializer.dxfields, line 71 there is `value = self.field._type(values)` this code. I'm not sure, what the intention was what to do here, with this  `_type` function. IMO at this line values should just be assigned to value and all works well.

So replacing that line by `value = values` fixes the error. But as I said, not sure about the initial idea.

**Comment by tisto** [comment]
@ukretschmer thank you for reporting this issue. Could you imagine to write a unit/integration test that shows the problem?
