### ISSUE TITLE
TUS Endpoint

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#79]
http://tus.io/

**Comment by djay** [comment]
TUS is already in the plone core in the structure pattern. @vangheem

**Comment by tisto** [comment]
https://github.com/vangheem/tus

**Comment by tisto** [comment]
@vangheem could you point us to the current implementation of TUS in p.a.widgets? The link in the tus python package docs (https://github.com/vangheem/tus) is broken:

https://github.com/plone/plone.app.widgets/blob/master/plone/app/widgets/browser/file.py#L91

**Comment by vangheem** [comment]
The implementation is in https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/file.py now

**Comment by tisto** [comment]
@buchi you already have a basic implementation now, right? Would you mind pushing your work or even create a WIP pull request? I'm about to prepare a summary of the Beethoven Sprint and I would like to provide a link to that.

**Comment by buchi** [comment]
@tisto current state is in #261

**Comment by tisto** [comment]
Just for the record, I will add my personal notes from our discussion at Beethoven Sprint:

TUS
---

(florian, nathan, ramon, thomas, timo, victor)

File is an attribute

traversable services in plone.restapi

two separate endpoints for upload

my-file/@upload
my-file/@tus-upload CRUD

use a tmpfile (either use nfs or sticky session)
