### ISSUE TITLE
Bug: SearchableText indexing fails for blocks with empty blocks of text

### ISSUE THREAD

**Issue by tiberiuichim** [plone/plone.restapi#855]
```
for paragraph in block.get("text").get("blocks"):
```
should be
```
for paragraph in block.get("text", {}).get("blocks", []):
```

**Comment by tisto** [comment]
@tiberiuichim would you mind adding steps-to-reproduce here? Is it possible to create such a block structure with Volto currently?

We should make the code more robust like you propose anyways. I'd just like to understand how you got there. :)

**Comment by tiberiuichim** [comment]
I've just tested on volto.kitconcept.com demo. Easy to reproduce, create a new page, enter some text in a text block, hit enter (this creates a new text block that is empty), hit save.

```
  "blocks": {
    "0ad088b0-e178-44df-9d23-c12f31c88c15": {
      "@type": "text", 
      "text": {
        "blocks": [
          {
            "data": {}, 
            "depth": 0, 
            "entityRanges": [], 
            "inlineStyleRanges": [], 
            "key": "6qcol", 
            "text": "fds", 
            "type": "unstyled"
          }
        ], 
        "entityMap": {}
      }
    }, 
    "98028764-6b61-41bc-bc19-5d55967a1cf4": {
      "@type": "title"
    }, 
    "d4741a1c-5c4c-438d-a354-14176c5481c1": {
      "@type": "text"
    }
  },
```

I've just done this, above is snippet from ?fullobject network traffic.

**Comment by tisto** [comment]
@tiberiuichim just did that. I do not see any error on the network tab or in the console (when I do this locally with the latest Volto master).

**Comment by tisto** [comment]
@tiberiuichim can you still reproduce this error? Otherwise, I tend to close it...

**Comment by terapyon** [comment]
I got the same error for blocks with empty blocks of text. This is very important issue for us.

**Comment by tiberiuichim** [comment]
@tisto For future posterity, this is how to reproduce:

- create a Volto page
- only write text in the title block, don't write anything in the text block
- now look at the server response for ``my-page?fullobjects``. The value for the block field is like:

```
blocks: {
2c0ac9f0-3f6c-4665-b7f4-a4faae43c98a: {@type: "text"}
31323357-7be4-4252-b470-c6a394c5d994: {@type: "title"}
}
```

So you can see that the text block doesn't have a "text" property, it only has the ``@type`` property.

**Comment by tiberiuichim** [comment]
Closed as it has been fixed in master by the search indexing refactoring branch.

**Comment by tiberiuichim** [comment]
Actually I was wrong, the bug is still there:
```
for paragraph in block.get("text").get("blocks"):
```

**Comment by tisto** [comment]
@tiberiuichim would it be possible to add a failing Cypress test to Volto? We have a block indexing Cypress test already and it would be good to have to proof of failure and then for the fix.

**Comment by terapyon** [comment]
This is a big issue for me. And I think this is not only related volto but also restapi problem. Do you think about this? @tisto

**Comment by tisto** [comment]
@terapyon this is definitely a bug and it would be great to have a PR with a fix.

**Comment by terapyon** [comment]
This issue was already fixed in the master branch.
https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/indexers.py#L30
