### ISSUE TITLE
Implement PUT as well for updating content

### ISSUE THREAD

**Issue by lukasgraf** [plone/plone.restapi#86]
Right now only `PATCH` is implemented, which takes a diff of the object's representation as input for what fields should updated.

We also want to implement `PUT`, which would take the objects complete representation.

Discuss: What should happen if some fields are omitted by the client?

**Comment by tisto** [comment]
Postpone it to future release. If we make the API liberal in what it accept (robustness principle) for the PUT request it will be very close to PATCH. Let's implement a front-end first and then see if we need any additional functionality.
