### ISSUE TITLE
Implement File API

### ISSUE THREAD

**Issue by tisto** [plone/plone.restapi#9]
```

{
    contentType:
    size (kb)
    data/download
    filename
}
```

**Comment by davisagli** [comment]
data/download as a URI or embedded base64 data? The former is probably better (fewer bytes to download)

**Comment by tisto** [comment]
As URI. We might want to support embedded base64 data in future versions (maybe with framing).

**Comment by lukasgraf** [comment]
The current serialization for a `File` looks like this:

```json
{
  "@id": "http://localhost:8080/Plone/document.pdf",
  "@type": "File",
  "title": "My PDF document",
  "UID": "abef59538b3749debad950c3c5d35224",
  "...": "...",
  "file": "http://localhost:8080/Plone/document.pdf/@@download/file"
}
```

So a `Named[Blob]File` field gets serialized directly to its regular Plone download URL (as currently documented in the [Serialization](http://plonerestapi.readthedocs.io/en/latest/serialization.html#file-fields) chapter).

I would propose to change the serialization to something that is slightly more in line with the format used for deserialization (upload):

```json
{
  "@id": "http://localhost:8080/Plone/document.pdf",
  "...": "...",
  "file": {
    "filename": "document.pdf",
    "content-type": "application/pdf",
    "size": 65536,
    "download": "http://localhost:8080/Plone/document.pdf/@@download/file"
  }
}
```

That way, clients would have the necessary information to render a decent download link, including icon, filename and size without doing a second request.

The contract would then be that the client can do a `GET` request to the URL specified in `download`, with the same credentials, and will get back a response with appropriate `Content-Disposition`, `Content-Length`, and `Content-Type` headers as indicated in the metadata.

The same principle could probably be applied to images scales.

/cc @tisto @buchi

**Comment by tisto** [comment]
@lukasgraf you proposal looks good to me. It is essential that serialization/deserialization use the same structure. I guess from a HTTP spec perspective it would be correct if the client would send a GET request to "http://localhost:8080/Plone/document.pdf/@@download/file" with Accept "application/pdf" header. Though, since it works without the Accept header in Plone as well I guess we don't have to be pedantic about it.

**Comment by lukasgraf** [comment]
@tisto I agree, this would be the proper behavior. But since `Accept: */*` or no Accept header at all would also happen to work, we might just phrase this as a recommendation to the client / description of how the server is expected to behave in the docs.

I'll start working on this (and Images) then, PR coming up.

**Comment by tisto** [comment]
Closed by https://github.com/plone/plone.restapi/pull/115
