### ISSUE TITLE
Add next/prev information

### ISSUE THREAD

**Issue by rodfersou** [plone/plone.restapi#900]
## Show next / prev items in a folder
- [x] Follow behavior for next prev as much as possible
- [x] Expose information when serialize
- [x] Create tests
- [x] Implement feature
- [x] Run performance tests

**Comment by tisto** [comment]
Proposed API design from a discussion with @sneridagh @rodfersou:

````
"next_item": {
    "@id": "http://localhost:55001/plone/folder", 
    "@type": "Folder", 
    "description": "This is a folder with two documents", 
    "title": "My Folder"
  }, 

"previous_item": {
    "@id": "http://localhost:55001/plone/folder", 
    "@type": "Folder", 
    "description": "This is a folder with two documents", 
    "title": "My Folder"
  }, 
````

**Comment by tisto** [comment]
@rodfersou please add a docs section to: 

https://plonerestapi.readthedocs.io/en/latest/serialization.html

**Comment by tisto** [comment]
Just for the record a link to how Hydra (JSON-LD) does it: 

https://www.w3.org/community/hydra/wiki/Pagination

**Comment by tisto** [comment]
@plone/restapi-team this is a proposed enhancement of the content serializer to support next/previous navigation within a folder:

````
"next_item": {
    "@id": "http://localhost:55001/plone/folder", 
    "@type": "Folder", 
    "description": "This is a folder with two documents", 
    "title": "My Folder"
  }, 

"previous_item": {
    "@id": "http://localhost:55001/plone/folder", 
    "@type": "Folder", 
    "description": "This is a folder with two documents", 
    "title": "My Folder"
  }, 

"parent": {
    "@id": "http://localhost:55001/plone", 
    "@type": "Plone Site", 
    "description": "", 
    "title": "Plone site"
  }, 
````

This is a request for comments. :)
