### ISSUE TITLE
plone 4.3 + plone.app.users 2.1.0 No module named userdataschema

### ISSUE THREAD

**Issue by robystar** [plone/plone.restapi#908]
plone 4.3 + plone.app.users 2.1.0  is not compatible, class name has changed

File "/home/plone/iol/eggs/plone.restapi-6.5.0-py2.7.egg/plone/restapi/serializer/user.py", line 22, in <module>
    from plone.app.users.userdataschema import IUserDataSchemaProvider

**Comment by tisto** [comment]
@robystar thanks for reporting! May I ask about your use case for Plone 4.3 and Plone REST API?

We could do a minimum version declaration on setup.py regarding p.a.users. Though, this might cause version conflicts.

Our policy regarding old Plone versions is that we try to support them as much as possible in a sense that we do not remove compatibility (yet). Though, this highly depends on how much effort people are willing to put into this. In the past @buchi and @lukasgraf were the main drivers behind the Plone 4.3 support and if I am not mistaken they are still on this version. If we add newer features (especially for Volto), we usually focus on Plone 5.2 / Python 3 only.

**Comment by robystar** [comment]
ok,I understand. We share Plone users and groups with php applications developed by others. No problem, we can avoid to upgrade plone.app.users.
