### ISSUE TITLE
Tag 6.9.0 was made, but is not on master

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#936]
Result is that `CHANGES.rst` on master still has 6.8.1 as the last release.
Did something go wrong during release?

Also, a few `plone.restapi` tests go wrong on Jenkins on Plone 6.0. No idea if that is at all related, or if those would be fixed when we update `plone.restapi` in the versions. Ah, no, it is in the checkouts, so that is probably not the problem.

**Comment by mauritsvanrees** [comment]
Forgot the link to test failures:
https://jenkins.plone.org/job/plone-6.0-python-3.8/lastCompletedBuild/testReport/
(That is 3.8, but 3.7 and 3.6 have same or similar failures. But as said, likely unrelated.)

**Comment by tisto** [comment]
@mauritsvanrees things are a bit complicated right now because we have two active branches (6.x.x. and master). I fixed the failing 5.2 and 6.0 branch the other day. I will check this and the release on the machine where I did the release later today.

**Comment by tisto** [comment]
@mauritsvanrees I merged 6.x.x into master again. Now things should be in place. The 6.0 branch is green again as far as I can see. Closing...
