### ISSUE TITLE
plone.restapi 6.13.1 does not start in Plone4

### ISSUE THREAD

**Issue by gbastien** [plone/plone.restapi#956]
Hi @tisto @sneridagh 

I think #940 breaks fix reported in #694, in Plone4, plone.restapi fails to start with error :
ConfigurationExecutionError: <class 'zope.component.interfaces.ComponentLookupError'>: (<InterfaceClass zope.security.interfaces.IPermission>, 'plone.app.controlpanel.Overview')

This is because now controlpanels service is only loaded in Plone5 and the configure.zcml into controlpanels is doing the job of including permissions.zcml but is no more called.

I think moving this from services/controlpanels/configure.zcml to services/configure.zcml would fix the problem.  Or at least add the same fix to database service.

What do you think?

Thank you for great addon!

Gauthier

**Comment by tisto** [comment]
@gbastien I haven't had time to look into this in-depth but what you write makes sense. What I don't get it why our Plone 4 tests do not catch this. A PR with a fix would be welcome!

**Comment by gbastien** [comment]
@tisto we have the same behavior, tests pass (imio.restapi/plonemeeting.restapi packages) but instance fails to start...  this is related to package order, I do not know exactly difference regarding this between test and instance...

**Comment by tisto** [comment]
@gbastien yeah. I suspected something like this. It would be nice to have a test failing but this is way too much work to figure out, so I am good with a simple fix. :)

**Comment by gotcha** [comment]
Order of packages issues are often due to/hidden by `z3c.autoinclude` (I dunno if it is the case here). This is the reason why I try to not forget to explicitly include stuff in ZCML.

**Comment by tisto** [comment]
@gotcha yeah, thanks for the hint! I suspected something like this but I do not really have time to look into this right now. It bugs me that our test setup was not able to catch this regression.
