### ISSUE TITLE
Release for Plone 5.2.2.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#962]
I want to start on a Plone 5.2.2 release, see https://github.com/plone/Products.CMFPlone/issues/3119

Coredev branch 5.2 has `plone.restapi` in the `checkouts.cfg` and has pinned 6.8.0. Latest releases are 7.0.0 alpha releases. Maybe it is best to use latest stable 6.13.2. What do you recommend?

**Comment by tisto** [comment]
@mauritsvanrees awesome! Yeah, 6.13.2 would be the best choice for 5.2.2.

**Comment by tisto** [comment]
@mauritsvanrees https://pypi.org/project/plone.restapi/6.13.4/ is out. Any release within 6.13.x should do. Will close the issue now.
