### ISSUE TITLE
Parameter "metadata_fields" of serializer.catalog.LazyCatalogResultSerializer is not used

### ISSUE THREAD

**Issue by gbastien** [plone/plone.restapi#970]
Hi @tisto

me again ;-)

In search/handler.SearchHandler.search, the metadata_fields is managed to be passed to ISerializeToJson serializer (LazyCatalogResultSerializer).

The LazyCatalogResultSerializer receives the metadata_fields but does nothing with it, instead the called ISerializeToJson that renders the brain get the metadata_fields again in the request.form in the metadata_fields method.

Where it does again the same work more or less than in SearchHandler.

As the DefaultJSONSummarySerializer is doing it, to me we should just remove metadata_fields as a parameter and let it get it from request.form.

For now, it only work if in request.form.

I can propose a PR to clean this because I was lost into this and I suppose other could be also.

Thank you,

Gauthier

**Comment by tisto** [comment]
@gbastien thanks for working on p.restapi and contributing! Keep it going! :)
