### ISSUE TITLE
plone.api dependency in upgrade code

### ISSUE THREAD

**Issue by erral** [plone/plone.restapi#971]
There is an undeclared plone.api dependency in [upgrade.py](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/upgrades/ordering.py#L3)

I ran into this when installing plone.restapi in Plone 4.3.x

IIRC it was decided that it was not acceptable to have plone.api dependency except for tests, right?

**Comment by tisto** [comment]
Yes. That is correct. We should remove this dependency.
