### ISSUE TITLE
Three test failures in test_dxfield_serializer when using 6.13.4

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.restapi#974]
On Jenkins, I pinned 6.13.4, but that led to three test failures.
https://jenkins.plone.org/job/plone-5.2-python-3.8/593/testReport/
The tests expect for example `http://nohost/plone/doc1/@@images/uuid_1.png` but they get ` .gif` file, or the other way around.
With master checked out, the tests are green again, so I did that for now: https://github.com/plone/buildout.coredev/commit/194f18f2936e5b7c56a7d42d1a759c3e1ab7661a

Is there maybe a test fix on the master branch that needs back porting to the 6.x.x branch?

**Comment by erral** [comment]
This must be related to https://github.com/plone/plone.restapi/pull/925 and the changes on plone.namedfile

**Comment by tisto** [comment]
@mauritsvanrees uh, sorry about that. Keeping those two branches in sync is actually non-trivial and lots of work. Will look into it...

**Comment by mauritsvanrees** [comment]
Thanks. Since it is only in the tests, it should still be fine to use the latest 6.13.4 in a Plone 5.2.2 release, or certainly in a beta/pending.

**Comment by tisto** [comment]
Just checked and #925 indeed has been only released in the 7.x branch. I Will see if I can backport this.
